package io.destinyos.engines.tarot;

import io.destinyos.core.signal.Polarity;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * Vietnamese interpretive content for one card (Master Spec section 17,
 * research item R11).
 *
 * <p>Authored once as versioned reference data (see
 * {@link TarotCardMeanings}), never generated at runtime — R11's own
 * constraint: "Card meanings must be authored or sourced, not generated by
 * the LLM at runtime" (CLAUDE.md Rule B). Grounded in the standard,
 * decades-converged Rider-Waite-Smith interpretive tradition (A.E. Waite's
 * 1910 <i>Pictorial Key to the Tarot</i> and the consistent derivative
 * corpus since), not free-associated.
 *
 * <p>{@code uprightPolarity}/{@code reversedPolarity} are a labelled
 * simplification: one polarity per orientation, not per dimension. A card
 * could plausibly read as {@code SUPPORT} for career and {@code CAUTION}
 * for relationships in a full reading; this pass does not capture that
 * nuance. A future revision that sources per-dimension polarity would be a
 * {@code contentVersion} bump, not a bug fix.
 *
 * @param uprightKeywords    short keywords for the upright orientation
 * @param reversedKeywords   short keywords for the reversed orientation
 * @param uprightPolarity    this card's traditional direction when upright
 * @param reversedPolarity   this card's traditional direction when reversed
 *                           (traditionally often softened/complicated, not a
 *                           flat inversion of {@code uprightPolarity})
 * @param careerMeaning      interpretation for CAREER-dimension questions
 * @param financeMeaning     interpretation for FINANCE-dimension questions
 * @param relationshipMeaning interpretation for RELATIONSHIP-dimension questions
 * @param decisionMeaning    interpretation for DECISION-dimension questions
 * @param generalMeaning     interpretation with no specific dimension
 */
public record TarotCardMeaning(
        List<String> uprightKeywords,
        List<String> reversedKeywords,
        Polarity uprightPolarity,
        Polarity reversedPolarity,
        String careerMeaning,
        String financeMeaning,
        String relationshipMeaning,
        String decisionMeaning,
        String generalMeaning
) {
    public TarotCardMeaning {
        uprightKeywords = uprightKeywords == null ? List.of() : List.copyOf(uprightKeywords);
        reversedKeywords = reversedKeywords == null ? List.of() : List.copyOf(reversedKeywords);
    }

    /** No content authored yet for any field. */
    public static final TarotCardMeaning EMPTY =
            new TarotCardMeaning(List.of(), List.of(), null, null, null, null, null, null, null);

    public boolean isEmpty() {
        return this.equals(EMPTY);
    }

    public Optional<String> generalMeaningIfPresent() {
        return Optional.ofNullable(generalMeaning);
    }

    /** Polarity for the given orientation, or {@code null} if this card has no authored content. */
    public Polarity polarityFor(TarotOrientation orientation) {
        Objects.requireNonNull(orientation, "orientation");
        return orientation == TarotOrientation.UPRIGHT ? uprightPolarity : reversedPolarity;
    }
}
