package io.destinyos.engines.tarot;

import static org.assertj.core.api.Assertions.assertThat;

import io.destinyos.core.context.BirthTimePrecision;
import io.destinyos.core.context.CalculationContext;
import io.destinyos.core.result.EngineStatus;
import io.destinyos.core.signal.Dimension;
import io.destinyos.core.version.MethodologyVersions;
import java.time.Instant;
import java.time.ZoneId;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Behavioural contract of the seeded Tarot draw (DECISION_LOG C6,
 * Master Spec section 17).
 */
class TarotEngineTest {

    private final TarotEngine engine = new TarotEngine();

    private static CalculationContext context() {
        return new CalculationContext("calc-tarot-1", "TAROT_RWS",
                new MethodologyVersions("1.0", "1.0", "1.0", null),
                ZoneId.of("Asia/Ho_Chi_Minh"), Locale.forLanguageTag("vi-VN"), null,
                Instant.parse("2026-08-18T00:00:00Z"), null, null,
                BirthTimePrecision.UNKNOWN, List.of());
    }

    @Test
    @DisplayName("Same seed, same spread -> identical reading, every time")
    void sameSeedIsDeterministic() {
        var input = TarotDrawInput.withSeed(TarotSpread.PAST_PRESENT_FUTURE, 42L);

        var first = engine.calculate(input, context()).data();
        var second = engine.calculate(input, context()).data();

        assertThat(first.draws()).isEqualTo(second.draws());
        assertThat(first.seed()).isEqualTo(second.seed()).isEqualTo(42L);
    }

    @Test
    @DisplayName("Different seeds produce different draws (overwhelmingly likely)")
    void differentSeedsProduceDifferentDraws() {
        var a = engine.calculate(TarotDrawInput.withSeed(TarotSpread.PAST_PRESENT_FUTURE, 1L),
                context()).data();
        var b = engine.calculate(TarotDrawInput.withSeed(TarotSpread.PAST_PRESENT_FUTURE, 2L),
                context()).data();

        assertThat(a.draws()).isNotEqualTo(b.draws());
    }

    @Test
    @DisplayName("No seed supplied -> engine generates one via CSPRNG and reports it")
    void noSeedGeneratesOne() {
        var result = engine.calculate(TarotDrawInput.of(TarotSpread.CHOICE_A_B), context());

        assertThat(result.status()).isEqualTo(EngineStatus.SUCCESS);
        assertThat(result.data().seed()).isNotNull();

        // Reproducibility: replaying with the reported seed gives the same draw.
        var replay = engine.calculate(
                TarotDrawInput.withSeed(TarotSpread.CHOICE_A_B, result.data().seed()), context());
        assertThat(replay.data().draws()).isEqualTo(result.data().draws());
    }

    @Test
    @DisplayName("Two auto-generated draws use different seeds (CSPRNG is not degenerate)")
    void autoGeneratedSeedsDiffer() {
        var a = engine.calculate(TarotDrawInput.of(TarotSpread.CHOICE_A_B), context());
        var b = engine.calculate(TarotDrawInput.of(TarotSpread.CHOICE_A_B), context());

        assertThat(a.data().seed()).isNotEqualTo(b.data().seed());
    }

    @Test
    @DisplayName("A draw never repeats a card within the same spread")
    void noDuplicateCardsWithinOneDraw() {
        // Run across many seeds; Fisher-Yates over a fixed deck must never
        // produce a duplicate regardless of seed.
        for (long seed = 0; seed < 200; seed++) {
            var reading = engine.calculate(
                    TarotDrawInput.withSeed(TarotSpread.SITUATION_CHALLENGE_ADVICE, seed),
                    context()).data();

            Set<String> drawnIds = new HashSet<>();
            for (var draw : reading.draws()) {
                assertThat(drawnIds.add(draw.card().id()))
                        .as("seed %d drew %s twice", seed, draw.card().id())
                        .isTrue();
            }
        }
    }

    @Test
    @DisplayName("The number of cards drawn matches the spread's position count")
    void cardCountMatchesSpread() {
        for (TarotSpread spread : TarotSpread.values()) {
            var reading = engine.calculate(TarotDrawInput.withSeed(spread, 7L), context()).data();
            assertThat(reading.draws()).hasSize(spread.cardCount());
        }
    }

    @Test
    @DisplayName("Draw positions match the spread's declared position labels, in order")
    void positionsMatchSpreadDefinition() {
        var reading = engine.calculate(
                TarotDrawInput.withSeed(TarotSpread.PAST_PRESENT_FUTURE, 7L), context()).data();

        assertThat(reading.draws()).extracting(TarotCardDraw::position)
                .containsExactly("PAST", "PRESENT", "FUTURE");
    }

    @Test
    @DisplayName("UPRIGHT_ONLY policy never produces a reversed card")
    void uprightOnlyPolicyNeverReverses() {
        for (long seed = 0; seed < 50; seed++) {
            var input = new TarotDrawInput(TarotSpread.SITUATION_CHALLENGE_ADVICE, null, seed,
                    TarotOrientationPolicy.UPRIGHT_ONLY);
            var reading = engine.calculate(input, context()).data();

            assertThat(reading.draws())
                    .extracting(TarotCardDraw::orientation)
                    .containsOnly(TarotOrientation.UPRIGHT);
        }
    }

    @Test
    @DisplayName("RANDOM_INDEPENDENT_PER_CARD policy produces both orientations over many draws")
    void randomPolicyProducesBothOrientations() {
        Set<TarotOrientation> seen = new HashSet<>();
        for (long seed = 0; seed < 100; seed++) {
            var reading = engine.calculate(
                    TarotDrawInput.withSeed(TarotSpread.CHOICE_A_B, seed), context()).data();
            reading.draws().forEach(d -> seen.add(d.orientation()));
        }
        assertThat(seen).containsExactlyInAnyOrder(TarotOrientation.UPRIGHT, TarotOrientation.REVERSED);
    }

    @Test
    @DisplayName("The engine emits one signal per authored dimension field per card (R11, resolved)")
    void emitsSignalsFromAuthoredMeaning() {
        var result = engine.calculate(
                TarotDrawInput.withSeed(TarotSpread.PAST_PRESENT_FUTURE, 3L), context());

        assertThat(result.status()).isEqualTo(EngineStatus.SUCCESS);
        // 3 cards x up to 5 dimension fields each; every card is fully
        // authored (TarotDeckTest), so exactly 5 signals per card.
        assertThat(result.signals()).hasSize(15);
        assertThat(result.signals()).allSatisfy(signal -> {
            assertThat(signal.engine()).isEqualTo(TarotEngine.ENGINE_ID);
            assertThat(signal.critical()).isFalse();
            assertThat(signal.evidenceIds()).isNotEmpty();
        });
    }

    @Test
    @DisplayName("Every draw records one evidence entry per card, all in the same dimension bucket")
    void evidenceRecordsEveryCard() {
        var result = engine.calculate(
                TarotDrawInput.withSeed(TarotSpread.SITUATION_CHALLENGE_ADVICE, 5L), context());

        assertThat(result.evidence()).hasSize(3);
        assertThat(result.evidence()).allSatisfy(e -> {
            assertThat(e.dimension()).isEqualTo(Dimension.OTHER);
            assertThat(e.engine()).isEqualTo(TarotEngine.ENGINE_ID);
            assertThat(e.fact()).containsKeys("position", "cardId", "cardName", "orientation");
        });
    }

    @Test
    @DisplayName("Deck and shuffle versions travel with every reading (CLAUDE.md section 6)")
    void versionsAreReported() {
        var reading = engine.calculate(
                TarotDrawInput.withSeed(TarotSpread.CHOICE_A_B, 9L), context()).data();

        assertThat(reading.deckVersion()).isEqualTo(TarotDeck.DECK_VERSION);
        assertThat(reading.shuffleAlgorithmVersion()).isEqualTo(TarotEngine.SHUFFLE_ALGORITHM_VERSION);
    }

    @Test
    @DisplayName("Metadata declares a real school and source, matching the registry seed for TAROT_RWS")
    void metadataNamesSchoolAndSource() {
        var metadata = engine.metadata();

        assertThat(metadata.school()).contains("Rider-Waite-Smith");
        assertThat(metadata.source()).isNotBlank();
        assertThat(metadata.methodologyId()).isEqualTo("TAROT_RWS");
    }

    @Test
    @DisplayName("The engine does not require birth time, location, name or the Calendar")
    void hasNoCalendarDependency() {
        // The property that lets Phase 5 (Tarot) proceed while Calendar
        // research (R9, R10, R14a/b, R15-R17) is still open (ADR D2).
        var capability = engine.capability();

        assertThat(capability.requiresCalendar()).isFalse();
        assertThat(capability.requiresBirthTime()).isFalse();
        assertThat(capability.requiresLocation()).isFalse();
        assertThat(capability.requiresName()).isFalse();
    }

    @Test
    @DisplayName("Null input is rejected by validateInput, not by throwing from calculate")
    void nullInputIsValidatedNotThrown() {
        var validation = engine.validateInput(null);

        assertThat(validation.valid()).isFalse();
        assertThat(validation.errors()).isNotEmpty();
    }
}
