package io.destinyos.engines.iching;

import java.util.ArrayList;
import java.util.List;

/**
 * Hao tu (爻辭) content for hexagrams 49-64, King Wen order - see
 * {@link LineJudgment} for source and verification status (R25).
 */
final class LineJudgments4 {

    private LineJudgments4() {
    }

    static List<LineJudgment> entries() {
        List<LineJudgment> list = new ArrayList<>();

        // Que 49 (CÁCH)
        list.add(new LineJudgment(49, 1, "Sơ Cửu", "象 ⽈: 澤 中 有 ⽕, ⾰. 君 ⼦ 以 治 厤 明 時. Dịch âm. - Tượng viết: Trạch trung hữu hỏa, cách, quân tử dĩ trị lịch minh thì. Dịch nghĩa. - Lời Tượng nói rằng: Trong chằm có lửa, là quẻ Cách. Đấng quân tử coi đó mà trị lịch rõ mùa. GIẢI NGHĨA Truyện của Trình Di. - Nước lửa làm tắt lẫn nhau là quẻ Cách. Cách là thay đổi, đấng quân tử coi Tượng thay đổi, suy xét sự dời dịch của mặt trời mặt trăng ngôi sao, vì sao, để làm lịch số, tỏ rõ thứ tự của bốn mùa. Ôi, trong đạo biến đổi, việc rất lớn, lẽ rất rõ, dấu rất rệt, chẳng gì bằng bốn mùa, xem bốn mùa mà thay đổi theo đó, thì sẽ hợp thứ tự với trời đất vậy. Bản nghĩa của Chu Hy. - Bốn mùa là cuộc thay đổi lớn. LỜI KINH 初 九: 鞏 ⽤ 黄 ⽜ 之 ⾰", "Củng dụng hoàng ngưu chi cách.", "Hào Chín Đầu: Giàng bó dùng da trâu vàng.", 757, null));
        list.add(new LineJudgment(49, 2, "Lục Nhị", "象 ⽈: 鞏 ⽤ 黄 ⽜, 不 可 以 有 為 也. Dịch âm. - Tượng viết: Củng dụng hoàng ngưu, bất khả dĩ hữu vi dã. Dich nghĩa. - Lời Tượng nói rằng: Giàng bó dùng trâu vàng, chẳng khá có làm vậy. GIẢI NGHĨA Truyện của Trình Di. - Là hào Chín Đầu, thì, ngôi và tài đều không thể làmgì, cho nên, chỉ lấy đức giữa thuận tự giữ cho bền. LỜI KINH 六 ⼆: 已 ⽇ 乃 ⾰ 之, 征 吉, 無 咎.", "Dĩ nhật nãi cách chi, chinh cát, vô cữu.", "Hào Sáu Hai: Hết ngày bèn đổi đấy, đi tốt, không lỗi.", 759, null));
        list.add(new LineJudgment(49, 3, "Cửu Tam", "象 ⽈: 已 ⽇ ⾰ 之, ⾏ 有 嘉 也. Dịch âm. - Tượng viết: Dĩ nhật cách chi, hành hữu gia dã.Dịch nghĩa. - Lời Tượng nói rằng: Hết ngày đổi đấy, đi có tốt vậy. Truyện của Trình Di. - Hết ngày mà đổi, đi thì tốt mà không lỗi thế là đi có phúc tốt. LỜI KINH 九三: 征凶, 貞厲, ⾰⾔三就, 有孚.", "Chính hung trinh lệ, cách ngôn tam tựu, hữu phu.", "Hào Chín Ba: Đi hung, chính nguy, nói đổi ba nên có tin.", 760, null));
        list.add(new LineJudgment(49, 4, "Cửu Tứ", "象 ⽈: ⾰ ⾔ 三 就, 又 何 之 矣? Dịch âm. - Tượng viết: Cách ngôn tam tựu, hựu hà chi hỹ? Dịch nghĩa. - Lời Tượng nói rằng: Nói đổi ba lên, lại đi đâu vậy? GIẢI NGHĨA Truyện của Trình Di. - Xét về lời bàn của công chúng, đến ba lần, thì việc rất đáng rồi? Bản nghĩa của Chu Hy. - Ý nói đã đích xác rồi. LỜI KINH 九 四: 悔 亡, 有 孚, 改 命 吉.", "Hối vong, hữu phu, cải mệnh cát.", "Hào Chín Tư: Ăn năn mất, có tin đổi mệnh tốt.", 761, null));
        list.add(new LineJudgment(49, 5, "Cửu Ngũ", "象 ⽈: 改 命 之 吉, 信 志 以. Dịch âm. - Tượng viết: Cải mệnh chi cát, tín chí dã. Dịch nghĩa. – Lời Tượng nói rằng: Cái tốt của sự đổi mệnh, là tín chí vậy. GIẢI NGHĨA Truyện của Trình Di. - Đổi mệnh mà tốt, là vì trên dưới tin bụng của nhau. Lòng thành đã tộc bậc, thì kẻ trên, người dưới tin nhau. Đạo đổi lấy sự tin nhau của kẻ trên người dưới làm gốc. LỜI KINH 九 五: ⼤ ⼈ 虎 變, 未 占 有 孚.", "Đại nhân hổ biến, vị chiêm hữu phu.", "Hào Chín Năm: Người lớn cọp biến, chưa xem có tin.", 762, null));
        list.add(new LineJudgment(49, 6, "Thượng Lục", "象 ⽈: ⼤ ⼈ 虎 變, 其 ⽂ 炳 也. Dịch âm. - Tượng viết: Đại nhân hổ biến, kỳ văn bính dã. Dịch nghĩa. - Lời Tượng nói rằng: Người lớn cọp biến, thửa vẻ tỏ vậy. GIẢI NGHĨA Truyện của Trình Di. - Sự lý rõ ràng, như vằn cọp tỏ rệt, sáng sủa, thiên hạn còn không tin chăng? LỜI KINH象⽈: 君⼦豹變, 其⽂蔚也, ⼩⼈⾰⾯, 順以從君也.", "Quân tử báo biến, tiểu nhân cách diện, chính hung, cư trinh.", "Hào Sáu Trên: Đấng quân tử beo biến, kẻ tiểu nhân đổi mặt, đi hung, ở chính.", 764, null));

        // Que 50 (ĐỈNH)
        list.add(new LineJudgment(50, 1, "Sơ Lục", "初 六: ⿍ 顛 趾, 利 出 否, 得 妾 以 其 ⼦, 無 咎.", "Đỉnh điên chỉ, lợi xuất bĩ, đắc thiếp dĩ kỳ tử, vô cữu.", "Hào Sáu Đầu: Vạc chổng chân, lợi ra vật hư xấu, được, nàng hầu, lấy thửa con, không lỗi.GIẢI NGHĨA Truyện của Trình Di. - Hào Sáu ở dưới vạc, là Tượng cái chân, phía trên, nó ứng nhau vói hào Tư, chân mà ngảnh lên, là Tượng chổng ngược. Vạc đổ thì chân chổng, chân chổng thì đổ cái chứa của nó, đó không phải là cách thuận, nhưng cũng có khi nên chổng; nghĩa là giốc hết những vật hư xấu, để làm cho nó sạch sẽ và lấy cái mới mẻ, thì được. Cho nên, chổng chân lợi về vật hư xấu, “bĩ” nghĩa là “xấu”… “Được nàng hầu lây thửa con, không lỗi” là sao? Sáu là hào Âm mà thấp, cho nên là nàng hầu. “Được nàng hầu” nghĩa là được người. Nếu được nàng hầu tử tế, thì nó có thể giúp đỡ cho chủ, khiến chủ không lỗi. “Con” tức là chủ; “lấy thửa con” nghĩa là đưa chủ đến chỗ không lỗi. Bản nghĩa của Chu Hy. - Ở dưới quẻ Đỉnh là Tượng chân vạc, phía trên ứng với nhau với hào Chín Tư, thì là đổ rồi. Nhưng đương đầu quẻ, vạc chưa đựng gì, mà vật hư xấu, từ trước vẫn chứa ở đó, nhân nó đổ mà dốc hết ra, thì là lợi rồi. “Được nàng hầu, rồi được thửa con” cũng bởi cớ đó. Hào này Tượng như thế mà Chiêm thì không lỗi, vì nhân bị hỏng mà thành công, nhân hèn hạ mà nên sang.", 769, null));
        list.add(new LineJudgment(50, 2, "Cửu Nhị", "象 ⽈: ⿍ 顛 趾, 未 悖 也, 利 出 否, 以 從 貴 也. Dịch âm. - Tượng viết: Đỉnh điên chỉ, vị bội dã, lợi xuất bĩ, dĩ tòng quí dã. Dịch nghĩa. - Lời Tượng nói rằng: Vạc chổng chân, chưa trái vậy, lợi ra vật hư xấu, vì theo sang vậy. GIẢI NGHĨA Truyện của Trình Di. - Vạc đổ mà chân chổng lên, tức là trái đạo. Nhưng mà chưa hẳn là trái, vò nó có khi phải dốc hết vật hư xấu đi. Bỏ cái cũ màđựng cái mới, đổ cái hư xấu mà nhận cái tốt, là nghĩa “theo sang”, ứng với hào Tư tức là lên theo kẻ sang. LỜI KINH 九 ⼆: ⿍ 有 實, 我 仇 有 疾, 不 我 能 即, 吉.", "Đỉnh hữu thật, ngã cừu hữu tật, bất ngã năng tức, cát!", "Hào Chín Hai: Vạc có cái chứa, kẻ thù ta có tật, chẳng ta hay tới, tốt!", 771, null));
        list.add(new LineJudgment(50, 3, "Cửu Tam", "象 ⽈: ⿍ 有 實, 慎 所 之 也, 我 仇 有 疾, 終 無 尤 也. Dịch âm. - Tượng viết: Đỉnh hữu thật, thận sở chi dã, ngã cừu hữu tật, chung vô vưu dã.Dịch nghĩa. - Lời Tượng nói rằng: Vạc có đồ chứa, cẩn thận thửa đi vậy; kẻ thù ta có tật, trọn không lỗi vậy. GIẢI NGHĨA Truyện của Trình Di. - Hào Hai không chịu gần gũi với hào Đầu mà lên theo hào Sáu Năm là chính ứng của nó, thế là cẩn thận thửa đi. Kẻ thù là kẻ đối nhau với mình, chỉ về hào Đầu. Đã tự giữ bằng cách chính đính, thì nó không thể tới lại với ta. Vì vậy, sau chót không có sai lỗi. LỜI KINH 九 三:⿍ ⽿ ⾰, 其 ⾏ 塞, 雉 膏 不 ⾷, ⽅ ⾬, 虧 悔 終, 吉.", "Đỉnh nhĩ cách, kỳ hành tắc, trĩ cao bất thực, phương vũ, khuy hối chung, cát.", "Hào Chín Ba: Tai vạc đổi, thửa đi lấp, mỡ con chim trĩ không ăn, đang mưa, ăn năn về thiếu, chọn tốt.", 772, null));
        list.add(new LineJudgment(50, 4, "Cửu Tứ", "象 ⽈: ⿍ ⽿ ⾰, 失 其 義 也. Dịch âm. - Tượng viết: Đỉnh nhĩ cách, thất kỳ nghĩa dã. Dịch nghĩa. - Lời Tượng nói rằng: Tai vạc đổi, mất thửa nghĩa vậy. GIẢI NGHĨA Truyện của Trình Di. - Lúc đầu đổi khác với tai vạc, là mất cái nghĩa tìm nhau; không phải kẻ ứng với hào Năm, là mất cái đạo cầu hợp với nhau; không được giữa, là Tượng không phải cùng chí với nhau. Vì thế sự đi của nó bị lấp không thông. Nhưng trên sáng mà dưới có tài, sau cùng ắt hòa hợp, cho nên “sắp mưa mà tốt”. LỜI KINH 九四: ⿍折⾜, 覆公錬, 其形屋, 凶.", "Đỉnh chiết túc, phúc công tốc, kỳ hình ốc, hung!.", "Hào Chín Tư: Vạc gẫy chân, đổ đồ ăn của Ông, thửa tội giết kín[4] hung!", 774, null));
        list.add(new LineJudgment(50, 5, "Lục Ngũ", "象 ⽈: 覆 公 觫, 信 如 何 也. Dịch âm. - Tượng viết: Phúc cộng tốc, tín như hà dã. Dịch nghĩa. – Lời Tượng nói rằng: Đổ đồ của Ông, tin đường sao vậy. GIẢI NGHĨA Truyện của Trình Di. - Kẻ đại thần gánh lây cái trách nhiệm của thiên hạ,ắt phải làm nên cuộc thịnh trị cho thiên hạ, thì mới không lỡ sự nương tựa của đấng quân thượng, sự trông mong của kẻ hạ dân, và chí “đem thân gánh đạo” của mình, chẳng sai sự hẹn, là “tin”. Nếu không được thế, thì là bỏ mất chức việc, làm lỡ sự ủy thác của người trên, còn được là “tin” nữa chăng? Vì vậy mới nói: “tin dường sao vậy”. Bản nghĩa của Chu Hy. - Ý nói mất sự tin. LỜI KINH 六 五: ⿍ 黄 ⽿, ⾦ 鉉 利 貞.", "Đỉnh hoàng nhĩ, kim huyên, lợi trinh.", "Hào Sáu Năm: Vạc tai vàng, quai màu vàng, lợi về chính bền.", 775, null));
        list.add(new LineJudgment(50, 6, "Thượng Cửu", "象 ⽈: ⿍ 黄 ⽿, 中 以 為 實 也. Dịch âm. - Tượng viết: Đỉnh hoàng nhĩ, trung dĩ vi thật dã. Dịch nghĩa. - Lời Tượng nói rằng: Vạc tai vàng giữa lấy làm thật vậy. GIẢI NGHĨA Truyện của Trình Di. - Hào Sáu Năm lấy sự được giữa làm hay, đó là lấy “giữa” làm đức thật vậy. LỜI KINH 上 九: ⿍ ⽟ 鉉, ⼤ 吉, 無 不 利.", "Đỉnh ngọc huyên, đại cát, vô bất lợi.", "Hào Chín Trên: Đỉnh quai ngọc, cả tốt, không gì không lợi.", 776, null));

        // Que 51 (CHẤN)
        list.add(new LineJudgment(51, 1, "Sơ Cửu", "出 (xuất) là do chữ 爸(xưởng) lầm ra. LỜI KINH 象 ⽈: Tấn 雷, 震, 君 ⼦ 以 恐 懼 修 省. Dịch âm. - Tượng viết: Tấn lôi, Chấn, quân tử dĩ khủng cụ tu tĩnh. Dịch nghĩa. - Lời Tượng nói rằng: Liền sấm là quẻ Chấn, đấng quân tử coi đó mà sợ hãi sửa xét. GIẢI NGHĨA Truyện của Trình Di. - “Tấn” là lần kép, trên dưới đều là thể Chấn, cho nên liền sấm. Sấm động trùng điệp thì oai càng thịnh. Đấng quân tử soi sấm liền dữ dội đó mà sợ hãi, tự mình sửa sang, tự mình ngẫm xét. Đấng quân tử sự oai của trời thì sửa chính mình mình, nghĩa xét lỗi mình mà đổi nó đi. Chẳng những trong lúc sấm động, hễ gặp phải việc sợ hãi đều nên như thế. LỜI KINH 初九: 震來虢虢, 後笑⾔啞啞吉.", "Chấn lai khích khích, hậu tiếu ngôn ách ách cát.", "Hào Chín Đầu: Nhức lại ngơm ngớp, sau cười nói khanh khách, tốt.", 781, null));
        list.add(new LineJudgment(51, 2, "Lục Nhị", "彖⽈: 震亨, 震來虢虢, 恐致福也, 笑⾔啞啞, 後有則也. Dịch âm. - Tượng viết: Chấn lai khích khích, khủng trí phúc dã tiếu ngôn ách ách, hậu hữu tắc dã. Dịch nghĩa. – Lời Tượng nói rằng: Sợ lại ngom ngớp, vì sợ mà đến phúc vậy; cười nói khanh khách, sau có phép vậy. GIẢI NGHĨA Truyện của Trình Di. - Sự sợ đến nơi mà biết lo hãi, đoái ngắm thì sẽ không có vạ lo, thế là lo sợ mà đến được phúc. Nhân lo sợ mà tự mình tu tỉnh, chẳng dám trái với phép tắc, thế là bởi sự sợ mà sau có phép tắc, cho nên có thể giữ được yên lành mà cười nói khanh khách vậy. LỜI KINH 六 ⼆: 震 來 厲 憶, 喪 ⾙, 躋 于 九 陵, 勿 逐, 七 ⽇ 得.", "Chấn lai lệ ức, táng bối, tê vu cửu lăng, vật trục, thất nhật đắc.", "Hào Chín Hai: Nhức lại, nguy đồ (?) mất của, lên chân chín gò, chớ đuổi, bảy ngày được.GIẢI NGHĨA Truyện của Trinh Di. - Hào Sáu Hai ở giữa, được chỗ chính, là kẻ khéo ở cuộc sợ, mà cưỡi lên hào Chín Đầu là một hào cứng, hào Chín là chủ sự nhức, nó nhức động mà hăng lên, ai chống lại được? “Lệ” là mạnh là nguy, nó lại đã mạnh, thì ở vào chỗ nguy; “ức” là đồ đoán, “bối” là của mình có, “tê” là lên, “cửu lăng” là chỗ gò cao, “trục” là đi theo. Sự nhức kéo lại dữ dội, đoán chừng không thể đương nổi mà ắt phải mất cái của mình có, thì lên hẳn chỗ rất cao, để mà tránh nó. Chữ “Chín” là nói nhiều tầng là cao tột bậc, nhiều đến chín tầng, cũng như những chữ “chín trời”, “chín đất” vậy. “Chớ đuổi, bảy ngày được” là sao? Cái quý của hào Hai là đức trung chính, gặp khi nhức sợ kéo đến, tuy phải lượng thế nhún tránh, cũng nên giữ đức trung chính, chớ để mất đi. Đoán là ắt mất, cho nên tránh xa để tự giữ lấy, nó qua thì lại trở lại bình thường, ấy là không đuổi mà tự nhiên vẫn được. Đuổi là đi theo vật khác, đem mình đi theo vật khác, thế là mất sự tự chủ, cho nên răn rằng chớ đuổi. Ngôi quẻ có sáu, số bảy là lại bắt đầu, thì đã chót, việc đã thay đổi. Chẳng để mất cái sở thủ, tuy là một lúc không chống được nó kéo lại, nhưng thời qua, việc hết thời sẽ trở lại bình thường, cho nên nói rằng “bảy ngàỳ được”. Bản nghĩa của Chu Hy. - Hào Sáu Năm cưỡi lên hào Chín Đầu là một hào cứng, cho nên nhằm khi sự nhức kéo lại, tự thấy nguy dữ, chữ “ức” chưa rõ nghĩa là gì. Lại nên mất hết của cải mà phải lên trên chín gò.. Nhưng nó mềm thuận trung chính, đủ để tự giữ, cho nên không tìm mà tự được. Hào này lời chiêm đủ ở trong Tượng, có điều Tượng ở “chín gò” “bảy ngày”, chưa rõ ra sao.", 782, null));
        list.add(new LineJudgment(51, 3, "Lục Tam", "象 ⽈: 震 來 厲, 乘 剛 也. Dịch âm. - Tượng viết: Chấn lai lệ, thừa cương dã.Dịch nghĩa. - Lời Tượng nói rằng: Nhức lại, nguy, cưỡi cứng vậy. GIẢI NGHĨA Truyện của Trình Di. - Đương thì nhức, cưỡi lên kẻ cứng, cho nên nò mạnh mà mình nguy, nhức cứng kéo lại, còn chống sao nổi? LỜI KINH 六 tam: 震 蘇 蘇,震 ⾏ 無 眚.", "Chấn tô tô, chấn hành vô sảnh.", "Hào Sáu Ba: Nhức, thom thỏm, nhức đi, không tội.", 784, null));
        list.add(new LineJudgment(51, 4, "Lục Tứ", "象 ⽈: 震 蘇 蘇, 位 不 當 也. Dịch âm. - Tượng viết: Chấn tô tô, vị bất đáng dã. Dịch nghĩa. - Lời Tượng nói rằng: Nhức thom thỏm, ngôi chẳng đáng vậy.GIẢI NGHĨA Truyện của Trình Di. - Nó, phải sợ hãi tự mất thom thỏm vậy, là vì nó ở vào chỗ không được chính đáng. Chẳng giữa chẳng chính, thì yên sao được? LỜI KINH 六四: 震遂泥.", "Chấn toại nê.", "Hào Chín Tư: Nhức bèn đắm.", 785, null));
        list.add(new LineJudgment(51, 5, "Lục Ngũ", "象 ⽈: 震 遂泥, 未 光 也. Dịch âm. - Tượng viết: Chấn toại nê, vị quang dã. Dịch nghĩa. - Lời Tượng nói rằng: Nhức bèn đắm, chưa sáng vậy. GIẢI NGHĨATruyện của Trình Di. - Dương là vật cứng, nhức là nghĩa động, lấy chất cứng ở thì động, tự nó vốn đã có đạo sáng sủa hanh thông. Vì mất sự cương chính mà bị hãm giữa hai hào Âm đến nỗi “bèn đắm”, há có thể sáng? LỜI KINH 六 五: 震 往 來 厲, 億 無 喪 有.", "Chấn vãng lai lệ, ức vô táng hữu.", "Hào Sáu Năm: Nhức đi lại nguy, đồ (?) không mất cái có.", 786, null));
        list.add(new LineJudgment(51, 6, "Thượng Lục", "象 ⽈: 震 來 厲, 危 ⾏ 也, 其 事 在 中, ⼤ 無 喪 也. Dịch âm. - Tượng viết: Chấn lai lệ, nguy hành dã; kỳ sự tại trung, đại vô táng dã.Dịch nghĩa. - Lời Tượng nói rằng: Nhức lại nguy, đi hiểm nghèo vậy, thửa việc ở giữa, lớn không mất vậy. GIẢI NGHĨA Truyện của Trình Di. - Đi lại đều nguy, thế là đi thì có nguy. Động đều có nguy, chi cốt không mất thửa việc mà thôi. “Thửa việc” chỉ về đức giữa; không mất đức giữa, thì tự giữ được. “Lớn không mất” nghĩa là lấy sự không mất làm lớn vậy. LỜI KINH 上 六: 震 索 索, 視 矍 矍, 征 凶, 震 不 于 其 躬, 于 其 鄰, 無 咎, 婚 媾 有 ⾔.", "Chấn tắc tác, thị quắc quắc, chinh hung chấn bất vu kỳ cung, vu kỳ lân, vồ cữu, hôn cấu hữu ngôn.", "Hào Sáu Trên: Nhức xơ xác, trông ngơ ngác, đi thì hung; nhức chẳng chưng thửa mình, chưng thửa láng giềng, không lỗi, dâu gia có nói.", 787, null));

        // Que 52 (CẤN)
        list.add(new LineJudgment(52, 1, "Sơ Lục", "其 ⽌ cấn kỳ chỉ”, chữ ⽌ (chỉ) nên theo lời quẻ[4] đổi làm chữ (bối). LỜI KINH 象 ⽈: 兼 ⼭ ⾉, 君 ⼦ 以 思 不 出 其 位. Dịch âm. - Tượng viết: Kiêm sơn Cấn, quân tử dĩ tư bất xuất kỳ vị. Dịch nghĩa. - Lời Tượng nói rằng: Gồm núi là quẻ Cấn. Đấng quân tử coi đómà nghĩ chẳng việc thửa ngôi. GIẢI NGHĨA Truyện của Trình Di. - Trên dưới đều là núi, cho nên nói là gồm núi. Cái này nhập với cái kia là “gồm” tức là trùng điệp vậy. Trùng điệp là tượng của Cấn. Đấng quân tử coi tượng Cấn đậu mà nghĩ chỗ đậu không vượt ra ngoài ngôi mình. Ngôi tức là phận mình ở . Muôn việc đều có nơi chốn, hễ đúng nơi chốn thì là đậu yên. Hoặc thái quá, hoặc bất cập, đều là vượt ra ngoài ngôi. LỜI KINH 初 六: ⾉ 其 趾, 無 咎, 利 永 貞.", "Cấn kỳ chỉ, vô cữu, lợi vĩnh trinh.", "Hào Sáu Đầu: Đậu thửa ngón chân, không lỗi, lợi về dài lâu chính bền.", 794, null));
        list.add(new LineJudgment(52, 2, "Lục Nhị", "象 ⽈: ⾉ 其 趾, 未 失 正 也. Dịch âm. - Tượng viết: Cấn kỳ chỉ, vị thất chính dã. Dịch nghĩa. - Lời Tượng nói rằng: Đậu thửa ngón chân, chưa mất chính vậy. GIẢI NGHĨA Truyện của Trình Di. - Đáng đậu mà đi, không phải là chính. Đậu từ lúc đầu, cho nên đến mất sự chính. Đậu từ lúc đầu thì dễ mà chưa đến lỗi vậy. LỜI KINH 六 ⼆: ⾉ 其 腓, 不 拯 其 隨, 其 ⼼ 不 快.", "Cấn kỳ phì, bất chủng kỳ tùy, kỳ tâm bất khoái.", "Hào Sáu Hai: Đậu thửa bụng chân, chẳng cứu thửa theo, thửa lòng chẳng sướng.", 795, null));
        list.add(new LineJudgment(52, 3, "Cửu Tam", "象 ⽈: 不 拯 其 隨, 未 退 聴 也. Dịch âm. - Tượng viết: Bất chửng kỳ tùy, vị thoái thính dã. Dịch nghĩa. - Lời Tượng nói rằng: Chẳng cứu thửa theo, chứa lui nghe vậy. GIẢI NGHĨA Truyện của Trình Di. - Sở dĩ chẳng cứu nó mà lại dạ theo, là vì kẻ ở trên chưa xuống mà theo. Lui nghe nghĩa là xuống mà theo vậy. Bản nghĩa của Chu Hy. - Hào Ba đậu ở trên, cũng chẳng chịu xuống mà theo hào Hai. LỜI KINH 九 三: ⾉ 其 限, 列 其 夤, 厲 薰 ⼼.", "Cấn kỳ hạn, liệt kỳ di, lệ huân tâm.", "Hào Chín Ba: Đậu thửa hạn, xé thửa thăn, nguy hun lòng.", 796, null));
        list.add(new LineJudgment(52, 4, "Lục Tứ", "象 ⽈: ⾉ 其 限, 危 薰 ⼼ 也. Dịch âm. - Tượng viết: Cấn kỳ hạn, nguy huân tâm dã. Dịch nghĩa. - Lời Tượng nói rằng: Đậu thửa hạn, nguy hun lòng vậy. GIẢI NGHĨA Truyện của Trình Di. - Ý nói nó cứ cố đậu không thể tiến lui, cái lo về sự hiểm nghèo thường thường hun đốt trong lòng. LỜI KINH 六 四:⾉ 其 ⾝, 無 咎.", "Cấn kỳ thân, vô cữu.", "Hào Sáu Tư: Đậu thửa mình, không lỗi.GIẢI NGHĨA Truyện của Trình Di. - Hào Tư là ngôi đại thần, đậu chỗ đáng đậu trong thiên hạ. Vì nó Âm mềm mà không gặp vua Dương cứng, cho nên không thể làm đậu người khác mà chỉ tự đậu thân mình, thì được không lỗi. Bản nghĩa của Chu Hy. - Lây chất Âm ngôi Âm, lúc đáng đậu mà đậu, cho nên là Tượng “đậu thửa mình” mà Chiêm thì là không lỗi.", 797, null));
        list.add(new LineJudgment(52, 5, "Lục Ngũ", "象 ⽈: ⾉ 其 ⾝, ⽌ 諸 躬 也. Dịch âm. - Tượng viết: Cấn kỳ thân, chỉ chư cung dã. Dịch nghĩa. - Lời Tượng nói rằng: Đậu thửa mình, là đậu chưng mình vậy. GIẢI NGHĨA Truyện của Trình Di. - Không thể làm cho thiên hạ cùng đậu, mà chỉ đậu được thân mình, há đủ xứng ngôi đại thần? LỜI KINH 六五:⾉其輔, ⾔有序, 悔亡.", "Cấn kỳ phụ ngôn hữu tự, hối vong.", "Hào Sáu Năm: Đậu thửa mép, nói có thứ tự, ăn năn mất.", 798, null));
        list.add(new LineJudgment(52, 6, "Thượng Cửu", "象⽈: ⾉其輔, 以中正也. Dịch âm.- Tượng viết: Cấn kỳ phụ, dĩ trung chính dã. Dịch nghĩa. - Lời Tượng nói rằng: Đậu thửa mép, lấy giữa chính vậy. GIẢI NGHĨA Truyện của Trình Di. - Cái hay của hào Nảm là đức giữa. Đậu thửa mép là đậu ở giữa, ý nói lấy đức giữa làm chính vậy. Bản nghĩa của Chu Hy. - Chữ 正 (chính) là chữ thừa, kháp vần[5] đủ thấy. LỜI KINH 上九: 敦⾉, 吉.", "Đôn Cấn, cát.", "Hào Chín Trên - Dầy đậu, tốt.", 799, null));

        // Que 53 (TIỆM)
        list.add(new LineJudgment(53, 1, "Sơ Lục", "漸君,⼦以居賢德,thiện俗. Dịch âm.- Tượng viết: Sơn thượng hữu mộc, Tiệm, quân tử dĩ cư hiền đức. Dịch nghĩa. - Lời Tượng nói rằng: Trên núi có cây là quẻ Tiệm, đấng quân tử coi đó mà chứa đức hiền, làm hay thói tục. GIẢI NGHĨA Truyện của Trình Di. - Trên núi có cây, sự cao của nó có chỗ nhân theo, đó là nghĩa dần dần. Đấng quân tử coi Tượng “dần dần” mà chứa đức hiền thiện, làm tốt cho phong tục. Người ta tiến về hiền đức ắt, phải tập dần mới được, không thể vượt qua chừng độ mà tới ngay. Ở mình còn thế, thì dạy bảo người, nếu không dùng cách dần dần sao được? Dời thói dổi lễ, không thể là việc một sớm một tối có thể làm xong, cho nên làm hay phong tục cũng phải dần dần.LỜI KINH 初六: 鴻漸于⼲,⼩⼦厲有⾔,無咎.", "Hồng tiệm vu can, tiểu tử lệ, hữu ngôn, vô cữu.", "Hào Sáu Đầu: Con sếu tiến chưng bến, trẻ nhỏ nguy, có nói, không lỗi.", 806, null));
        list.add(new LineJudgment(53, 2, "Lục Nhị", "六二：鴻漸于磐，飲食衎衎。", "Lục Nhị: Hồng tiệm vu bàn, ẩm thực hãn hãn.", "Hào Sáu Hai: Con sếu tiến chưng tảng đá, ăn uống hơn hớn.", 802, "PATCH THỦ CÔNG (2026-08-31): nhãn hào (\"Lục Nhị:\") HOÀN TOÀN VẮNG MẶT trong bản trích xuất tại đúng vị trí này (khác các mục khác - đây không phải gõ nhầm mà là nội dung nhãn bị thiếu). Nội dung dịch âm/dịch nghĩa còn nguyên, nhưng nhãn \"Lục Nhị\" và Hán tự \"六二\" do suy luận vị trí (hào thứ 2, sau Sơ Lục, trước Cửu Tam), KHÔNG trực tiếp đọc được từ nguồn - ĐỘ TIN CẬY THẤP HƠN mọi mục khác, cần đối chiếu ảnh trang gốc hoặc zh.wikisource trước khi dùng."));
        list.add(new LineJudgment(53, 3, "Cửu Tam", "象⽈: 飲⾷衍衍, 不素飽也.Dịch âm.- Tượng viết: Ẩm thực hãn hãn, bất tố bão dã. Dịch nghĩa. - Lời tượng nói rằng: Uống ăn hơn hớn, chẳng nó không vậy. GIẢI NGHĨA Truyện của Trình Di. - Gọi là uống ăn hơn hớn, nghĩa là đắc chí hòa vui, không thể bảo là chỉ ăn no không mà thôi. Bản nghĩa của Chu Hy. - Chữ “no không” cũng như chữ “ăn không” trong Kinh Thi, nghĩa là được sự “no” ấy có đạo, không phải chỉ ăn cho no mà ở cho yên.[3] LỜI KINH 九三: 鴻漸于陸, 夫征不復, 婦孕不育, 凶, 利禦寇.", "Hồng tiệm vu lục, phu chinh bất phục, phụ dựng bất dục, hung, lợi ngữ khấu.", "Hào Chín Ba: Con sếu tiến chưng đất liền, chồng đi chẳng lại, vợ chửa chẳng nuôi, hung, lợi về chống giặc.", 808, null));
        list.add(new LineJudgment(53, 4, "Lục Tứ", "象⽈:夫征不復,離群sũ也, 婦孕不育, 失其道也,利⽤禦寇,順相保也. Dịch âm.- Tượng viết: Phu chinh bất phục, ly quần sũ dã; phụ dực bất dục, thất kỳ đạo dã; lợi dụng ngữ khấu, thuận tượng bảo dã. Dịch nghĩa. - Lời tượng nói rằng: Chồng đi chẳng lại, lìa đàn loài vậy; vợ chửa chẳng nuôi, lỗi thửa đạo vậy; lời dùng chống giặc, thuận cùng giữ vậy. GIẢI NGHĨA Truyện của Trình Di. - Chồng đi chẳng lại, thì lỗi chính đạo của sự tiến, theo lòng ham muốn mất chính đạo, lìa phản đàn loài, là đáng xấu vậy. Vợ chửa không dùng chính đạo, cho nên không thể nuôi được. Chỉ lợi về sự chống giặc, tức là lấy sự hòa thuận giữ lẫn cho nhau. LỜI KINH 六四: 鴻漸于⽊, 或得其桷, ⽆咎.", "Hồng tiệm vu mộc, hoắc đắc kỳ giốc, vô cữu.", "Hào Sáu Tư: Con sếu tiến chưng cây, hoặc được thửa cành ngang, không lỗi.", 809, null));
        list.add(new LineJudgment(53, 5, "Cửu Ngũ", "象⽈: 或得其桷, 順以巽也. Dịch âm.- Tượng viết: Hoặc đắc kỳ giốc, thuận dĩ tốn dã. Dịch nghĩa. - Lời Tượng nói rằng: Hoặc được thửa cành ngang, thuận và nhún vậy. GIẢI NGHĨA Truyện của Trình Di. - Cành ngang là chỗ bình yên, cái đạo cầu yên, chỉ thuận và nhún. Thuận chính mà nhún như hào Tư, tức là được cành ngang vậy. LỜI KINH 九五: 鴻漸于陸, 婦三歲不孕, 終莫之勝, 吉.", "Hồng tiệm vu lăng, phụ tam tuế bất dựng, chung mạc chi thắng, cát.", "Hào Chín Năm: Con sếu tiến chưng gò, vợ ba năm chẳng chửa, trọn chẳng gì thắng, tốt.GIẢI NGHĨA Truyện của Trình Di. - Gò là đống cao, con sếu vẫn đậu, là chỗ rất cao, giống như ngôi vua. Hào Năm với Hào Hai là chính ứng, cái đức trung chính giống nhau, thế mà bị cách hào Ba hào Tư, hào Ba liền với hào Hai, hào Tư liến với hào Năm, đều là kẻ ngăn sự giao tiếp của nó. Nó chưa hợp nhau được ngay, cho nên ba năm không chửa. Nhưng đạo trung chính có lý ắt phải hanh thông, há làm cách hại được nó? Cho nên rát lại không gì thắng nó. Có điều sự hợp của nó cũng phải dần dần, vì vậy, sau chót được tốt. Bản nghĩa của Chu Hy. - Hào Chín Năm ở ngôi tôn, hào Sáu Hai là chính ứng với hào Năm, mà bị hào Ba vào Tư ngăn cách; nhưng rút lại vẫn không cướp được chính đạo của nó, cho nên Tượng nó như thế, mà kẻ xem như thế thì tốt.", 810, null));
        list.add(new LineJudgment(53, 6, "Thượng Cửu", "象⽈: 終莫之勝, 吉, 得所願也. Dịch âm.- Tượng viết: Chung mạc chi thắng, cát, đắc sở nguyện dã. Dịch nghĩa. - Lời Tượng nói rằng: Chọn thẳng gì được, tốt, được thửa muốn vậy. GIẢI NGHĨA Truyện của Trình Di. - Vua tôi lấy sự trung chính giao nhau, đạo đó đáng được thực hiện, tuy là có kẻ ngăn cách ở giữa, há thắng được chăng? Lâu rồi ắt được cái sở nguyện của nó, thế là việc tốt trong đạo dần dần. LỜI KINH 上九: 鴻漸于陸, 其⽻可⽤為儀, 吉.", "Hồng tiệm vu quỳ, kỳ vũ khả dụng vi nghi, cát.", "Hào Chín Trên: con sếu tiến chưng đường mây, lộng nó khá dùng làm miều cờ, tốt.", 812, null));

        // Que 54 (QUI MUỘI)
        list.add(new LineJudgment(54, 1, "Sơ Cửu", "初九: 歸妹以娣, 跛能履, 征吉.", "Quy muội dĩ đệ, bí năng lý, chinh cát.", "Hào Chín Đầu: Em gái về nhà chồng bằng vợ lẽ, quẻ biết xẻo, đi tốt.", 817, null));
        list.add(new LineJudgment(54, 2, "Cửu Nhị", "象⽈:歸妺以娣,以恒也,bí能履吉,相承也. Dịch âm.- Tượng viết: Qui muội dĩ đệ, dĩ hằng dã; bí năng lý, cát, tương thừa dã. Dịch nghĩa. - Lời Tượng nói rằng: Em gái về nhà chồng, bằng vợ lẽ, vì thường thường vậy; quẻ biết xéo, tốt, vâng nhau vậy. GIẢI NGHĨA Truyện của Trình Di. - Nghĩa quẻ Qui muội lấy sự đẹp lòng mà động, không phải đạo vợ chồng có thể thường thường. Hào Chín là kẻ Dương cương có đức hiền trinh, tuy là vợ lẽ hèn mọn, lại có thể giữ được thường thường, dù nó ở dưới không thể làm gì, như kẻ què biết xéo, nhưng mà đi tốt, là ví nó biết vậy giúp nhau; biết vâng giúp chồng, tức là sự tốt của vợ lẽ. LỜI KINH 九⼆: 眇能視,利幽⼈之貞.", "Diểu năng thị, lợi u nhân chi trinh.", "Hào Chín Hai: Chột biết trông, lợi về sự chính bền của bậc u nhân.", 818, null));
        list.add(new LineJudgment(54, 3, "Lục Tam", "六三: 歸妺以須,反歸以娣.", "Qui muội dĩ tu, phản qui dĩ đệ.", "Hào Sáu Ba: Em gái về bằng sự đợi, lại về bằng vợ lẽ.", 820, null));
        list.add(new LineJudgment(54, 4, "Cửu Tứ", "象⽈: 歸妺以須,未當也. Dịch âm.- Tượng viết: Qui muội dĩ tu, vị đáng dã. Dịch nghĩa. - Lời Tượng nói rằng: Em gái về nhà chồng lấy đợi chưa đáng vậy. GIẢI NGHĨA Truyện của Trình Di. - Chưa đáng nghĩa là chỗ ở của nó, đức nó, cách cầu lấy chồng của nó đều không đáng, không ai lấy nó, cho nên phải đợi. LỜI KINH 九四: 歸妺愆期,遲歸有時.", "Qui muội khiên kỳ, trì qui hữu thì.", "Hào Chín Tư: Em gái về nhà chồng lỗi hẹn, chậm về có thời. Truyện của Trình Di. - Hào Chín lấy chất Dương ở ngôi Tư, ngôi Tư ở thể trên là chỗ cao, đức Dương cứng ở con gái là đức chính, tức là người hiền minh, không có chính ứng, tức là chưa được chỗ về, quá thời chưa về nhà chồng, cho nên nói là lỗi hẹn. Con gái ở chỗ sang cao, có đức hiền minh, lòng người ai cũng muố lấy, cho nên sự lỗi hẹn chính là “có thời”, nghĩa là tự nó còn có chờ đợi, không hải là khong dắt chồng, là đợi được kẻ tốt đôi mới đi.Bản nghĩa của Chu Hy. - Hào Chín Tư lấy chất Dương ở thể trên mà không có chính ứng, tức là gái hiền không chịu khinh suất theo người. Mà cối lỗi hẹn để đợi. Chính là trái lại với hào Sáu Ba.", 821, null));
        list.add(new LineJudgment(54, 5, "Lục Ngũ", "象⽈: 遲歸之志,有待⽽⾏也. Dịch âm.- Tượng viết: Khiên kỳ chi chí, hữu đãi nhi hành dã. Dịch nghĩa. - Lời Tượng nói rằng: Cái chí lỗi hẹn, có đợi mà đi vậy. GIẢI NGHĨA Truyện của Trình Di. - Sở dĩ lỗi hẹn là do ở mình không do ở kẻ kia. Con gái hiền là người mà người ta muốn lấy, sở dĩ lỗi hẹn, là tại chí nó muốn có chờ đợi, chờ đợi được người tốt đôi mới đi. LỜI KINH 六五: 帝⼄歸妹, 其君之袂, 不如其娣之袂良, ⽉幾望, 吉.", "Đế Ất qui muội, kỳ quân chi quệ, bất như kỳ đệ chi quệ lương, nguyệt cơ vọng, cát!", "Hào Sáu Năm: Vua Đế Ất gả chồng em gái, vạt áo của vua nó không đẹp bằng vạt áo của vợ lẽ nó. Mặt trăng hầu tuần vọng, tốt!", 822, null));
        list.add(new LineJudgment(54, 6, "Thượng Lục", "上六: ⼥承筐,無實,⼠刲⽺無⾎,無攸利.", "Nữ thừa khuông, vô thật: sĩ khuê dương vô huyết; vô du lợi.", "Hào Sáu Trên: Con gái vâng giỏ, không đồ đựng; con trai giết dê, không máu; không thửa lợi.", 824, null));

        // Que 55 (PHONG)
        list.add(new LineJudgment(55, 1, "Sơ Cửu", "初九: 遇其配主, 雖旬無咎, 往有尚.", "Ngọ kỳ phối chủ, tuy tuần vô cữu, vãng hữu thượng.", "Hào Chín Đầu: Gặp thử chủ sánh dẫn đều không lỗi, đi có chuộng.", 829, null));
        list.add(new LineJudgment(55, 2, "Lục Nhị", "六⼆:豐其蔀,⽇中⾒⽃,往得疑疾,有孚發若,吉.", "Phong kỳ bộ, nhật trung kiến Đẩu, vãng đắc nghi tật, hữu phu phát nhược, cát.", "Hào Sáu Hai: Thịnh thửa trướng mặt trời giữa thấy sao Đẩu, đi được ngờ ghét, có tin dường mở ra vậy tốt.", 830, null));
        list.add(new LineJudgment(55, 3, "Cửu Tam", "象⽈:有孚發若,信以發志也. Dịch âm.- Tượng viết: Hữu phu phát nhược, tín dĩ phát chí dã. Dịch nghĩa. - Lời Tượng nói rằng: Có tin dường mở ra vậy, là dùng sự tin để mở chí vậy. GIẢI NGHĨA Truyện của Trình Di. - “Có tin dường mở ra vậy” nghĩa là dùng phu tín cám phát tâm chí của người trên vậy. LỜI KINH 九三: 豐其沛, ⽇中⾒沫, 折其右肱, 無咎.", "Phong kỳ bái, nhật trung kiến mạt[5], triết kỳ hữu quãng, vô cữu.", "Hào Chín Ba: Thịnh thửa màn, mặt trời giữa thấy sao Mạt, gãy thửa cánh tay phải, không lỗi.", 832, null));
        list.add(new LineJudgment(55, 4, "Cửu Tứ", "沫 (mạt) là nhỏ. Hào Ba ở chỗ sáng cực mà ứng với hào Sáu Trên, tuy không thể dùng, mà không phải lỗi tại nó, cho nên Tượng, Chiêm của nó như thế. LỜI KINH 象⽈:豐其沛,不可⼤事也; 折其有肱,終不可⽤也. Dịch âm.- Tượng viết: Phong kỳ bái, bất khả đại sự dã: triết kỳ hữu quang, chung bất khả dụng dã. Dịch nghĩa. - Lời Tượng nói rằng: Thịnh thửa màn, chẳng khá làm việc lớn vậy; gãy thửa cánh tay phải, trọn chẳng khá dùng vậy. GIẢI NGHĨATruyện của Trình Di. - Hào Ba ứng với hào Trên, kẻ trên ứng với mà không có ngôi. Âm mềm không có thế lực, lại ở chỗ đã chót còn cùng làm nên việc lớn được chăng? Đã không thể nhờ, như gãy cánh tay phải, thì rút cục không thể dùng được. LỜI KINH 九四: 豐其蔀, ⽇中⾒⽃, 遇其夷主, 吉.", "Phong kỳ bộ, nhật trung kiến Đẩu, ngộ kỳ di chủ, cát.", "Hào Chín Tư: Thịnh thửa trướng, mặt trời giữa thấy sao Đẩu, gặp thửa chủ ngang tốt.", 834, null));
        list.add(new LineJudgment(55, 5, "Lục Ngũ", "中⾒⽃, 幽不明也. Dịch âm.- Nhật trung kiến Đẩu, u bất minh dã. Dịch nghĩa. - Mặt trời giữa thấy sao Đẩu, tối chẳng sáng vậy. GIẢI NGHĨA Truyện của Trình Di. - Ý nói tối tăm không thể sáng láng, là vì vua Tượng Âm mà tối thì không trung chính. LỜI KINH 遇其夷主, 吉⾏也 Dịch âm.- Ngộ kỳ di chủ, cát hành dã. Dịch nghĩa. - Gặp thửa chủ ngang, đi tốt vậy. GIẢI NGHĨA Truyện của Trình Di. - Dương cứng gặp nhau là sự đi tốt lành. Tới xuống với hào Đầu, cho nên nói là “đi”, nghĩa là trở xuống mà tìm thì tốt.LỜI KINH 六五: 來章有慶譽, 吉.", "Lai chương hữu khánh dự, cát.", "Hào Sáu Năm: Lại đẹp có phúc khen, tốt.", 836, null));
        list.add(new LineJudgment(55, 6, "Thượng Lục", "象⽈: 六五之吉,有慶也. Dịch âm.- Tượng viết: Lục Ngũ chi cát, hữu khánh dã. Dịch nghĩa. - Lời Tượng nói rằng: Cái tốt của hào Sáu Năm, có phúc vậy. GIẢI NGHĨATruyện của Trình Di. - Gọi là tốt, vì nó phúc khánh tới thiên hạ. Kẻ làm vua tuy là mềm tối, nếu biết dùng người hiền tài, thì có thể làm phúc cho thiên hạ, chỉ lo không thể như thế mà thôi. LỜI KINH 上六: 豐其屋,蔀其家,闚其⼾, 闃其無⼈,三歲不靚,凶.", "Phong kỳ ốc, bộ kỳ gia, khuy kỳ hộ, khuých kỳ vô nhân, tam tuế bất thục, hung.", "Hào Sáu Trên: Thịnh thửa mái, che thửa nhà nhòm thửa cửa, hiu quạnh thửa không người, ba năm chẳng thấy, hung.", 837, null));

        // Que 56 (LỮ)
        list.add(new LineJudgment(56, 1, "Sơ Lục", "初六: 旅瑣瑣, 斯其所取災.", "Lữ tỏa tỏa, tư kỳ sơ thủ tai.", "Hào Sáu Đầu: Hành lữ nhỏ mọn, ấy là cái lấy vạ.", 842, null));
        list.add(new LineJudgment(56, 2, "Lục Nhị", "象⽈: 旅瑣瑣, 志窮災也. Dịch âm.- Tượng viết: Lữ tỏa tỏa, chí cùng tai dã. Dịch nghĩa. - Lời Tượng nói rằng: Hành lữ nhỏ mọn, chí cùng hại vậy. GIẢI NGHĨA Truyện của Trình Di. - Chí ý cùng gặt càng tự rước lấy tai vạ. Chữ “tai” và chữ “sảnh” đối nhau mà nói thì có phân biệt, nói riêng một mình, chỉ là “vạ lo” mà thôi. LỜI KINH 六⼆: 旅即次, 懷其資, 得童僕貞.", "Lữ tức thứ, hoài kỳ tư, đắc đồng bộc trinh.", "Hào Sáu Hai: Hành lữ tới chỗ trọ, ôm thửa của, được thằngnhỏ, đầy tớ chính bền.", 843, null));
        list.add(new LineJudgment(56, 3, "Cửu Tam", "象⽈: 得童僕貞, 終無咎也. Dịch âm.- Tượng viết: Đắc đồng bộc trinh, chung vô cữu dã. Dịch nghĩa. - Lời Tượng nói rằng: Được thằng nhỏ đầy tớ chính bền, chọn không lỗi vậy. GIẢI NGHĨATruyện của Trình Di. - Cái người ky lữ, nhờ vào thằng nhỏ đầy tớ, đã được thằng nhỏ, đầy tó trung trinh, thì không oán hối gì nữa. LỜI KINH 九三: 旅焚其次, 喪其童僕, 貞厲.", "Lữ phần kỳ thứ, táng kỳ đồng bộc, trinh lệ.", "Hào Chín Ba: Hành lữ cháy thửa nhà trợ, mất thửa thằng nhỏ, đầy tớ, chính bền nguy.", 845, null));
        list.add(new LineJudgment(56, 4, "Cửu Tứ", "象⽈: 旅焚其次, 亦已傷矣, 以旅與下, 其義喪也. Dịch âm.- Tượng viết: Lữ phần kỳ thứ, diệc dĩ thương kỹ, dĩ lữ dữ hạ, kỳ nghĩa táng dã.Dịch nghĩa. - Lời Tượng nói rằng: Hành lữ cháy thửa nơi trọ cũng đã hại vậy; lấy thì hành lữ cùng với kẻ dưới, thửa nghĩa mất vậy. GIẢI NGHĨA Truyện của Trình Di. - Kẻ hành lữ cháy mất nhà trọ, cũng đã khốn hại rồi; lấy thời hành lữ mà cách cùng với kẻ dưới như thế, nghĩa nên mất vậy. Ở thời hành lữ, mà lấy sự quá cứng tự cao đối đãi kẻ dưới, ắt phải mất sự trung trinh của họ, nghĩa là mất lòng họ vậy. Trong thời hành lữ mà mất lòng thằng nhỏ đầy tớ, là đáng lo lắm. LỜI KINH 九四: 旅于處, 淂其資斧, 我⼼不快.", "Lữ vu xử, đắc kỳ tư phủ, ngã tâm bất khoái.", "Hào Chín Tư: Hành lữ chưng ở, được thửa của búa, lòng ta chẳng sướng.", 846, null));
        list.add(new LineJudgment(56, 5, "Lục Ngũ", "象⽈: 旅于處, 未得位也; 得其資斧, ⼼未快也. Dịch âm.- Tượng viết: Lữ vu xử, vị đắc vị đã, đắc kỳ tư phủ, tâm vị khoái dã.Dịch nghĩa. - Lời Tượng nói rằng: Hành lữ chưng ở, chưa được ngôi vậy, được thửa của búa, lòng chưa sướng vậy. GIẢI NGHĨA Truyện của Trình Di. - Hào Tư lấy sự gần vua làm đáng ngôi, ở quẻ Lữ, hào Năm không dùng nghĩa vua, cho nên hào Tư là chưa đáng ngôi. Có người nói rằng: Như thế thì hào Chín ở ngôi Tư, không được chính đính là có lỗi rồi. Đáp răng: Lấy chất cứng ở ngôi mềm là sự “đáng nên” của kẻ hành lữ. Hào Chín là tài cứng sáng, muốn được thời mà thực hành chí mình, cho nên dù được của búa, với cuộc hành lữ là hay mà tâm chí nó chưa sướng. LỜI KINH 六五: 射雉, ⼀⽮亡, 終以譽命.", "Xã trĩ, nhất thỉ vong, chung dĩ dự mệnh.", "Hào Sáu Năm: Bắn chim trĩ, một phát tên mất, chọn lấy khen mệnh.", 848, null));
        list.add(new LineJudgment(56, 6, "Thượng Cửu", "象⽈: 終以譽命, 上逮也. Dịch âm.- Tượng viết: Chung dĩ dự mệnh, thượng đãi dã. Dịch nghĩa. - Lời Tượng nói rằng: Trọn lấy khen mệnh trên kịp vậy. GIẢI NGHĨA Truyện của Trình Di. - Có đức văn vẻ sáng sủa, thì kẻ trên người dưới cùng với, “Kịp” tức là cùng, biết thuận vâng người trên mà người trên cùng với, tức là “được người trên kịp”. Ở ngôi trên mà được lòng kẻ dưới, tức là “được kẻ dưới kịp”. Ở thời hành lữ mà được trên dưới cùng với, vì vậy mới đem được khen mệnh đến. Bản nghĩa của Chu Hy. - “Kịp” là tiếng khen mệnh tốt của nó đến tai người trên. LỜI KINH 上九: ⿃焚其巢, 旅⼈先笑, 後號眺, 喪⽜于易, 凶.", "Điểu phần kỳ sào, lữ nhân tiên tiếu, hậu hào diêu, táng ngưu vu dị, hung!", "Hào Chín Trên: Chim cháy thửa tổ, kẻ hành lữ trước cười, sau kêu gào, mất trâu chưng dễ dàng, hung!", 849, null));

        // Que 57 (TỐN)
        list.add(new LineJudgment(57, 1, "Sơ Lục", "巽,君⼦以申命⾏事. Dịch âm.- Tượng viết: Tùy phong Tốn, Quân tử dĩ thân mệnh hành sự. Dịch nghĩa. - Lời Tượng nói rằng: Theo gió là quẻ Tốn. Đấng quân tử coi đó mà nhắc lại mệnh lệnh, làm việc. GIẢI NGHĨA Truyện của Trình Di. - Hai luồng gió chồng nhau, tức là theo gió. “Theo” nghĩa là nối nhau, đấng quân tử coi Tượng hai lần Tốn nối nhau mà nhắc lại mệnh lệnh, thi hành chánh sự. “Theo” và “Chồng” tức là trên dưới đều thuận. Người trên thuận với kẻ dưới mà ban ra, kẻ dưới thuận với người trên mà làm theo, đó là trên dưới đều thuận theo cái nghĩa “hai lần nhún” vậy. Mệnh lệnh chính sự thuận lẽ thì hợp lòng dân mà dân thuận theo. Bản nghĩa của Chu Hy. - “Theo” là nghĩa nối nhau. LỜI KINH初六: 進退,利武⼈之貞.", "Tiến thoái, lợi vũ nhân chi trinh.", "Hào Sáu Đầu: Tiến lui, lợi về sự chính bền của người võ.", 855, null));
        list.add(new LineJudgment(57, 2, "Cửu Nhị", "象⽈: 進退,志疑也;利武⼈之貞,志治也. Dịch âm.- Tượng viết: Tiến thoái, chí nghi dã, lợi vũ nhân chi trinh, chí trị dã. Dịch nghĩa. - Lời Tượng nói rằng: Tiến lui chí ngờ vậy; lợi về nết chính bền của người võ; chí trị vậy. GIẢI NGHĨA Truyện của Trình Di. - Tiến lui không biết chỗ nào ở yên, là tại chí nó ngờsợ. Lợi dụng nết cương trinh của người dùng võ để dựng chí mình, thì chí mình trị: “Trị” nghĩa là sửa dựng vậy. LỜI KINH 九⼆: 巽在床下, ⽤史巫 紛若, 吉,⽆咎", "Tôn tại sàng hạ, dựng sử vu phân nhược, cát! Vo cữu!", "Hào Chín Hai: Nhún ở dưới giường , dùng thày bói, thày cúng bời bời vậy, tốt! Không lỗi! GỊẢI NGHĨA Truyện của Trình Di. - Hào Hai thực là cứng giữa, tuy thể Tốn mà ở chỗ mềm, là kẻ quá nhún, không phải là cố tà tâm. Kính nhún quá độ, tuy chẳng phải là lễ chính, nhưng cũng có thể xa sự sỉ nhục, tuyệt sự oán trách. Thày bói thày cúng là người thông đạt lòng thành tín với đấng thành minh. “Bởi vậy” tức là nhiều. Nết rất thành thực mà yên về đường khiêm nhún, có thể khiến cho thành ý thông đạt được nhiều thì tốt mà không lỗi, nghĩa là lòng thành của mình đủ để cảm động người ta vậy. Người ta không xét đến cái thành ý của mình, thì sẽ cho sự quá nhún là sự nịnh hót. Bản nghĩa của Chu Hy. - Hào Hai là chất Dương, động ngôi Âm mà ở chỗ thấp, có ý chẳng yên. Nhưng trong thì nhún, chẳng chán sự thấp[2], mà hào Hai lại có đức giữa, không đến quá lắm, cho nên lời Chiêm của nó, là: Có thể quá nhún mà lại đinh ninh phiền phức nói cho hết lời, để tự thông đạt, thì có thể tốt mà không lỗi. Cũng là lời Chiêm tốt lành về việc hết lòng thành để cúng tế vậy.", 856, null));
        list.add(new LineJudgment(57, 3, "Cửu Tam", "象 ⽈ . 紛 若 之 吉 .得 中 也 .Dịch âm. - Tượng viết: Phán nhược chi cát, đắc trung dã. Dịch nghĩa. - Lời Tượng nói rằng: Dường hời vậy mà tốt, được giữa vậy. GIẢI NGHĨA Truyện của Trinh Di. - Hào Hai vì đóng ngôi mềm, ở chỗ thấp là tượng quá nhún, mà có thể khiến cho thông đạt thành ý của mình, nhiều đến bời bời vậy, là tại nó được giữa vậy. Hào Dương ở giữa là Tượng trong thật. Bên trong đã thành thật thì người ta tự nhiên tin mình bằng ý thật, mà không phải là nịnh hót, sợ sệt nữa. Vì vậy mới tốt mà không lỗi. LỜI KINH 九 三 . 頻 巽 吝 .", "Tần tốn lận", "Hào Chín Ba: Liền nhún, đáng tiếc.", 857, null));
        list.add(new LineJudgment(57, 4, "Lục Tứ", "象 ⽈ . 頻 巽 之 吝 . 志 窮 也 . Dịch âm. - Tượng viết: Tần tốn chi lận, chí cùng dã. Dịch nghĩa. - Lời Tượng nói rằng: Liền nhún mà đáng tiếc, chí cùng vậy. GIẢI NGHĨA Truyện của Trình Di. - Tài chất hào Ba vốn không phải kẻ biết nhún, kẻ ở trên lại sát với nó bằng sự nhún vâng hai lần cứng mà xéo lên hào cứng, thế nó không thể thi hành chí mình, cho nên liền lỗi mà liền nhún, ấy là chí nộ cùng quấn, đáng tiếc lắm vậy. LỜI KINH 六 四 . 悔 亡 . ⽥ 獲 三 品 .", "Hối vong, điền hoạch tam phẩm.", "Hào Sáu Tư: Ăn năn mất, săn được ba phẩm.", 858, null));
        list.add(new LineJudgment(57, 5, "Cửu Ngũ", "九五：貞吉，悔亡，無不利，無初有終，先庚三日，後庚三日，吉。", "Cửu Ngũ: Trinh cát, hối vong, vô bất lợi, vô cơ hữu chung, tiêu canh tam nhật, hậu canh tam nhật, cát.", "Hào Chín Năm: Chính bền tốt, ăn năn mất, không gì lợi, không đầu có chót, trước canh ba ngày, sau canh ba ngày tốt!", 852, "PATCH THỦ CÔNG (2026-08-31): nhãn bị gõ nhầm \"Dịch âni.\" thay vì \"Dịch âm.\" trong bản scan, khiến parser tự động bỏ sót. Phần dịch âm giữ nguyên văn OCR (\"vô cơ hữu chung\", \"tiêu canh tam nhật\") dù nghi ngờ là lỗi in/OCR của chính \"vô sơ hữu chung\", \"tiên canh tam nhật\" (khớp nghĩa \"không đầu có chót\", \"trước canh ba ngày\") - KHÔNG tự sửa để tránh bịa, cần đối chiếu lại trước khi coi là cấp 1."));
        list.add(new LineJudgment(57, 6, "Thượng Cửu", "象 ⽈ . 九 五 之 吉 . 位 正 中 也 . Dịch âm. - Tượng viết: Cửu Ngũ chi cát, vị chính trung dã. Dịch nghĩa. – Lời Tượng nói rằng: Cái tốt của hào Chín Năm ngôi chính giữa vậy. GIẢI NGHĨA Truyện của Trình Di. – Cái tốt của hào Chín Năm, vì nó ở chỗ giữa chính. Được đạo chính giữa thì tốt mà sự ăn năn mất đi. LỜI KINH 上 九 . 巽 在 床 下 . 喪 其 資 斧 . 貞 凶 .", "Tốn tại sàng hạ, táng kỳ tư phủ, hung!", "Hào Chín Trên: Nhún ở dưới giường, mất thửa của búa, hung!.", 861, null));

        // Que 58 (ĐOÁI)
        list.add(new LineJudgment(58, 1, "Sơ Cửu", "初 九. 和 兌.吉.", "Hòa đoái, cát!", "Hào Chín Đầu: Hòa đẹp lòng, tốt!", 866, null));
        list.add(new LineJudgment(58, 2, "Cửu Nhị", "象⽈ . 和 兌 之 吉 . ⾏ 未 疑 也 . Dịch âm. - Tượng viết: Hòa đoái chi cát, hối vong. Dịch nghĩa. – Lời Tượng nói rằng: cái tốt của sự hòa đẹp lòng, đi chưa ngờ vậy. GIẢI NGHĨA Truyện của Trình Di. – Hào Đầu theo thì xử thuận, lòng không vướng víu, không định làm gì chỉ cần lấy hòa mà thôi, cho nên mới tốt. Lời Tượng lại vì nó ở thể đẹp lòng, đứng chỗ thấp, mà không giữa chính, cho nên nói rằng: “đi chưa ngờ vậy”. Nghĩa là sự đi của nó chưa có vẻ đáng ngờ, tức là chưa thấy nó có lỗi vậy. Nếu nó mà được giữa chính, thì sẽ không có câu nói ấy. Bản nghĩa của Chu Hy. - Ở về đầu quẻ, sự đẹp lòng của nó chưa có điều ngờ.LỜI KINH 九 ⼆ . 孚 兌 . 吉 . 悔 亡 .", "Phu đoái cát, hối vong.", "Hào Chín Hai: Tin đẹp lòng, tôt ăn năn mất.", 868, null));
        list.add(new LineJudgment(58, 3, "Lục Tam", "象 ⽈ . 孚 兌 之 吉 . 信 志 也 . Dịch âm. - Tượng viết: Phu đoái chị cát, tín chí dã. Dịch nghĩa. - Lời Tượng nói rằng: Tín đẹp lòng mà tốt, tín chí vậy. GIẢI NGHĨA Truyện của Trình Di. - Cái để trong lòng là chí. Hào Hai cứng đặc ở giữa, tức là phu tín để ở bên trong. Chí nó đã để về đường thành tín, há lại đến nỗi đẹp lòng với kẻ tiểu nhân mà tự mình làm mất bản tính của mình? vì vậy mới tốt. LỜI KINH六三 . 來 兌 . 凶 .", "Lai đoái, hung!", "Hào Sáu Ba: Lại đẹp lòng hung!", 869, null));
        list.add(new LineJudgment(58, 4, "Cửu Tứ", "象 ⽈ . 來 兌 之 凶 . 位 不 當 也 . Dịch âm. - Tượng viết: Lai đoái chi hung, vị bất đáng dã. Dịch nghĩa. - Lời Tượng nói rằng: Lại đẹp lòng mà hung, ngôi chẳng đáng vậy. Truyện của Trình Di. – Hào Âm ở chỗ không chính, không kẻ cùng với, mà cố liều cầu lấy đẹp lòng, vì vậy mới hung. LỜI KINH 九 四 . 商 兌 . 未 寧 . 介 疾 有 喜 .", "Thượng đoái, vị ning, giới tật, hữu hỷ.", "Hào Chín Tư: Đắn đo đẹp lòng chưa yên, thẳng ghét, có mừng.", 869, null));
        list.add(new LineJudgment(58, 5, "Cửu Ngũ", "象 ⽈ . 九 四 之 喜 . 有 慶 也 . Dịch âm. – Tượng viết: Cửu tứ chi hỷ, hữu khảnh dã. Dịch nghĩa. - Lời Tượng nói rằng: cái mừng của hào Chín Tư, có phúc vậy. GIẢI NGHĨA Truyện cửạ Trình Di. – gọi là cứng, nghĩa là nếu có giữ đường chính đínhmà vua đẹp lòng, thì được thi hành cái đạo Dương cứng của nó mà phúc khánh tới người. LỜI KINH 九 五 . 孚 于 剝 . 有 厲.", "Phu vu hấc, hữu lệ.", "Hào Chín Năm: Tin chung đẽo, có nguy.", 871, null));
        list.add(new LineJudgment(58, 6, "Thượng Lục", "象 ⽈ . 孚 于 剝 . 位 正 當 也 . Dịch âm. – Tượng viết: Phu vu bác, vị chính đương dã. Dịch nghĩa. - Lời Tượng nói rằng: Tin chưng đẽo, ngôi chính nên vậy.GIẢI NGHĨA Truyện của Trình Di. – Răn đừng tin chưng đẽo là ngôi của hào Năm chính nên răn vậy. Liền sát với kẻ Âm mềm, có cách sẽ đẹp lòng nhau, cho nên răn đừng tin nó. LỜI KINH 上 六 . 引 兌 .", "Dẩn đoái.", "Hào Sáu Trên: Dẫn đẹp lòng.", 872, null));

        // Que 59 (HOÁN)
        list.add(new LineJudgment(59, 1, "Sơ Lục", "象 ⽈ . ⾵ ⾏ ⽔ 上 . 渙 . 先 王 以 享 于 帝 ⽴ 廟 . Dịch âm. – Tượng viết: Phong hành thủy thượng, Hoán, tiên vương dĩ hưởng vu đế, lập miếu.Dịch nghĩa. – Lời Tượng nói rằng: Gió đi trên nước là quẻ Hoán. Đấng tiên vương coi đó mà cúng chưng trời, dựng miếu. GIẢI NGHĨA Truyện của Trình Di. Gió đi trên nước, có tượng tan lìa, đâng tiên vương coi tượng đó mà cứu sự tan lìa của thiên hạ, đến chưng cúng trời dựng miếu. Thu họp lòng người không gì bằng nhà tôn miếu; sự báo đáp trong việc cúng tế, do ở trong lòng mà ra; cho nên cúng trời, dựng miếu là việc mà lòng người theo về. Cái đạo buộc lòng người, họp sự lia tan không gì lớn hơn thế. LỜI KINH 初 六 . ⽤ 拯 ⾺ 壯 . 吉 .", "Chửng mã tráng, cát.", "Hào Sáu Đầu: Vớt ngựa mạnh, tốt.", 877, null));
        list.add(new LineJudgment(59, 2, "Cửu Nhị", "象 ⽈ . 初 六 之 吉 . 順 也 . Dịch âm. - Tượng viết: Sơ lục chi cát, thuận dã. Dịch nghĩa. – Lời Tượng nói rằng: Cái tốt của hào Sáu Đầu, thuận vậy. GIẢI NGHĨA Truyện của Trình Di. – Hào Đầu sở dĩ được tốt, vì nó biết thuận kẻ có tài cứng giữa. Mới tan mà cứu ngay, là biết thuận với thời. LỜI KINH 九 ⼆ . 渙 奔 其 機 . 悔 亡 .", "hoán bôn kỳ ngột, hối vong.", "Hào Chín Hai: Tan chạy thửa ghế! Ăn năn mất.", 878, null));
        list.add(new LineJudgment(59, 3, "Lục Tam", "象 ⽈ . 渙 奔 其 機 . 得 愿 也. Dịch âm. – Tượng viết: Hoán bôn kỳ ngột, đắc nguyện dã. Dịch nghĩa. – Lời Tượng nói rằng: Tan chạy thửa ghết, được ý muốn vậy. GIẢI NGHĨA Truyện của Trình Di. – trong thì lìa tan, lấy sự hợp lại mà yên ổn. Hào Hai ở trong chỗ hiểm, kíp tới vào hào Đầu, là tìm sự yên ổn vậy. Nhờ nó như thể cái ghết mà mất sự ăn năn của mình, ấy được thủa ý muốn đó. LỜI KINH 六 三 . 渙 其 躬 . 無 悔 .", "Hoán kỳ cung, vô hối.", "Hào Sáu Ba: Tan thửa mình, không ăn năn.", 879, null));
        list.add(new LineJudgment(59, 4, "Lục Tứ", "象 ⽈ . 渙 其 躬 . 志 在 外 也 . Dịch âm. - Tượng viết: Hoán kỳ cung, chí tại ngoại dã. Dịch nghĩa. - Lời Tượng nói rằng: Tan thửa mình, chí ở ngoài vậy. GIẢI NGHĨA Truyện của Trình Di. – Chí ứng với hào Trên, tức là ở ngoài . nó với hào Trên ứng nhau, cho nên thân nó được khỏi lìa tan mà không ăn năn. LỜI KINH 六 四 . 渙 其 群 . 元 吉 . 渙 有 丘 . 匪 夷 所 思 .", "Hoán kỳ quân, nguyên cát; hoán hữu khâu, phi di sở tư.", "Hào Sáu Tư: Tan thửa đàn, cả tốt; tan có gò, chẳng phải thường thửa nghĩ.", 880, null));
        list.add(new LineJudgment(59, 5, "Cửu Ngũ", "象 ⽈ . 渙 王 居 無 咎 . 正 位 也 . Dịch âm. – Tượng viết: Hoán kỳ quần, nguyên cát, quang đại dã. Dịch nghĩa. – Lời Tượng nói rằng: Tan thửa đàn, cả tốt, sáng lớn vậy. GIẢI NGHĨA Truyện của Trình Di. Gọi là cả tốt, nghĩa là công đức của nó lớn. “Cả tốt sáng lớn“ chẳng ở hào Năm mà ở hào Tư, là vì nghĩa của hai hào thông luôn với nhau. Ở hào Tư nói về sự thi hành công dụng, ở hào Năm nói về sự thành công, đó là sự khác nhau của vua tôi vậy. LỜI KINH九 五 . 渙 汗 其 ⼤ 號 . 渙 王 居 . 無 咎.", "Hoán hãn kỳ đại hiệu, hoán vương cư, vô cữu.", "Hào Chín Năm: Tan bồ hôi thửa hiệu lớn, tan chỗ ở của vua, không lỗi.", 882, null));
        list.add(new LineJudgment(59, 6, "Thượng Cửu", "象 ⽈ . 王 居 無 咎 . 正 位 也 .Dịch âm. - Tượng viết: Vương cư vô cữu, chính vị dã. Dịch nghĩa. - Lời Tượng nói rằng: Chỗ ở của vua ở không lỗi, ngôi chính vậy. GIẢI NGHĨA Truyện của Trình Di.- Chỗ ở của vua ý nói ngôi chính tức là ngôi tôn của kẻ làm vua. Có thể như hào Năm đã làm thì ở ngôi tôn là xứng đáng mà không có lỗi. LỜI KINH 上九. 渙其⾎去, 逖出, ⽆咎", "hoán kỳ huyết khứ, địch[4], xuất, vô cữu.", "Hào Chín Trên: Tan thửa máu đi, rùng rợn[5] ra, không lỗi.", 883, null));

        // Que 60 (TIẾT)
        list.add(new LineJudgment(60, 1, "Sơ Cửu", "以制數度.議德⾏. Dịch âm. – Tượng viết: Trạch thượng hữu thuy, Tiết, quân tử dĩ tiết chế số độ, nghị đức hạnh. Dịch nghĩa. – Lời Tượng nói rằng: Trên chằm có nước là quẻ Tiết. Đấng quân tử coi đó mà chế độ, bàn đức nết. GIẢI NGHĨA Truyện của Trình Di. – Chằm nó chứa nước có hạn, quá hạn thì đầy tràn. Đó là có tiết độ, cho nên mới là quẻ Tiết. Đấng quân tử cọi tượng quẻ Tiết mà chế dựng số độ, phàm trong các vật lớn nhỏ, nhẹ nặng, cao thấp, văn hoa, mộc mạc đều có số độ để làm chừng mực,”số” là kẻ về nhiều ít, “độ” là nói khuôn phép. Bàn đức nết là gì? Cái chứa ở trong cái đức, cái phát ra ngoài là nết, đúng nghĩa thì trúng tiết độ, bàn là cân nhắc so đo, cầu trung tiết độ vậy. LỜI KINH 初九.不出⼾庭.無咎.", "bất xuất hộ đình, vô cữu.", "Hào Chín Đầu: Chẳng ra sân cửa, không lỗi.", 888, null));
        list.add(new LineJudgment(60, 2, "Cửu Nhị", "象⽈.不出⼾庭.知通塞也. Dịch âm. – Tượng viết: bất xuất hộ đình, tri thông tắc dã. Dịch nghĩa. – Lời Tượng nói rằng: Chẳng ra sân cửa, biết thông tắc vậy. GIẢI NGHĨA Truyện của Trình Di. – Lời hào, ở đầu thì dè dặt, răn nó giữ gìn cần thận, cho nên nói rằng:”chẳng ra sân cửa, không lỗi” Lời Tượng sợ người ta câu nệ câu đó, cho nên lại nói rõ rằng: Dâu nên giữ gìn cẩn thận, chẳng ra sân cửa, lại phải biết thì thông hay tắc. Thông thì đi, tắc thì đậu, hễ nghĩa nên ra thì ra. LỜI KINH 九⼆.不出⾨庭.凶.", "bất xuất môn đình, hung.", "Hào Chín Hai: Chẳng ra sân cổng, hung.", 889, null));
        list.add(new LineJudgment(60, 3, "Lục Tam", "象⽈.不出⾨庭凶.失時極也. Dịch âm. – Tượng viết: Bất xuất môn đình hung, thất thì cực dã. Dịch nghĩa. – Lời Tượng nói rằng: Chẳng ra sân cổng, hung, lỗi thời đến tột bậc vậy. GIẢI NGHĨA Truyện của Trình Di. – Không thể đi lên mà theo đạo cứng và chính giữa của hào Chín Năm. Để làm nên công dè dặt, mà lại vương với kẻ Âm mềm riêng tây, ấy là lỗi thời đến tột bậc, vì vậy mới hung. Lỗi thời là lỗi với sự “đang nên” vậy. LỜI KINH 六三.不節若.則嗟若.無咎.", "Bất tiết nhược, tắt ta nhược, vô cữu", "Hào Sáu Ba: Chẳng dè dặt vậy, thì than thở vậy, không lỗi.", 890, null));
        list.add(new LineJudgment(60, 4, "Lục Tứ", "象⽈.不節之嗟.又誰咎也. Dịch âm. – Tượng viết: Bất tiết chi ta, hựu thùy cữu dã. Dịch nghĩa. – Lời Tượng nói rằng: Lời than của kẻ chẳng tự dè dặt, lại đổ lỗi cho ai. GIẢI NGHĨA Truyện của Trình Di. – Dè dặt thì có thể khỏi lỗi, mà chẳng tự dè dặt để đến đáng than thì còn trách ai? Bản nghĩa của Chu Hy. – Chữ “Vô cữu” này khác với các hào, ý nói không thể đổ lỗi cho ai vậy. LỜI KINH 六四.安節.亨.", "An tiết, hanh.", "Hào Sáu Tư: Yên dè dặt, hanh.", 891, null));
        list.add(new LineJudgment(60, 5, "Cửu Ngũ", "象⽈.安節之亨.承上道也. Dịch âm. –Tượng viết: An tiết chi hanh, thừa thượng đạo dã. Dịch nghĩa. – Lời Tượng nói rằng: Yên dè dặt mà hanh, vâng đạo trên vậy. GIẢI NGHĨA Truyện của Trình Di. – Cái nghĩa của hào Tư yên lòng với sự dè dặt, không phải chỉ có một tượng, đây chỉ nói điều trong yếu hơn. Trở nên vâng theo cái đạo cứng và giữa chính của hào Chín Năm để làm tiết độ, vì vậy mới hanh. Các điều hay khác cũng chẳng ra ngoài sự giữa chính. LỜI KINH 九五.⽢節.吉.往有尚.", "Cam tiết, cát vãng hữu thượng.", "Hào Chín Năm: Sự dè dặt ngọt, tốt, đi có chuộng.", 892, null));
        list.add(new LineJudgment(60, 6, "Thượng Lục", "象⽈.⽢節之吉.居位中也. Dịch âm. – Tượng viết: Cam tiết chi cát, cư vị trung dã. Dịch nghĩa. – Lời Tượng nói rằng: Cái tốt của sự dè dặt ngọt ở ngôi giữa vậy. GIẢI NGHĨA Truyện của Trình Di. – Đã ở ngôi tôn, lại được đạo giữa, vì vậy tốt mà có công sự dè dặt lấy vừa phải làm quý, được mực giữa là chính đáng rồi. LỜI KINH 上 六.苦節.貞凶.悔亡.", "Khổ tiết, trinh hung, hối vong.", "Hào Sáu Trên: Sự dè dặt khổ, chính bền hung, ăn năn mất.", 893, null));

        // Que 61 (TRUNG PHU)
        list.add(new LineJudgment(61, 1, "Sơ Cửu", "初九. 虞吉.有他不燕.", "Ngu cát, hữu tha, bất yên.", "Hào Chín Đầu: Lo tốt, có khác, chẳng yên.", 897, null));
        list.add(new LineJudgment(61, 2, "Cửu Nhị", "象⽈.初九虞吉.志未變也. Dịch âm. – Tượng viết: sơ cửu ngu cát, chí vị biến dã. Dịch nghĩa. – Lời nói Tượng nói rằng: Hào Chín Đầu lo tốt, chí chưa đổi vậy. GIẢI NGHĨA Truyện của Trình Di. – Đương lúc mới tin, chí mình chưa thể hăn vào đâu mà biết lo lường đo đắn cái điều mình tin, thì được chính đạo cho nên mới tốt, là vì chính mình đã còn chưa biến động. Nếu mà chí mình đã định theo về đường nào, thì là biến động rồi, sự lo lường không được chính đáng nữa. LỜI KINH九⼆.鳴鶴在陰.其⼦和之.我有好爵.吾與爾靡之.", "Minh hạc tại âm, kỳ tủ họa chi; ngã hữu hảo tước, ngô dữ nhi my chi.", "Hào Chín Hai: Con Hạc kêu ở chỗ tối, con nó họa đấy, ta có tước tốt, tớ cùng mày ràng[2] đấy.", 899, null));
        list.add(new LineJudgment(61, 3, "Lục Tam", "象⽈.其⼦和之.中⼼愿也. Dịch âm. –Tượng viết: Kỳ Tử họa chi, trung tâm nguyệt dã. Dịch nghĩa. –Lời Tượng nói rằng: Con có họa đó, trong lòng muốn vậy. GIẢI NGHĨATruyện của Trình Di. – Trong lòng muốn tức là điều mà ý thức vẫn muốn, cho nên nó mới thông nhau mà ứng nhau. LỜI KINH 六三.得敵.或⿎或罷.或泣或歌.", "Đắc địch, hoặc cổ hoặc bãi, hoặc khấp hoặc ca", "Hào Sáu Ba: Được kẻ địch, hoặc khua trông, hoặc thôi, hoặc khóc, hoặc múa.", 900, null));
        list.add(new LineJudgment(61, 4, "Lục Tứ", "象⽈.可⿎或罷.位不當也. Dịch âm. –Tượng viết: Hoặc cổ hoặc bãi, vị bất đáng dã. Dịch nghĩa. – Lời Tượng nói rằng: Hoặc khua trống, hoặc thôi ngôi chẳng đáng vậy. GIẢI NGHĨA Truyện của Trình Di. – Ở chẳng đáng ngôi, cho nên không có chủ trương, chỉ theo cái sự mình tin được đáng ngồi, thì sự mình tin có phương hướng rồi. LỜI KINH 六四.⽉⼏望.⾺匹亡.無咎.", "Nguyệt cơ vọng, mà xuất vong, vô cữu.", "Hào Sáu Tư: mặt trăng hầu tuần vọng, đôi ngựa mất , không lỗi", 901, null));
        list.add(new LineJudgment(61, 5, "Cửu Ngũ", "象⽈.⾺匹亡.絕類上也 Dịch âm. – Tượng viết: Mã thất vong, tuyệt loại thượng dã. Dịch nghĩa. – Lời Tượng nói rằng: Đôi ngựa mất, dứt loài lên vậy. GIẢI NGHĨA Truyện của Trình Di. – Dứt loài mình mà lên theo hào Năm. Loài ứng với nhau vậy. LỜI KINH 九五.有孚攣如.無 咎.", "Hữu phu loan như, vô cữu.", "Hào Chín Năm: Có tin dường như co quắp vậy, không lỗi.", 902, null));
        list.add(new LineJudgment(61, 6, "Thượng Cửu", "象⽈.有孚攣如.位正當也. Dịch âm. – Tượng viết: Hữu phu loan như, vị chính đáng dã. Dịch nghĩa. – Lời Tượng nói rằng: Có tin dương như co quắp vậy, ngôi chính đang vậy. GIẢI NGHĨA Truyện của Trình Di. – Hào Năm ở ngôi vua là chỗ tôn quý, bởi đạo giữa chính, có thể khiến cho thiên hạ tin mình bền chặt như có quắp lấy, mới là xứng ngôi. Cái đạo của kẻ làm vua nên như thế vậy. LỜI KINH 上九.翰⾳登于天.貞凶.", "Hàn âm đăng vu thiên, Trinh hung.", "Hào Chín Trên: Tiếng cánh lên chưng trời, chính bền hung.", 903, null));

        // Que 62 (TIỂU QUÁ)
        list.add(new LineJudgment(62, 1, "Sơ Lục", "初六.⾶⿃以凶.", "Phi điểu dĩ hung.", "Hào Sáu Đầu: Chim bay lấy hung.", 909, null));
        list.add(new LineJudgment(62, 2, "Lục Nhị", "象⽈.⾶⿃以凶.不可如何也.Dịch âm. – Tượng viết: Phi điểu dĩ hung, bất khả như hà dã. Dịch nghĩa. – Lời Tượng nói rằng: Chim bay lấy hung, chẳng khá dường sao vậy. GIẢI NGHĨA Truyện của Trình Di. – Sự quá của nó như chóng như thể chim bay, há cứu ngăn được? Hung là đáng lắm! Chẳng khá dường sao, nghĩa là không thể dùng sức được nữa. LỜI KINH 六⼆.過其祖.遇其妣.不及其君.遇其⾂.無咎 .", "Quá kỳ tổ, ngộ kỳ tỷ, bất cập kỳ quân, ngộ kỳ thần, vô cữu.", "Hào Sáu Hai: Quá thửa ông, gặp thửa bà; chẳng kịp thửa vua, gặp thửa bề tôi, không lỗi.", 910, null));
        list.add(new LineJudgment(62, 3, "Cửu Tam", "象⽈.從或戕之.凶如何也. Dịch âm. – Tượng viết: bất cập kỳ quân, thần bất khả dã. Dịch nghĩa. – Lời Tượng nói rằng: Chẳng kịp thửa vua, bề tôi không thể quá vậy. GIẢI NGHĨA Truyện của Trình Di. – Trong thời “quá”, việc gì cũng quá mực thường, cho nên với việc tiên lên, thì răn đừng kịp thửa vua, là vì bề tôi không thể quá phận bề tôi vậy. Bản nghĩa của Chu Hy. – Sở dĩ chẳng kịp vua lại gặp bề tôi, là vì tôi không thể quá. LỜI KINH 九三.弗過防之.從或戕之.凶.", "Phất quá phòng chi, tòng hoặc tường chi, hung!", "Hào Chín Ba: Chẳng quá ngừa đó, theo hoặc hại đó, hung!", 911, null));
        list.add(new LineJudgment(62, 4, "Cửu Tứ", "象⽈.從或戕之.凶如何也. Dịch âm. – Tượng viết: tòng hoặc tường chi, hung như hà dã. Dịch nghĩa. – Lời Tượng nói rằng: Theo hoặc hại đấy, hung dường như sao vậy. GIẢI NGHĨA Truyện của Trình Di. – Trong thời Âm quá, ắt phải hại Dương, đạo kẻ tiểu nhân thịnh, ắt hại đến người quân tử, nên quá ngừa đó. Ngừa nó không đến cùng tột, thì bị nó hại, cho nên nói rằng “hung dường sao” nghĩa là tệ lắm vậy. LỜI KINH 九四.無咎.弗過遇之.往厲必戒.勿⽤永貞.", "Vô Cữu, phất quá ngộ chi, vãng lệ, tất giới vật dụng vĩnh trinh.", "Hào Chín Tự: Không lỗi chẳng quá gặp đấy, đi nguy, ắt răn, chớ dùng dài lâu chính bền.", 912, null));
        list.add(new LineJudgment(62, 5, "Lục Ngũ", "六五.密云不⾬.⾃我西郊.公⼷取彼在⽳.", "mật vân bất vũ, tự ngã tây giao, công dặc thủ bỉ, tại huyệt.", "Hào Sáu Năm: Mây dầy chẳng mưa, ở cõi tây ta, ông bắn lấy nó ở hang.", 914, null));
        list.add(new LineJudgment(62, 6, "Thượng Lục", "象⽈.密云不⾬.已上也. Dịch âm. – Tượng viết: Mật vân, bất vũ, dĩ thượng dã. Dịch nghĩa. – Lời Tượng nói rằng: mây dầy chẳng mưa, đã lên vậy. GIẢI NGHĨA Truyện của Trình Di. – Dương lên Âm xuống, hợp nhau thì hoa nhau mà thành mưa, Âm đã ở trên , mây tuy dầy há nên được mửa? Đó là nghĩa âm quá không thể thành mưa. Bản nghĩa của Chu Hy. – Đã trên tức là quá cao. LỜI KINH 上六.弗遇過之.⾶⿃離之.凶.是謂災眚.", "Phất ngộ quá chi, phi điểm ly chi, hung thị vị tai sảnh.", "Hào Sáu Trên: Chẳng gặp, quá đây, chim bay lìa đấy, hung, ấy rằng vạ tội.", 915, null));

        // Que 63 (KÝ TẾ)
        list.add(new LineJudgment(63, 1, "Sơ Cửu", "象⽈.⽔在⽕上.既濟.君⼦以思患⽽預防之. Dịch âm. – Tượng viết: Thủy tại hỏa thượng, Ký tế, quan tử dĩ tư hoạn nhi dự phòng chi. Dịch nghĩa. – Lời Tượng nói rằng: Nước ở trên lửa là quẻ Ký tế, đáng quan tử coi đó để nghĩ sự lo mà ngừa sẵn đấy. GIẢI NGHĨA Truyện của Trình Di. – Nước lừa đã giao nhua, thứ nào được dùng của thứ ấy, tức là đã sang. Gặp thì “đã sang”. Chỉ sợ vạ hại sinh ra, cho nên nghĩ cách ngừa sẵn đi, khiên cho không đến phải lo. Từ xưa thiên hạ yên rồi mà lại đến phải vạ loạn, đều tại không biết lo nghĩ mà ngừa sẵn cả. LỜI KINH 初九.曳其輪.濡其尾.無咎.", "Duệ kỳ luân, nhu kỳ vy, vô cữu.", "Hào Chín Đầu: Kéo thửa bánh xe, ướt thửa đuôi không lỗi.", 920, null));
        list.add(new LineJudgment(63, 2, "Lục Nhị", "象⽈.曳其輪.義無咎也. Dịch âm. – Tượng viết: Duệ kỳ luân, nghĩa vô cữu dã. Dịch nghĩa. – Lời Tượng nói rằng: Kéo thửa bánh xe, nghĩa không lỗi vậy. GIẢI NGHĨA Truyện của Trình Di. – Đầu lúc đã sang, biết ngăn sự tiến thì không lỗi cùng cực, nghĩa đó tự nhiên không lỗi. LỜI KINH六⼆.婦喪其茀.勿逐.七⽇得.", "Phụ táng kỳ phất, vật trục, thất nhật đắc.", "Hào Sáu Hai: Đàn bà mất thửa khăn trùm[2] chớ đuổi bảy ngày được.", 921, null));
        list.add(new LineJudgment(63, 3, "Cửu Tam", "象⽈.七⽇得.以中道也. Dịch âm. – Tượng viết: Thất nhật đắc, di trung đạo dã.Dịch nghĩa. – Lời Tượng nói rằng: bây ngày được, vì đạo giữa vậy. GIẢI NGHĨA Truyện của Trình Di. – Cái đạo giữa chính tuy chẳng dược dùng đến, nhưng không có lẽ đến cùng không được thi hành, cho nên mất khăn trùm, bây ngày sẽ lại được, nghĩa là tự giữ đạo giữa, lúc khác ắt được thi hành. Không mất mực giữa thì là chính rồi. LỜI KINH 九三.⾼宗伐⿁⽅.三年克之.⼩⼈勿⽤.", "Cao Tông phạt Quỷ Phương, tam nhiên khắc chi, tiểu nhân vật dụng.", "Hào Chín Ba: Vua Cao Tông đánh nước Quỷ Phương, ba năm được đấy, kẻ tiểu nhân chờ dùng.", 922, null));
        list.add(new LineJudgment(63, 4, "Lục Tứ", "象⽈.三年克之.憊也 Dịch âm. –Tượng viết: Tam niên khắc chi, bại dã. Dịch nghĩa. – Lời của Tượng nói rằng: Ba năm được đó, mệt vậy. GIẢI NGHĨA Truyện của Trình Di. – Nói mệt cho thấy việc đó rất khó, vua Cao Tông làm thì được, nếu không có bụng như vua Cao Tông, thì là tham lam tức tôi, để làm hại dân. LỜI KINH 六四.繻有⾐袽.終⽇戒.", "Nhu hữu y như, chung nhật giới.", "Hào Sáu Tư: ướt có áo giẻ, trọn ngày răn.", 923, null));
        list.add(new LineJudgment(63, 5, "Cửu Ngũ", "繻 (nhu) đổi làm chữ 濡 (nhu) đọc là thăm dò vậy. Thuyền có hẻ dò thì nhét bằng áo giẻ. Có áo giẻ để phòng bịsự dò mà lại trọn ngày răn sợ, không nhắc, lo vạ nên như thế vậy. Bản nghĩa của Chu Hy. – Đương thì đã sang, lấy chất mềm ở ngôi mềm, là kẻ biết dự bị lo sợ, cho nên Tượng nó như thế. LỜI KINH 象⽈.終⽇戒.有所疑也. Dịch âm. – Tượng viết: Chung nhật giới, hữu sơ nghĩ dã. Dịch nghĩa. – Lời Tượng nói rằng: Trọn ngày răn, có thửa ngờ vậy. GIẢI NGHĨA Truyện của Trình Di. – Trọn ngày răn sợ, là thường ngờ rằng vạ lo sắp tới. Ở thì đã sang, nên răn sợ như thế. LỜI KINH 九五.東鄰殺⽜.不如西鄰之祭.實受其福.", "Đông lân sát ngưu, bất như tây lân chi thược tế, thật thụ kỳ phúc.", "Hào Chín Năm: Láng giềng bên Đông giết trâu, chẳng bằng láng giềng bên Tây tế Thược, thật chịu thửa phúc.", 924, null));
        list.add(new LineJudgment(63, 6, "Thượng Lục", "象⽈.東鄰殺⽜.不如西鄰之時也.實受其福.吉⼤來也. Dịch âm. – Tượng viết: Đông lân sát ngưu bất như tây lân chi thì dã; thậ thụ kỳ phúc, cát đại lai dã. Dịch nghĩa. – Lời Tượng nói rằng: Láng giềng bên Đông giết trâu, chằng bằng láng giềng bên Tây phải thời vậy; thật chịu thửa phúc, tốt cả lại vậy. GIẢI NGHĨA Truyện của Trình Di. – Tài đến hào năm không phải chẳng hay, nhưng khong phải thì bằng hào Hai. Hào Hai ở dưới là thời có tiến, cho nên giữa chính mà tin, thì sự tốt cả lại, thế gọi là chịu phúc. “Tốt cả lại” nghĩa là thời đang sang, tức là “cả lại” tức là “hanh nhỏ, đầu tốt” vậy. LỜI KINH 上六.濡其⾸.厲.", "Nhu kỳ thủ, lệ!", "Hào Sáu Trên: Ướt thửa đầu, nguy!GIẢI NGHĨA Truyện của Trình Di. – Chót cuộc đã sang vẫn là chẳng yên mà nguy. Lại kẻ mềm ở ngôi đó mà đứng trên thể hiêm, khảm là nước, sang cũng lấy nghĩa là nước, cho nên nói cùng cực đến nỗi ướt đầu, đủ biết là nguy. Chót cuộc đã sang mà kẻ tiểu nhân ở vào ngôi đó, sự bại hoại của nó có thể đứng mà đợi được. Bản nghĩa của Chu Hy. – chót cuộc đã sang, trên thể hiểm, mà lấy tài Âm mềm ở vào chỗ đó, là Tượng con cáo lội nước mà ướt đầu. Kẻ xem không biết răn sợ, tức là đạo nguy.", 925, null));

        // Que 64 (VỊ TẾ)
        list.add(new LineJudgment(64, 1, "Sơ Lục", "初六.濡其尾.吝.", "Nhu kỳ vĩ lận!", "Hào Sáu Đầu: Ướt thửa đuôi, tiếp đáng!", 929, null));
        list.add(new LineJudgment(64, 2, "Cửu Nhị", "象⽈.濡其尾.亦不知極也. Dịch âm. – Tượng viết: nhu kỳ vĩ, Diệc bất trí cực dã. Dịch nghĩa.- Lời Tượng nói rằng: Ướt thửa đầu, cũng chẳng biết cực vậy. GIẢI NGHĨA Truyện của Trình Di. – Chẳng lượng tài lực mà tiên, đến chứng ướt đầu, ấy là “chẳng biết” đến tột bậc. Bản nghĩa của Chu Hy. – Chữ 極 (cực) chưa rõ nghĩa là gì. Xét vẫn trên dưới cũng không hợp, e là chữ 敬 (kính) nay đã chừa lại đó. LỜI KINH 九⼆.曳其輪.貞吉.", "Duệ kỳ luân, trinh cát.", "Hào Chín hai: Kéo thửa bánh xe, chính bền, tốt.", 930, null));
        list.add(new LineJudgment(64, 3, "Lục Tam", "六三.未濟.征凶.利涉⼤川.", "Vị tế chinh hung, lợi thiệp đại xuyên.", "Hào Sáu ba: Chưa sang đi hung, lợi về sang sông lớn.", 931, null));
        list.add(new LineJudgment(64, 4, "Cửu Tứ", "利 (lợi) còn có chữ 不(bất). LỜI KINH 象⽈.未濟征凶.位不當也. Dịch âm. – Tượng viết: Vị tế chinh hung, vị bất đáng dã. Dịch nghĩa.- Lời Tượng nói rằng: chưa sang đi hung, ngôi chẳng đang vậy. GIẢI NGHĨA Truyện của Trình Di. – Hào Ba đi thì hung, vì ngôi không đáng Ý nói nó là kẻ Âm mềm chẳng giữa chẳng chính, lại không có tài ra khỏi chỗ hiểm. Nếu vượt quá được chỗ hiểm đẻ theo kẻ ứng với mình thì có lợi. LỜI KINH 九四.貞吉.悔亡.震⽤伐⿁⽅.三年有賞于⼤國.", "Trinh cát, hối vong, chấn dụng phát Quỷ Phương, Tam niên hữu thương vu đại quốc.", "Hào Chín Tư: Chính bền, ăn năn mất, nhức dùng đánh nước Quỷ Phương, ba năm, có thương chưng nước lớn.GIẢI NGHĨA Truyện của Trình Di. –Hào Chín Tư là chất Dương cứng, ở ngôi đại thần, trên có ông vua trống giữa sáng thuận, lại đã ra khỏi chỗ hiểm, chưa sang nhưng quá giữa rồi, tức là có cách sang được. Làm cho thiên hạ quá sự gian nan, nếu không có tài cứng mạnh, thì không làm nổi , hào Chín tuy là Dương mà ngôi Tư, cho nên răn phải chính bền thì tốt, mà sự ăn năn sẽ mất, không chính bền không sang được, là có ăn năn. Nhức là động đến tột bậc. Người xưa dùng sức nhiều nhất là việc đánh nước Quỷ Phương, cho nên lấy nó làm nghĩa, sức siêng mà đánh xa, đến chừng ba năm, rồi mới nên việc. Bản nghĩa của Chu Hy. – Lấy hào Chín ở ngôi Tư, chẳng chính mà có ăn năn. Có thể gắng mà chính bền, thì sự ăn năn sẽ mất. Nhưng vì nó là tư chất không chính bên, thì sự ăn năn sẽ chết. Nhưng vì nó là tư chất chính bền, muốn gắng mà chính bền nếu không do đức dương cứng thì dùng sức lâu thì không thể được nên là Tượng “đánh nước Quỷ Phương ba năm mà được nhận thưởng”.", 932, null));
        list.add(new LineJudgment(64, 5, "Lục Ngũ", "象⽈.貞吉悔亡.志⾏也. Dịch âm. – Tượng viết: Trinh cát, hối vong, chí hành dã. Dịch nghĩa.- Lời Tượng nói rằng: Chính bền tốt, ăn năn mất, chí được thi hành vậy. GIẢI NGHĨA Truyện của Trình Di. – Như tài hào Tư, hợp được với thì mà lại thêm đức chính bền, thì có thể thực hành chí mình, thế là tốt lành mà sự ăn năn sẽ mất. Việc đánh nước Quỷ Phương, là chính bền đến tột bậc vậy.LỜI KINH 六五.貞吉無悔.君⼦之光.有孚.吉.", "Trinh cát, vong hối, quân tử chi quang, hữu phu, cát.", "Hào Sáu Năm: chính bền tốt, không ăn năn, sự sáng của đấng quân tử, có tin tốt.", 934, null));
        list.add(new LineJudgment(64, 6, "Thượng Cửu", "象⽈.君⼦之光.其暉吉也. Dịch âm. – Tượng viết: quân tử chi quang, kỳ huy cát dã.Dịch nghĩa.- Lời Tượng nói rằng: sự sáng của đấng quân tử, thửa tia sáng tốt vậy. GIẢI NGHĨA Truyện của Trình Di. –Sáng thịnh thì có tia sáng, tia sáng tức là ánh sáng tan ra. Đấng quân tử chưa chất đầu đủ mà sự sáng đến chưng có tia, tức là hay đến tột bậc, cho nên lại nói là tốt. LỜI KINH 上九.有孚于飲酒.無咎.濡其⾸.有孚失是.", "Hữu Phu vu ẩm tửu, vô cữu, nhu kỳ thủ, hữu phu, thất thị.", "Hào Chín Trên: có tin chưng uống rượu, không lỗi, ướt thửa đầu, có tin, mất phải.", 935, null));

        return List.copyOf(list);
    }
}
