package io.destinyos.engines.iching;

import java.util.ArrayList;
import java.util.List;

/**
 * Hao tu (爻辭) content for hexagrams 33-48, King Wen order - see
 * {@link LineJudgment} for source and verification status (R25).
 */
final class LineJudgments3 {

    private LineJudgments3() {
    }

    static List<LineJudgment> entries() {
        List<LineJudgment> list = new ArrayList<>();

        // Que 33 (ĐỘN)
        list.add(new LineJudgment(33, 1, "Sơ Lục", "初六:聽尾,萬,勿⽤有攸往.", "Độn vỹ, lệ! Vật dụng hữa du vãng.", "Hào Sáu Đầu: Trốn đuôi, nguy! Chớ dùng có thửa đi.", 538, null));
        list.add(new LineJudgment(33, 2, "Lục Nhị", "象⽈:遯尾之属,不往何災也. Dịch âm. - Tượng viết: Độn vỹ chi lệ, bất vãng hà tai dã.Dịch nghĩa. - Lời Tượng nói rằng: Cái nguy của sự trốn đuôi, không đi hại gì vậy? GIẢI NGHĨA Truyện của Trình Di. - Thấy cơ lánh trước, vẫn là phải rồi, đi lánh mà làm cái đuôi, là đạo nguy đó. Đi đã có nguy, chẳng bằng không đi mà nấp cho kín, có thể khỏi hại, vì rằng hào này ở chỗ nhỏ nhặt, cho nên mới thế. Người đời xưa ở chỗ nhỏ, ẩn chỗ thấp, đời loạn mà không đi cùng nhiều. LỜI KINH 六⼆:執之⽤黄⽜之⾰,莫之滕說.", "Chấp chi dụng hoàng ngưu chi cách, mạc chi thắng[3] thoát.", "Hào Sáu Hai: Giữ đó, dùng da trâu vàng không ai trút nổi?", 539, null));
        list.add(new LineJudgment(33, 3, "Cửu Tam", "象⽈:執⽤黄⽜,固志也. Dịch âm. - Tượng viết: Chấp dụng hoàng ngưu, cố chí dã. Dịch nghĩa. - Lời Tượng nói rằng: Giữ dùng trâu vàng, bền chí vậy. GIẢI NGHĨA Truyện của Trình Di. - Kẻ trên người dưới lấy đạo trung thuận cố kết với nhau, tâm chí của họ rất bền, như thể ràng giữ bằng da trâu vậy. LỜI KINH 九三:繫遯有疾,厲,畜⾂妾,吉.", "Hệ độn, hữu tật, lệ! Xúc thần thiếp, cát.", "Hào Chín Ba: Vướng trốn, có tật nguy! Nuôi đầy tớ nàng hầu, tốt.", 540, null));
        list.add(new LineJudgment(33, 4, "Cửu Tứ", "象⽥:繫遯之属,有疾憊也.畜⾂妾吉, 不可⼤事也. Dịch âm. - Tượng viết: Hệ độn chi lệ, hữu tật bại dã; sức thần thiếp cát, bất khả đại sự dã. Dịch nghĩa. - Lời Tượng nói rằng: Vướng trốn mà dữ, là có tật mệt vậy; nuôi đầy tớ nàng hầu, tốt, là không thể làm việc lớn vậy. GIẢI NGHĨA Truyện của Trình Di. - Trốn mà có vướng víu, ắt phải vì sự mỏi mệt mà nguy, có tật là mỏi mệt, nghĩa là không đủ sức nữa. Dùng lòng yêu thương riêng tây đó mà nuôi đầy tớ nàng hầu thì tốt, nhưng có thể đương nổi việc lớn. LỜI KINH 九四,好遯,君⼦吉,⼩⼈否.", "Hiếu độn, quân tử cát, tiểu nhân phủ[4].", "Hào Chín Tư: Yêu trốn, đấng quân tử tốt, kẻ tiểu nhân không.", 541, null));
        list.add(new LineJudgment(33, 5, "Cửu Ngũ", "象⽈: 君⼦好遯,⼩⼈否也. Dịch âm. - Tượng viết: Quân tử hiếu độn, tiểu nhân phủ dã. Dịch nghĩa. - Lời Tượng nói rằng: Đấng quân tử yên trốn, kẻ tiểu nhân thì không vậy. GIẢI NGHĨA Truyện của Trình Di. - Đấng quân tử dù có yêu thích, nhưng biết trốn đi, không lỗi với nghĩa, kẻ tiểu nhân thì không thể đè nổi ý riêng, mà đến không hay. LỜI KINH 九五:嘉遯,貞吉.", "Gia Độn, trinh cát.", "Hào Chín Năm: Tốt trốn, chính tốt.", 542, null));
        list.add(new LineJudgment(33, 6, "Thượng Cửu", "象⽈:嘉遯貞吉,以正志也. Dịch âm. - Tượng viết: Gia độn trình cát, dĩ chính chí dã. Dịch nghĩa. - Lời Tượng nói rằng: Tốt trốn chính tốt, vì chính chí vậy. GIẢI NGHĨA Truyện của Trình Di. - Tâm chí chính đính thì hành động ắt theo đường chính đính, cho nên là sự trốn tốt. Ở ngôi giữa, được chỗ chính, mà lại ứng nhau với kẻ trung chính, đó là tâm chí chính đính, cho nên được tốt. Người ta hành động hay ngừng trôi, thì cốt chính đính chí mình mà thôi. LỜI KINH 上九:肥遯,無不利.", "Phì độn, vô bất lợi.", "Hào Chín Trên: Béo trốn, không gì không lợi.", 543, null));

        // Que 34 (ĐẠI TRÁNG)
        list.add(new LineJudgment(34, 1, "Sơ Cửu", "初九:壯于趾,征凶,有孚.", "Tráng vu chỉ, chính hung, hữu phu.", "Hào Chín Đầu: Mạnh ở ngón chân, đi thì hung, có tin.", 549, null));
        list.add(new LineJudgment(34, 2, "Cửu Nhị", "象⽈:壯于趾, 貞孚窮也. Dịch âm. - Tượng viết: Tráng vu chỉ, kỳ phu cùng dã. Dịch nghĩa. - Lời tượng nói rằng: Mạnh ở ngón chân, thửa tin cùng vậy. GIẢI NGHĨA Truyện của Trình Di. - Ở chỗ dưới nhất mà dùng sự mạnh để đi, có thể tin hẳn là sẽ cùng khốn mà hung. Bản nghĩa của Chu Hy. - Ý nói ắt phải cùng khốn. LỜI KINH 九⼆:貞吉.", "Trình cát", "Hào Chín Hai: Chính tốt.", 550, null));
        list.add(new LineJudgment(34, 3, "Cửu Tam", "象⽈:九⼆負吉,以中也 Dịch âm. - Tượng viết: Cửu Nhị trinh cát, dĩ trung dã. Dịch nghĩa. - Lời Tương nói rằng: Hào Chín Hai chính tốt, về giữa vậy. GIẢI NGHĨA Truyện của Trình Di. - Sở dĩ chính và tốt, vì nó được đạo “giữa” vậy. “Giữa” thì không lỗi sự chính, huống chi nó lại là chất Dương cứng mà ở thể Kiền…!LỜI KINH 九三:⼩⼈⽤壯,君⼦⽤罔,貞鷹.羝⽺觸藩,羸其⾓.", "Tiểu nhân dụng tráng, quân tử dụng võng, trinh lệ, đê dương xúc phiên, doanh kỳ giốc.", "Hào Chín Ba: Kẻ tiểu nhân dùng mạnh, đấng quân tử dùng chẳng, chính nguy! Dê đực húc giậu, mắc thửa sừng.", 551, null));
        list.add(new LineJudgment(34, 4, "Cửu Tứ", "象⽈:⼩⼈⽤壯,君⼦⽤罔也. Dịch âm. - Tượng viết: Tiểu nhân dụng tráng, quân tử võng dã. Dịch nghĩa. - Lời Tượng nói rằng: Kẻ tiểu nhân dùng mạnh, đấng quân tử chẳng vậy. GIẢI NGHĨA Truyện của Trình Di. - Ở kẻ tiểu nhân thì là dùng sức khỏe mạnh của họ, ở đấng quân tử thì là dùng “chẳng”, nghĩa là chí khí cứng mạnh, không coi các việc vào đâu; không kiêng sợ gì cả. Bản nghĩa của Chu Hy. - Kẻ tiểu nhân vì mạnh mà hỏng, đấng quân tứ vì “chẳng” mà khốn. LỜI KINH 九四:貞吉,悔亡,藩決不羸,壯于⼤輿之馥.", "Trinh cát, hối vong, phiên quyết bất doanh, tráng vụ đại dư chỉ phúc.", "Hào Chín Tư: Chính thì tốt, ăn năn mất, phên bựt chẳng mắc, mạnh ở vành trục xe lớn.GIẢI NGHĨA Truyện của Trình Di. - Hào Tư Dương cứng lớn thịnh, sự mạnh đã qua mực giữa, ấy là mạnh lắm. Nhưng nó ở ngôi Tư, tức là bất chính, nhằm khi đạo đấng quân tử đương lớn lên, không thể có sự bất chính, vì vậy, răn rằng: hễ chính thì tốt, mà sự ăn năn sẽ mất. Bởi vì nhằm khi Đạo đương lớn lên, hơi có sai lỗi thì hại đến thế hanh tiến, thế là có ăn năn. Nếu ở quẻ khác, hai lần cứng mà ở ngôi mềm, chưa hẳn không hay, tức như quẻ Đại quá vậy. Giậu là cái để ngăn cách, giậu phên bựt mở, thì không làm mắc sự mạnh của nó. Cái xe cao lớn, bánh trục khỏe mạnh, sự đi mà lợi có thể biết chắc, cho nên nói rằng: “Mạnh ở vành trục xe lớn”. Vành trục là chỗ cốt yếu củã bánh xe. Xe hỏng thường vì gãy cái vành trục, vành trục mạnh thì xe mạnh. Nói rằng “mạnh ở vành trục” nghĩa là mạnh về sự tiến vậy. Bản nghĩa của Chu Hy. - Bốn chữ “trình cát, hối vong” cũng như lời Chiêm của hào Chín Tư quẻ Hằng, Giậu bựt chẳng mắc, là nói tiếp theo hào trên. Bựt tức là mở, trước hào Ba có hào Tư là còn có giậu; trước hào Tư đến hai hào Âm, thì là giậu bựt. Mạnh ở vành trục xe lớn cùng là Tượng có thể tiến được. Là chất Dương, ở ngôi Âm, không đến cứng quá cho nên Tượng. Chiêm của nó như thế.", 552, null));
        list.add(new LineJudgment(34, 5, "Lục Ngũ", "象⽈:藩決不赢, 尚斧也. Dịch âm. - Tượng viết: Phiên quyết bất doanh, thượng vãng dã. Dịch nghĩa. - Lời Tượng nói rằng: Giậu bựt chẳng mắc, còn đi vậy. , GIẢI NGHĨA Truyện của Trình Di. - Dương cứng lớn lên, ắt đến cùng tột. Hào Tư duy Dương đã thịnh, nhưng sự đi của nó chưa thôi. Lấy chất Dương rất thịnh,dùng sự mạnh mà tiến lên, cho nên chẳng gì đương nổi, giậu phải bựt mở, không làm vướng mắc sức nó. “Còn đi”, tức là tiến lên không thôi. LỜI KINH 六五:喪⽺予易,無悔.", "Táng dương vu dị, vỏ hổi.", "Hào Sáu Năm: Mất dê ở sự dễ không ăn năm.", 554, null));
        list.add(new LineJudgment(34, 6, "Thượng Lục", "場 (trường) viết là 易 (trường). Lời bàn của Tiên Nho. - Chu Hy nói rằng: Chữ 易 trong câu 喪 ⽺于易 đọc là “dị” không bằng đọc là “trường”, như chữ 場 (trường) trong tiếng 韁場(cương trường). Sau đây lại có câu 喪⽺于易 cũng cùng nghĩa đó. LỜI KINH 象⽈:喪⽺于易,位不當也. Dịch âm. - Tượng viết: Táng dương vu dị, vị bất đáng dã. Dịch nghĩa. - Lời Tượng nói rằng: Mất dê ở sự dễ, ngôi không đáng vậy. GIẢI NGHĨA Truyện của Trình Di. - Sở dĩ phải dùng cách mềm mại hòa thuận, là vì hào này lấy chất Âm mềm ở ngôi tôn. Nếu là chất Dương cứng trung chính được ngôi tôn, thì ở dưới không có kẻ mạnh. Lấy hào ở ngôi Năm, là ngôi không đáng, cho nên mới đặt ra cái nghĩa “mất dê ở sự dễ”. LỜI KINH 上六:羝⽺觸藩,不能退,不能逐,無攸利,難則吉.", "Dê dương xúc phiên, bất năng thoái, bất năng toại, vô du lợi, gian tắc cát.", "Hào Sáu Trên: Dê đực húc giậu, chẳng hay lui, chẳng hai toại, không thửa lợi, khó thì tốt.", 555, null));

        // Que 35 (TẤN)
        list.add(new LineJudgment(35, 1, "Sơ Lục", "象⽈:⽕在地上,晉,君⼦以⾃眧眧德.. Dịch âm. - Tượng viết: Hỏa tại địa thượng. Tấn, quân tử dĩ tự chiêu minh đức. Dịch nghĩa. - Lời Tượng nói rằng: Lửa ở trên đất, là quẻ Tấn. đấng quân tử coi đó để tự làm tỏ đức sáng. GIẢI NGHĨA Truyện của Trình Di. - “Chiêu” là làm cho tỏ ra. Đấng quân tử coi tượng sáng ra trên đất mà càng sáng thịnh, để tự làm cho tỏ đức sáng của mình. Bỏ sự che lấp đi, đem sự biết lại, là tỏ đức sáng ở mình, làm rõ đức sáng với thiên hạ là tỏ đức sáng với bên ngoài. Làm rõ đức sáng ở mình, cho nên nói rằng “tự tỏ”. Bản nghĩa của Chu Hy. - “Chiêu” là làm cho rõ ra.LỜI KINH 軔六:晉如,等如,負吉,罔孚,裕無咎.", "Tấn như, tồi như, trình cát, võng phu, dạ vô cữu.", "Hào Sáu Đầu; Dường tiến lên vậy, dường đun lại vậy, chính thì tốt, chẳng tin, khoan thai không lỗi.", 561, null));
        list.add(new LineJudgment(35, 2, "Lục Nhị", "六⼆:⾳如,愁如,負吉,受兹介福于其王母.", "Tấn như, sầu như, trinh cát, thụ tư giới phúc vu kỳ vương mẫu.", "Hào Sáu Hai: Dường tiến vậy, dường sầu vậy, chính thì tốt, nhận phúc lớn ấy chưng thuở bà nội.", 562, null));
        list.add(new LineJudgment(35, 3, "Lục Tam", "象⽈:受兹介福,以中正也. Dịch âm. - Tượng viết: Thụ tư giới phúc, dĩ trung chính dã. Dịch nghĩa. - Lời Tượng nói rằng: Nhận phúc lớn ấy, vì trung chính vậy. GIẢI NGHĨA Truyện của Trình Di. - Nhận phúc lớn ấy bằng đạo trung chính. Người ta biết giữ đạo trung chính, lâu rồi ắt được hưởng thụ, huống chi có bậc cả sáng ở trên, mà lại cùng đức với mình, thì ắt được nhận phúc lớn.LỜI KINH 六三:衆允,悔亡", "Chúng doãn, hối vong.", "Hào Sáu Ba: Mọi người tin, ăn năn mất.", 564, null));
        list.add(new LineJudgment(35, 4, "Cửu Tứ", "象⽈:泉允之志,上⾏也. Dịch âm. - Tượng viết: Chúng doãn chi chí, thượng hành dã. Dịch nghĩa. - Lời Tượng nói rằng: Cái chí được mọi người tin, vì đi lên vậy. GIẢI NGHĨA Truyện của Trình Di. - Đi lên nghĩa là phía trên thuận bám vào chỗ cả sáng. Trên theo ông vua cả sáng tức là chỗ giống nhau của chí mọi người. LỜI KINH 九四:晉如,鼦⿏,貞利.", "Tấn như, thạch thử trinh lệ.", "Hào Chín Tư: Dường tiến vậy, con chuột đồng, chính bền, nguy!", 564, null));
        list.add(new LineJudgment(35, 5, "Lục Ngũ", "象⽈:鼦⿏貞利,铉不當也. Dịch âm. - Tượng viết: Thạch thử trinh lệ, vị bất đáng dã. Dịch nghĩa. - Lời Tượng nói rằng: Chuột đồng chính nguy, ngôi chẳng đáng vậy. Truyện của Trình Di. - Người hiện vì chính đức mới nên ở ngôi trên, bất chính mà ở ngôi cao thì là không đáng; tham lam mà chỉ sợ mất thời hay sợ người, ở mãi chỗ đó, đủ biết là nguy. Lời bàn của Tỉên Nho. - Vương Đồng Nghê nói rằng: Trong thì mềm tiến, mà hào Chín Tư một mình tiến bằng cách cứng, cho nên cái nghĩa sự tiến đó, với sự trinh là nguy, với ngôi là không đáng.LỜI KINH 六異:悔亡,失得,勿恤,往吉,無不利.", "Hối vong, thất đắc vật tuất, vãng cát, vô bất lợi.", "Hào Sáu Năm: Ăn năn mất, mất được chớ lo, đi thì tốt, không gì không lợi.", 566, null));
        list.add(new LineJudgment(35, 6, "Thượng Cửu", "象⽈:失得勿恤,往有庚也. Dịch âm. - Tượng viết: Thất đắc vật tuất, vãng hữu khánh dã. Dịch nghĩa. - Lời Tượng nói rằng: Mất được chớ lo, đi có phúc vậy. GIẢI NGHĨA Truyện của Trình Di. - Lấy đức cả sáng, được kẻ dưới phụ vào đem lòng thành thực mà tin dùng họ, thì có thể làm nên công lớn của thiên hạ, thế là đimà có phúc khánh. LỜI KINH 上九:晉其⾓,維⽤伐⾢,厲,吉無咎,貞吝.", "Tấn kỳ dốc, duy dụng phạt ấp, lệ! Cát vô cữu, trinh lận.", "Hào Chín Trên: Tiến thửa sừng, bui dùng đánh làng, lo thì tốt, không lỗi, trinh thì đáng tiếc.", 567, null));

        // Que 36 (MINH DI)
        list.add(new LineJudgment(36, 1, "Sơ Cửu", "初九:明夷于作,垂其翼;君⼦于⾏, 三⽇不⾷,肴攸往,主⼈有⾔.", "Minh di vu phi, thùy kỳ dực; quân tử vu hành, tam nhật bất thực; hữu du vãng; chủ nhân hữu ngôn.", "Hào Chín Đầu: Sáng đau chưng bay; đủ thửa cánh; đấng quân tử chưng đi, ba ngày chẳng ăn; có thửa đi; người chủ có nói.", 572, null));
        list.add(new LineJudgment(36, 2, "Lục Nhị", "象⽈:考⼦于⾏,義不⾷也. Dịch âm. - Tượng viết: Quân tử vu hành, nghĩa bất thực dã. Dịch nghĩa. - Lời Tượng nói rằng: Đấng quân tử chưng đi nghĩa là chẳng ăn vậy.GIẢI NGHĨA Truyện của Trình Di. - Đấng quân tử lành nấp mà khốn cùng, nghĩa nên thế vậy. Chỉ theo nghĩa nên thế nào thì làm thế ấy, cho nên ở yên mà không buồn, dầu rằng chẳng ăn cũng được. Bản nghĩa của Chu Hy. - Nghĩa là ở đâu thì theo ở đấy chẳng ăn cũng được. Lời bàn của Tiên Nho. - Vương Đồng Khuê nói rằng: “Đấng quân tử chưng đi” nghĩa là bỏ lộc và ngồi vậy. “Ba ngày không ăn” nghĩa là không đáng ăn lộc vậy. LỜI KINH 六⼆:明夷,夷于左股,⽤_,⾺狀吉.", "Minh di, di vu tả cổ, dụng chửng, mã tráng cát", "Hào Sáu Hai: Sáng đau, đau ở đùi bên tả, dùng cứu, ngựa mạnh tốt.", 574, null));
        list.add(new LineJudgment(36, 3, "Cửu Tam", "象⽈:六⼆之吉,順以則也. Dịch âm. - Tượng viết: Lục Nhị chi cát, thuận dĩ tắc dã. Dịch nghĩa. - Lời Tượng nói rằng: Cái tốt của hào Sáu Hai, vì thuận bằng phép vây. GIẢI NGHĨA Truyện của Trình Di. - Hào Sáu Hai mà được tốt, vì nó xử thuận mà có phép tắc. Phép là đạo trung chính; biết thuận mà được trung chính, cho nên ở thì sáng đau mà có thể giữ được sự tốt. LỜI KINH 九三:明夷于南狩,得其⼤⾸,不可疾貞.", "Minh di vu nam thù, đắc kỳ đại thủ, bất khả tật trinh.", "Hào Chín Ba: Sáng đau chưng cuộc săn bên nam được thừa đầu lớn, chẳng khá kíp chính.GIẢI NGHĨA Truyện của Trình Di. - Hào Chín Ba ở trên quẻ Ly là sáng đến tột bậc, lại chỗ cứng mà tiến lên; hào Sáu Trên ở trên quẻ Khôn, là tối đến tột bậc; rứt sáng ở dưới mà làm bậc trên thể dưới, rứt tối ở trên, mà ở chỗ cùng cực, hai đẳng ứng địch với nhau, là kẻ sẽ dùng sự sáng để trừ sự tối, ấy là việc của vua Thang vua Vũ[3] đó chăng? Bên Nam ở về phía trước mà là phương sáng, săn bắn là việc trừ hại, săn bên Nam nghĩa là tiến lên mà trừ hại, nên bắt được đầu lớn của nó; đầu lớn chỉ về chùm đầu của đám tối, tức là hào Sáu Trên. Hào Ba với hào Trên cùng ứng với nhau, là tượng kẻ rứt sáng được kẻ rứt tối. Không thể kíp chính, nghĩa là giết kẻ đầu ác, và trừ tục cũ thói dơ chưa thể thay đổi ngay được, ắt phải thay đổi dần dần, vội quá thì nó sợ hãi mà không yên…Cho nên nói rằng không thể kíp chính, nghĩa là không thể kíp làm cho nó ngay thẳng. Hào Sáu Trên tuy không phải ngôi vua, vì nó ở trên mà là tối đến cùng cực, cho nên là chủ sự tối, mới gọi là đầu lớn. Bản nghĩa của Chu Hy. - Lấy chất cứng ở chỗ cứng, lại ở trên thể sáng, mà bị khuất dưới rất tối, chính là ứng nhau với hào Sáu Trên, chủ của sự tối, cho nên cố tượng ngảnh sáng, trừ hại bắt được kẻ đầu ác; nhưng mà không thể kíp ngặt, cho nên mới có lời răn không thể kíp chính. Vua Thành Thang nổi lên ở trên ngục Hạ đài[4], vua Văn Vương dấy lên ở ngục Dũ Lý, chính là hợp nghĩa của hào này, mà việc nhỏ cũng có như thế.", 575, null));
        list.add(new LineJudgment(36, 4, "Lục Tứ", "象⽈:南狩志之,乃⼤得也. Dịch âm. - Tượng viết: Nam thú chi chí, nãi đại bất đắc dã. Dịch nghĩa. - Lời Tượng nói rằng: Chí săn bên Nam, bền cả được vậy. GIẢI NGHĨATruyện của Trình Di. - Ôi lấy sự sáng của kẻ dưới trừ sự tối của kẻ trên, chí nó cốt trừ hại mà thôi, như vua Thang, vua Vũ của nhà Thương, nhà Chu, há có ý muôn lấy thiên hạ làm lợi? Bắt được đầu lớn của nó ấy là bỏ được sự hại mà cả được chí minh. Chí nếu không thế, thì tức là việc trái loạn. LỜI KINH 六四:⼊于左腹,獲明夷之⼼,于出⾨庭.", "Nhập vu tả phúc, hoạch minh di chi tâm, vu xuất môn định.", "Hào Sáu Tư: Vào chưng bụng bên tả được cái lòng sáng đau: chưng ra cửa sân.", 577, null));
        list.add(new LineJudgment(36, 5, "Lục Ngũ", "象⽈:⼊于左腹,獲⼼意也. Dịch âm. - Tượng viết: Nhập vu tả phúc, hoạch tâm ý dã. Dịch nghĩa. - Lời Tượng nói rằng: Vào chưng bụng bên tả, được lòng ý vậy. GIẢI NGHĨA Truyện của Trình Di. - Vào chưng bụng bên tả, nghĩa là lấy đạo cong lệch, vào với vua, mà được lòng ý của hắn. Được lòng hắn cho nên cùng chót vẫn không tỉnh ngộ.LỜI KINH 六五:箕;f之明夷,利貞.", "Cơ Tử chi minh di, lợi trinh.", "Hào Sáu Năm, ông Cơ Tử chưng sáng đau, lợi về chính bền.", 579, null));
        list.add(new LineJudgment(36, 6, "Thượng Lục", "參⽈:箕⼦⽓員,明不可息也. Dịch âm. - Tượng viết: Cơ Tử chi trinh, minh bất khả tức dã. Dịch nghĩa. - Lời Tượng nói rằng: Ông Cơ Tử chưng chính, sự sáng không thể tắt vậy. GIẢI NGHĨA Truyện của Trình Di. - Ông Cơ Tử ẩn náu, không mất sự chính bền, tuy gặp hoạn nạn, sự sáng vẫn còn, không thể dứt tắt vậy. Nếu gặp vạ lo mà để cho mất cái điều mình vẫn cầm giữ, thì là mất sự sáng, ấy là dứt tắt. Người xưa; như Dương Hùng[6] là hạng đó. LỜI KINH 上六:不明,晦,初登于天,後⼊于地.", "Bất minh hối; sơ đăng vu thiên, hậu nhập vu địa.", "Hào Sáu Trên: Chẳng sáng; tối đầu lên chưng trời, sau vào chưng đất.", 580, null));

        // Que 37 (GIA NHÂN)
        list.add(new LineJudgment(37, 1, "Sơ Cửu", "初九:閑有家,蜂亡.", "Nhàn hữu gia, hối vong.", "Hào Chín Đầu: Ngăn ngừa có nhà, ăn năn mất.", 585, null));
        list.add(new LineJudgment(37, 2, "Lục Nhị", "象⽈:間有⾗,志未變也. Dịch âm. - Tượng viết: Nhàn hữu gia, chí vị biện dã.. Dịch nghĩa. - Lời Tượng nói rằng: ngăn ngừa có nhà, chí chưa đổi vậy. GIẢI NGHĨA Truyện của Trình Di. - Ngăn ngừa từ lúc đầu, tức là trước khi ý chí người nhà chưa biến động. Chính chí chưa trôi tan biến động mà ngăn ngừa họ, thì không hại ân, không mất nghĩa, khu xử trong nhà như thế là khéo, cho nên sự ăn năn phải mất đi. Nếu để chí ý biến động mới trị, thì phải hại nhiều, ấy là có sự ăn năn? Bản nghĩa của Chu Hy. - Chí chưa biến mà ngừa sẵn.LỜI KINH 六⼆:無攸逐,在中饋,員吉.", "Vô du toại, tại trung quỹ, trinh cát.", "Hào Sáu Hai: không thửa thỏa, ở trong, chủ việc ăn uống, chính tốt.", 587, null));
        list.add(new LineJudgment(37, 3, "Cửu Tam", "象⽈:六⼆之吉,順以巽也. Dịch âm. - Tượng viết: Lục Nhị chi cát, thuận dĩ tốn dã. Dịch nghĩa. - Lời Tượng nói rằng: Cái tốt của Hào Sáu Hai, thuận và nhún vậy.GIẢI NGHĨA Truyện của Trình Di. - Hào Hai lấy chất Âm mềm ở chỗ trung chính, tức là kẻ biết thuận theo mà thấp nhún, cho nên là sự chính tốt của đàn bà. LỜI KINH 九三:家⼈嚆嗓,晦,厲,吉; 婦⼦嘻", "Gia nhân hạc hạc, hối, lệ, cát: phu tử hy hy. chung lận.", "Hào Chín Ba: Người nhà nem nép (?), hối dữ, tốt; vợ con hơn hớn, sau chót thẹn tiếc.", 588, null));
        list.add(new LineJudgment(37, 4, "Lục Tứ", "象⽈:家⼈嚆嚆,未失也, 婦⼦嘻嘻,失家節也. Dịch âm. - Tượng viết: Gia nhân hạc hạc, vị thất dã; phụ tử hy hy, thất gia tiết dã. Dịch nghĩa. - Lời Tượng nói rằng: Người nhà nem nép, chưa mất vậy; vợ con hơn hớn, mất tiết độ của nhà vậy. GIẢI NGHĨA Truyện của Trình Di. - Tuy nem nép về đạo trị nhà, chưa là lỗi lắm. Bằng như vợ con hơn hớn, thì là không có lễ phép, mất tiết độ của nhà, nhà ất phải loạn. LỜI KINH 六四:富家,⼤吉.", "Phú gia, đại cát", "Hào Sáu Tư: Giàu nhà, cả tốt.GIẢI NGHĨA Truyện của Trình Di. - Hào Sáu lấy thể nhún thuận mà ở ngôi Tư, là được, ngôi chính. Ở được ngôi chính là nghĩa ở yên, nhún thuận về công việc mà lại noi theo chính đạo, ấy là kẻ giữ được sự giàu có của mình. Cách ở nhà giữ được sự giàu, thì là cả tốt. Bản nghĩa của Chu Hy. - Dương chủ về nghĩa, Âm chủ về lợi, lấy chất Âm ở ngôi Âm, lại là ngôi cao, ấy là kẻ có thể làm giàu cho nhà mình.", 589, null));
        list.add(new LineJudgment(37, 5, "Cửu Ngũ", "象⽈:富家⼤吉,順在位也. Dịch âm. - Tượng viết: Phú gia đại cát, thuận tại vị dã. Dịch nghĩa. - Lời Tượng nói rằng: Giàu nhà cả tốt, thuận ở ngôi vậy. GIẢI NGHĨA Truyện của Trình Di. – Lấy đức nhún thuận mà ở ngôi chính, chính mà nhún thuận, ấy là kẻ giữ được giàu của mình. Tức là sự cả tốt của nhà giàu vậy. LỜI KINH 九五:王假有家勿恤吉.", "Vương cách hữu gia, vật, tuất cát.", "Hào Chín Năm: Vua đến có nhà, chớ lo, tốt.", 590, null));
        list.add(new LineJudgment(37, 6, "Thượng Cửu", "象⽈:王假有家,交相愛也. Dịch âm. - Tượng viết: Vương cách hữu gia, giao tương ái dã. Dịch nghĩa. - Lời Tượng nói rằng: Vua đến có nhà, yêu lẫn nhau vậy. GIẢI NGHĨA Truyện của Trình Di. - Cái đạo “vua đến có nhà”,không phải chỉ khiến người ta thuận theo mà thôi, phải làm cho họ thật lòng hóa theo, thực ý hợp với, chồng yêu người nội trợ của mình, vợ yêu người trị nhà của mình, thế là “yêu lẫn nhau”. Được như thế, có lẽ bà phi của vua Văn Bằng như thân sửa,phép đựng, mà nhà chưa hóa, thì chưa được là đạo “đến có nhà”. LỜI KINH 上九:有孚威如,終吉.", "Hữu phu uy như, chung cát", "Hào Chín Trên: Có tin, đường oai nghiêm vậy, trọn tốt,", 592, null));

        // Que 38 (KHUÊ)
        list.add(new LineJudgment(38, 1, "Sơ Cửu", "初九:晦亡,喪⾺,勿逐,⾃復,⾒惡⼈,無咎.", "Hối vong: táng mả, vật trục, tự phục, kiến ác nhân, vô cữu.", "Hào Chín Đầu: Ăn năn mất, mất ngựa, chớ đuổi theo tự nhiên trở lại, thấy người ác, không lỗi.", 599, null));
        list.add(new LineJudgment(38, 2, "Cửu Nhị", "象⽈:⾒惡⼈,以辟咎也. Dịch âm. - Tượng viết: Kiến ác nhân, dĩ ty cữu dã. Dịch nghĩa. - Lời Tượng nói rằng: Thấy người ác, để tránh lỗi vậy. GIẢI NGHĨA Truyện của Trình Di. - Trong khí lìa cách, tình người trái nhau, cầu hòa hợp lại còn không thể được. Nếu lấy cớ là người ác mà cự tuyệt đi, thì sẽ làm cho nhiều người thù hằn đấng quân tử mà vạ lỗi đến vậy. Cho nên, ắt phải thấy họ, để tránh khỏi sự oán trách. Hễ không cò sự oán trách, thì là có cách hợp được. LỜI KINH 九⼆:遇主于巷,無咎.", "Ngộ chủ vu hạng, vô cữu.", "Hào Chín Hai: Gặp chúa ở ngõ, không lỗi.", 600, null));
        list.add(new LineJudgment(38, 3, "Lục Tam", "六三:⾒與曳,其⽜掣,其⼈,天且剕,無初有終.", "Kiến dư duệ, kỳ ngưu xiết, kỳ nhân, thiên thả ty, vô sơ hữu chung.", "Hào Sáu Ba: Thấy xe kéo, thửa trâu kìm, thửa người gọt đầu và xẻo mũi. Không đầu, có chót.", 602, null));
        list.add(new LineJudgment(38, 4, "Cửu Tứ", "九四:睽孤,遇元夫,交孚,厲,無咎.", "Khuê cô, ngộ nguyên phu, giao phu, lệ, vôcữu.", "Hào Chín Tư: Lìa côi, gặp chàng lành, tin lẫn, nguy, không lỗi.", 603, null));
        list.add(new LineJudgment(38, 5, "Lục Ngũ", "象⽈:交孚無咎,志⾏也. Dịch âm. - Tượng viết: Giao phu vô cữu, chí hành dã. Dịch nghĩa. - Lời Tượng nói rằng: Tin lẫn, không lỗi, chí được thực hành vậy. GIẢI NGHĨA Truyện của Trình Di. - Hào Đầu hào Tư đều là bậc quân tử Dương cương, gặp thời lìa cách, kẻ trên người dưới lấy lòng chí thành giao kết nhau, hiệpchí chung sức với nhau, thì chí của nó có thể được thực hành, chẳng những không lỗi mà thôi. LỜI KINH 六五:晦亡,厥宗噬冬往何咎？", "Hối vong, quyết tôngphệ phu, vãng, hà cữu?", "Ăn năn mất, thửa họ cắn da, đi, lỗi gì?", 605, null));
        list.add(new LineJudgment(38, 6, "Thượng Cửu", "象⽈:厥宗噬膚,往有慶也. Dịch âm. - Tượng viết: Quyết tông phệ phu, vảng hữu khánh dã. Dịch nghĩa. - Lời Tượng nói rằng: Thửa họ cắn da, đi có phúc vậy.GIẢI NGHĨA Truyện của Trình Di. - Lời hào chỉ nói: Thửa họ cắn da, thì có thể đi mà không lỗi. Lời Tượng suy rõ nghĩa đó mà rằng: Kẻ làm vua tuy là tài mình không đủ, nếu biết tin dùng bậc hiền phụ, để họ đem đạo của họ vào sâu với mình, thì có thể làm việc, ấy là đi mà có phúc khánh. LỜI KINH 上九. 睽孤.⾒⾗負涂.載⿁⼀⾞.先張之弧.后說之弧.匪寇婚 媾.往遇⾬則 吉.", "Khuê cố kiến thỉ phụ đồ, tái quỉ nhất xa, tiên trương chi hồ, hậu thoát chi hồ, phỉ khấu, hôn cấu! Văng, ngộ vũ tắc cát.", "Hào Chín Trên: Lìa cô thấy lợn đội bùn, chở ma một xe, trước giương chưng cung, sau tháo chưng cung, chẳng phải giặc, dâu gia, đi, gặp mưa thì tốt.", 606, null));

        // Que 39 (KIỂN)
        list.add(new LineJudgment(39, 1, "Sơ Lục", "初六:往蹇, 來譽.", "Vãng kiển, lai dự.", "Hào Sáu Đầu: Đi kiển, lại khen.", 613, null));
        list.add(new LineJudgment(39, 2, "Lục Nhị", "象⽈:往蹇來宜待也. Dịch âm. - Tượng viết: Vãng kiển lai dự, nghi đãi dã. Dịch nghĩa. - Lời Tượng nói rằng: Đi kiển, lại khen, nên đợi vậy. GIẢI NGHĨA Truyện của Trình Di. - Đương thì kiển, tiến thì càng kiển, vì là thời chưa tiến được, cho nên, hãy nến thấy cơ mà đậu, để đợi thời, lúc nào đi được sẽ đi. Các hào đều đi thi kiển mà lại thì càng hay, thế thì không có cái nghĩa ra khỏi vận kiển hay sao? Đáp rằng: ở vận kiển mà đi thì kiển, vận kiển hết thì sẽ thay đổi. LỜI KINH 六⼆:王⾂蹇蹇,匪躬之故", "Vương thần kiển kiển, phí cung chi cố.", "Hào Sáu Hai: Tôi vua kiển kiển, chẳng phải cớ của mình.", 614, null));
        list.add(new LineJudgment(39, 3, "Cửu Tam", "象⽈:王⾂蹇蹇,終無尤也 Dịch âm. - Tượng viết: Vương thần kiển kiển, chung vô cữu dã. Dịch nghĩa. - Lời Tượng nói rằng: Tôi vua kiển, sau chót không lỗi vậy. GIẢI NGHĨA Truyện của Trình Di. - Dù bị khó khăn ngáng trở trong thì kiển, nhưng chí nó cốt ở giúp cho vua được qua nạn, tuy chưa thành công, song mà về sau không có lầm lỗi, là để khuyên khích sự trung tẫn vậy. Bản nghĩa của Chu Hy. - Việc tuy không xong, cũng chẳng có gì đáng trách. LỜI KINH 九三:往蹇來反", "Vâng kiểu lai phản.", "Hào Chín Ba: Đi kiển lại thì lại.", 615, null));
        list.add(new LineJudgment(39, 4, "Lục Tứ", "象⽈:往蹇來反,内喜之也. Dịch âm. - Tượng viết: Văng kiển lai phản, nội hỷ chi dã. Dịch nghĩa. - Lời Tượng nói rằng: Đi thì kiển, lại thì trở lại, trong thích đó vậy. GIẢI NGHĨA Truyện của Trình Di. - “Trong” là hào Âm ở dưới. Đương thì kiển, kẻ mềm không thể tự lập, cho nên đều phụ vào hào Chín Ba, là một hào Dương, mà yêu thích nó. Hào Ba ở quẻ Kiển, là được nơi chốn. Ở thì kiển, mà được lòngkẻ dưới, thì có thể cầu được yên ổn, cho nên mới lấy việc “lại” làm việc “về”. LỜI KINH 六四:往蹇來連.", "Vãng kiển lai liên.", "Hào Sáu Tư: Đi kiển, lại thì liền.", 617, null));
        list.add(new LineJudgment(39, 5, "Cửu Ngũ", "九五:⼤蹇朋來.", "Đại kiển bằng lai.", "Hào Chín Năm: Cả Kiển bạn lại.", 618, null));
        list.add(new LineJudgment(39, 6, "Thượng Lục", "参⽈:⼤考朋來,以中節也. Dịch âm. - Tượng viết: Đại kiển bằng lai, dĩ trung tiết dã. Dịch nghĩa. - Lời Tượng nói rằng: Cả kiển bạn lại vì tiết giữa (?) vậy. GIẢI NGHĨA Truyện của Trình Di. - Bạn là bè loài của nó. Hào Năm có đức trung chính, mà hào Hai cũng trung chính, tuy thì cả kiển, không bỏ mất sự thảo thủ, chịu kiển trong hồi kiển để cùng giúp nhau là vì cái tiết trung chính của nó. Trên dưới đều trung chính mà không vượt qua vận kiển là tại tài của bề tôi không đủ. Từ xưa, những người thủ tiết giữ nghĩa, mà tài không đủ làm qua vận kiển có phải ít đâu? Lý Cố, Vương Doãn nhà Hán, Chu Khải, Vương Đạo nhà Tấn đều là hạng người đó. LỜI KINH 上六:往蹇來碩,吉,利⾒⼤⼈.", "Vãng kiển lai thạc, cát, lợi kiến đại nhân.", "Hào Sáu trên: Đi kiển lại lớn, tốt, lợi về sự thấy người lớn.", 619, null));

        // Que 40 (GIẢI)
        list.add(new LineJudgment(40, 1, "Sơ Lục", "象⽈:雷⾬作,解,君⼦以赦過宥罪. Dịch âm. - Tượng viết: Lôi vũ tác, Giải, quân tử dĩ xá quá hựu tội. Dịch nghĩa. - Lời Tượng nói rằng: Sấm mưa nổi lên, là quẻ Giải, đấng quân tử coi đó mà xá lỗi, tha tội. GIẢI NGHĨA Truyện của Trình Di. - Trời đất giải tán mà thành sấm mưa, cho nên sấm mưa nổi lên mà là quẻ Giải. Xá là tha, hựu là khoan dong, lầm lỗi thì tha cũng được, tội ác mà tha thì không phải nghĩa, cho nên chỉ khoan dong mà thôi. Đấng quân tử coi tượng sấm mưa nổi lên thành quẻ Giải, thể theo sự phát dục của nó thì ân đức, thể theo sự giái tán của nó thì làm việc khoan thứ vậy. LỜI KINH 初六:無咎.", "Vô cữu.", "Hào Sáu Đầu: Không lỗi.", 626, null));
        list.add(new LineJudgment(40, 2, "Cửu Nhị", "象⽈:剛柔之睽,義無咎也. Dịch âm. - Tượng viết: Cương nhu chi tế, nghĩa vô cửu dã. Dịch nghĩa. - Lời Tượng nói rằng: Cứng mềm giao tế, nghĩa không lỗi vậy. GIẢI NGHĨA Truyện của Trình Di. - Hào Đầu hào Tư ứng nhau, ấy là cứng mềm giao tiếp với nhau. Cứng mềm giao tế với nhau là đúng với sự thích nghi. Nạn đã giải rồi, mà xử được cứng mềm vừa phải, nghĩa không lỗi vậy. LỜI KINH 九⼆:⽥擭三狐,得黄⽮, 貞吉.", "Điền hoạch tam hồ, đắc hoàng thi, trinh cát.", "Hào Chín Hai: Săn được ba con cáo, được tên vàng, chính bền thì tốt.", 627, null));
        list.add(new LineJudgment(40, 3, "Lục Tam", "象⽈:九⼆貞吉,得中道冬 Dịch âm. - Tượng viết: Cửu Nhị trinh cát, đắc trung đạo dã. Dịch nghĩa. - Lời Tượng nói rằng: Hào Chín Hai chính bền thì tốt vì được trung đạo vậy. GIẢI NGHĨA Truyện của Trình Di. - Bảo là “chính bền thì tốt” vì được trung đạo vậy. Trừ bỏ kẻ tà ác, khiến đạo trung chính ngay thẳng có thể thực hành, thế là chính mà tốt.LỜI KINH 六三:負且乘,致寇⾄,貞吝.", "Phụ thả thừa, tri khấu trí, trinh lận.", "Hào Sáu Ba: Đội và cưỡi, dắt giặc đến, chính bền cũng đáng tiếc.", 629, null));
        list.add(new LineJudgment(40, 4, "Cửu Tứ", "九四:解⽽拇,朋⾄斯孚.", "Giải nhi mẫu, bằng chi tư phu.", "Hào Chín Tư: Giải ngón chân cái mày, bằng đến ấy tin.", 630, null));
        list.add(new LineJudgment(40, 5, "Lục Ngũ", "象⽈:解⽽拇,未當位也. Dịch âm. - Tượng viết: Giải nhi mẫu, vị đáng vị dã. Dịch nghĩa. - Lời Tượng nói rằng: Giải ngón chân cái mày, chưa đáng ngôi vậy. GIẢI NGHĨA Truyện của Trình Di. - Hào Tư tuy là Dương cứng, nhưng ở ngôi Âm, về sự chính ngờ rằng chưa đủ, nếu lại gần gũi với kẻ tiểu nhân, thì ắt lỗi mất chính đạo, cho nên răn rằng: ắt phải ngón chân cái mình rồi mới có thể khiến cho đấng quân tử kéo đến, thế là tại mình ở chưa được đáng ngôi. Giải, nghĩa là vốn đương hợp nhau mà tự lìa ra, ắt phải giải ngón chân cái mà sau bạn mới tin, là vì đấng quân tử giao du với nhau, mà kẻ tiểu nhân xen vào, thì là lòng thành đối đấng quân tử, chưa được đến nơi. LỜI KINH 六五:君⼦維有解,吉,有孚于⼩⼈.", "Quân tử duy hữu giải, cắt, hữu phu vu tiểu nhân.", "Hào Sáu Năm: Đấng quân tử chỉ có giải, tốt, có tin chưng kẻ tiểu nhân.", 632, null));
        list.add(new LineJudgment(40, 6, "Thượng Lục", "象⽈:君⼦有解,⼩⼈退也. Dịch âm. - Tượng viết: Quân tử hữu giải, tiểu nhân thoái dã. Dịch nghĩa. - Lời Tượng nói rằng: Đấng quân tử có giải, kẻ tiểu nhân lui vậy. GIẢI NGHĨA Truyện của Trình Di. - Đấng quân tử mà giải là việc lùi bỏ kẻ tiểu nhân, tiểu nhân đi thì đạo quân tử thực hành được, cho nên mới tốt.LỜI KINH 上六:公⽤射準于⾼墉之上,獲之,無不利.", "Công dụng xạ chuẩn vu cao dung chi thượng, hoạch chi, vô bất lợi.", "Hào Sáu Trên: Ông dùng bắn chim cắt ở trên, tường cao, được nó, không gì không lợi.", 633, null));

        // Que 41 (TỔN)
        list.add(new LineJudgment(41, 1, "Sơ Cửu", "象⽈:善下有澤,損.君⼦以懲忿窒欲. Dịch âm. - Tượng viết: Sơn hạ hữa trạch, Tổn, quân tử dĩ trừng phẫn, chất dục. Dịch nghĩa. - Lời Tượng nói rằng: Dưới núi có chằm, là quẻ Tổn đấng quân tử coi đó mà răn sự giận, lấp lòng dục. GIẢI NGHĨA Truyện của Trình Di. - Dưới núi có chằm, khí nó thông lên, và thấm lên, và đào chỗ thấp để làm cho tăng bề cao, đều là Tượng “bớt của kẻ dưới”. Đấng quân tử xem Tượng “sự bớt” đó mà tự mình bớt đi. Trong đạo sửa mình, cái nên bớt chỉ là sự tức giận và lòng tham muốn, cho nên mình phải lấy đức mà răn sự giận, lấp hết ý muốn của mình. Bản nghĩa của Chu Hy. - Đấng quân tử sửa mình, cái nên giảm bớt, không gì quan hệ bằng mấy điều này. LỜI KINH 初九:已事,遄往,無咎,酌損之.", "Dĩ sự, xuyền váng, vô cữa, chước tổn chi.", "Hào Chín Đầu: Xong việc[3], mau đi, không lỗi, châm chước mà bớt đấy.GIẢI NGHĨA Truyện của Trình Di. - Nghĩa của quẻ Tổn là bớt của vật cứng thêm cho vật mềm, bớt của kẻ dưới, thêm cho kẻ trên, hào Đầu lấy chất Dương cứng ứng với hào Tư, hào Tư lấy chất Âm mềm ở ngôi trên, là kẻ nhờ ở hào Đầu thêm cho. Kẻ dưới thêm cho người trên, nên tự bớt của mình, mà chớ nhận là công của mình. Cái đã thêm cho người trên, xong việc, thì đi cho chóng, chớ tự ở vào chỗ công lao, mới không có lỗi. Nếu cứ hưởng cái tốt đẹp của sự thành công, thì không phải là bớt của mình để thêm cho người trên, với đạo làm kẻ dưới, như thế là có lỗi. Hào Tư Âm mềm, là kẻ nhờ cậy hào Đầu, hào Đầu nên châm chước cân nhắc sự nên chăng, bớt của mình mà thêm cho nó, thái quá và bất cập, đều là không được. Bản nghĩa của Chu Hy. - Hào Chín Đầu nhằm lúc cần nên bớt của dưới, thêm cho trên, phía trên ứng nhau với hào Sáu Tư, nên thôi cái việc đương làm, mà đi cho chóng để làm ích cho nó, đó là đạo không lỗi, cho nên Tượng và Chiêm của nó như thế. Nhưng ở dưới mà làm ích cho người trên, cũng nên châm chước nóng sâu.", 641, null));
        list.add(new LineJudgment(41, 2, "Cửu Nhị", "象⽈:已事遄往,尚合志也. Dịch âm. - Tượng viết: Dĩ sự, chuyên vãng, thượng hợp chí dã. Dịch nghĩa. - Lời Tượng nói rằng: Xong việc mau đi, chuộng[4] hợp chí vậy. GIẢI NGHĨA Truyện của Trình Di. - Cái mà trong đời chuốc dừng là “chuộng”. Điều mà hào Đầu vẫn chuộng, là sự hợp chí với người trên, hào Tư nhờ về hào Đầu, hào Đầu làm ích cho hào Tư, đó là hợp chí với người trên.Bản nghĩa của Chu Hy. - Chữ 尚 (thượng là chuộng) thông với chữ 上 (thượng là trên). LỜI KINH 九⼆: 利貞,征凶,弗损,益之.", "Lợi trinh, chinh hung! Phất tổn, ích chi.", "Hào Chín Hai: Lợi về chính bền, đi thì hung! Chớ bớt, thêm đấy!", 643, null));
        list.add(new LineJudgment(41, 3, "Lục Tam", "參⽈:九⼆利貞,中以為志也. Dịch âm. - Tượng viết: Cửu nhị lợi trinh, trung dĩ vi chí dã. Dịch nghĩa. - Lời Tượng nói rằng: Hào Chín Hai lợi về chính bền, giữa lấylàm chí vậy. GIẢI NGHĨA Truyện của Trình Di. - Hào Chín ở ngôi Hai, không phải chỗ chính, đứng vào thể “đẹp lòng” không phái là cứng nhưng được chỗ giữa là hay. Nếu mà giữ được đức “giữa” thì có điều gì không hay? Há có lẽ nào giữa mà không chính? Há có lẽ nào giữa mà thá quá? Hào Hai gọi là lợi về chính bền, nghĩa là lấy mực giữa làm chi vậy. Chỉ ở mực giữa, thì tự nhiên phải chính. Đại để giữa trọng hơn chính, giữa thì chính rồi, chính thì chưa ắt đã giữa. Có thể giữ được mực giữa, thì là lợi ích cho người trên. LỜI KINH 六三:三⼈⾏則损⼀⼈,⼀⼈作則得其友.", "Tam nhân hành tắc tổn nhất nhân, nhất nhân hành tắc đắc kỳ hữu.", "Hào Sáu Ba: Ba người đi thì tổn một người, một người đi thì được thửa bạn.", 644, null));
        list.add(new LineJudgment(41, 4, "Lục Tứ", "六四:損其疾,使遄有喜,元吉,無啓.", "Tổn tôn, sử xuyền hữu hỷ, nguyên cắt, vô cữu.", "Hào Sáu Tư: Bớt thửa tật, khiến chóng có mừng, cả tốt, không lỗi.", 646, null));
        list.add(new LineJudgment(41, 5, "Lục Ngũ", "象⽈:损其疾,亦可喜也Dịch âm. - Tượng viết: Tổn kỳ tật, diệc khả hỷ dã. Dịch nghĩa. - Lời Tượng nói rằng: Bớt thửa tật, cũng đáng mừng vậy, GIẢI NGHĨA Truyện của Trình Di. - Bớt cái tật đi, vẫn là đáng mừng, nói rằng “cũng” đó chỉ là tiếng phát ngữ mà thôi. LỜI KINH 六五:或益之⼗朋之悉,弗克違,元吉", "Hoặc ích chi thập bằng chi quy, phất khắc vi, nguyên cát.", "Hào Sáu Năm: Hoặc ích cho đấy, chưng con rùa mười “bằng”[6] chẳng hay trái, cả tốt!", 647, null));
        list.add(new LineJudgment(41, 6, "Thượng Cửu", "象⽈:六五元吉,⾃上祐也 Dịch âm. - Tượng viết: Lục Ngũ: nguyên cát, tự thượng hựu dã. Dịch nghĩa. - Lời Tượng nói rằng: Hào Sáu Năm cả tốt, tự trên phù hộ vậy. GIẢI NGHĨA Truyện của Trình Di. - Sở dĩ được cả tốt, là vì có thể hợp hết ý kiến của nhiều người, hợp với lẽ của trời đất, cho nên tự trời ban phúc cho vậy. LỜI KINH 上九:弗损,益之無咎,貞吉,利肴攸往,得⾂無彖", "Phất tổn, ích chi, vô cữu, trinh cát, lợi hữu du vãng, đắc thần vô gia.", "Hào Chín Trên: Chẳng bớt, thêm đấy, không lỗi, chính bền tốt, lợi có thửa đi, được bề tôi không nhà.", 649, null));

        // Que 42 (ÍCH)
        list.add(new LineJudgment(42, 1, "Sơ Cửu", "初九:利⽤為⼤作,元吉,無啓.", "Lợi dụng vi đại tác, nguyên cát, vô cữu.", "Hào Chín Đầu: Lợi dùng làm việc lớn, cả tốt, không lỗi.", 657, null));
        list.add(new LineJudgment(42, 2, "Lục Nhị", "象⽈:元吉無咎,下不厚事也.Dịch âm. - Tượng viết: Nguyên cát vô cữu, hạ bất hậu, sự dã. Dịch nghĩa. - Lời Tượng nói rằng: Cả tốt không lỗi, kẻ dưới chẳng được dầy vậy. GIẢI NGHĨA Truyện của Trình Di. - Kẻ ở dưới vốn không xử được dầy, việc dầy tức là việc nặng lớn vậy - vì bị người trên dùng mình, cho nên phải gánh việc lớn, ắt phải làm cho xong việc của Người mà đem lại sự cả tốt, mới là không lỗi. Đem lại được sự cả tốt thì kẻ ở trên dùng mình là biết người, mình đương vào đó là làm nổi trách nhiệm. Nếu không thể thì trên dưới đều có lỗi. Bản nghĩa của Chu Hy. - Nó vốn không phải gánh vác việc to, cho nên hễ không như thế, thì không lấp được tội lỗi. LỜI KINH 六⼆:或益之⼗朋之悉,弗克違 永貞,吉,王⽤亨于帝,吉.", "Hoặc ích chi thập bằng chi qui, phất khắc vi vĩnh trinh cát, vương dụng hưởng vu đế, cát!", "Hào Sáu Hai: Hoặc ích đấy, chưng rùa mười bằng[3] chẳng hay trái, vĩnh viễn chính bền, tốt, vua dùng hưởng chưng trời, tốt!", 658, null));
        list.add(new LineJudgment(42, 3, "Lục Tam", "象⽈:或益之,⾃外來也. Dịch âm. - Tượng viết: Hoặc ích chi, tự ngoại lai dã. Dịch nghĩa. - Lời Tượng nói rằng: Hoặc ích đấy, tự ngoài đến vậy.GIẢI NGHĨA Truyện của Trình Di. - Đã trung chính rỗng giữa, biết nhân điều thiện của thiên hạ mà giữ cho Bền, thì có việc có ích, mọi người sẽ tự ngoài đến làm ích cho mình. Hoặc có người nói: “Từ ngoài đến” có phải là hào Năm chăng? Đáp rằng: “Trung chính rỗng giữa như hào Hai, thiên hạ ai không thuận theo mà làm ích cho nó? Hào Năm là chính ứng của nó, cố nhiên cũng phải ở trong đám ấy. LỜI KINH 六三:益之,⽤凶事,無咎,有孚,中⾏⽤告公⽤圭.", "Ích chi, dụng hung sự, vô cữu, hữu phu, trung hàng, cáo công dụng khuê.", "Hào Sáu Ba: Ích đây, dùng việc hung, không lỗi, có tin, đường giữa, bảo tước. Công dùng ngọc khuê.", 660, null));
        list.add(new LineJudgment(42, 4, "Lục Tứ", "象⽈:益⽤凶事,固有之也. Dịch âm. - Tượng viết: Ích dụng hung sự, cố hữu chi dã. Dịch nghĩa. - Lời Tượng nói rằng: Ích dùng việc hung, cố có đây vậy. GIẢI NGHĨA Truyện của Trình Di. - Hào Sáu Ba “ích đây” mà chỉ có thể dùng vào việcchung, vì nó cố nhận là có, nghĩa là chuyên cố tự gánh lấy việc vậy. Kẻ ở dưới nên phải bẩm vâng người trên, thế mà tự tiện làm việc, thì chỉ cứu sự hung tai của dân, chữa sự nguy cấp của đời là được. Đó là lẽ quyền nghi trong khi gặp chuyện cấp nạn, biến cố cho nên mới được không lỗi. Nếu là hình thi, thì không thể thế. Bản nghĩa của Chu Hy. - Ích dùng việc hung, là muốn mệt lòng nhược trí, cố giữ cho có vậy. LỜI KINH 六四:中⾏,告公從,利⽤為依,遷國.", "Trung hành, cáp công tòng, lợi dụng vi y thiên quốc.", "Hào Sáu Tư: Đường giữa, tâu tước công theo, lợi dụng làm tựa, dời nước.", 662, null));
        list.add(new LineJudgment(42, 5, "Cửu Ngũ", "象⽈:告公從,以益志也. Dịch âm. - Tượng viết: Cáo công tòng, dĩ ích chí dã. Dịch nghĩa. - Lời Tượng nói rằng: “Tâu tước Công, theo lấy chí làm ích vậy”. GIẢI NGHĨA Truyện của Trình Di. - Lời hào chỉ nói: “Được đường giữa thì tâu tước Công sẽ được nghe theo”, lời Tượng lại tỏ thêm rằng: “Tâu tước Công mà được nghe theo là tại bảo họ lẩy cái chí làm ích cho kẻ dưới”. Nếu mà chí ở làm ích cho thiên hạ, thì người trên ắt tin mà theo. Kẻ thờ vua chẳng lo người trên không theo mình, chỉ lo chí mình không được thành thực mà thôi. LỜI KINH 九五:有孚,惠⼼,勿問,元吉,有⼿,惠我德.", "Hữa phu, huệ tâm, vật vấn, nguyên cắt, hữu phu, huệ ngã đức.", "Hào Chín Năm: Có tin lòng ơn, chớ hỏi, cả tốt, có tin, ơn đức ta.GIẢI NGHĨA Truyện của Trình Di. - Hào Năm là bậc Dương cương trung chính, ở ngôi tôn, lại được hào Sáu Hai là kẻ trung chính, ứng nhau với nó, để thi hành cái chí của nó, thì còn cái gì không lợi? Lấy chất Dương đặc ở giữa là Tượng “có tin”. Lấy đức, tài và ngôi của hào Chín Năm mà trong lòng chí thành về làm ơn làm ích cho người, thì sự rất hay, cả tốt của nó, chẳng hỏi cũng có thể biết, cho nên nói rằng “chớ hỏi cả tốt”. Kẻ làm vua ở ngôi làm được, cầm quyền làm được, nếu chí thành làm ích cho thiên hạ, thiên hạ được chịu phúc lớn của nó, không cần phải nói. “Có tin, ơn đức ta” nghĩa là kẻ làm vua chí thành làm ích cho thiên hạ, thì người thiên hạ ai cũng chí thành yên đội, lấy đức trạch của vua làm ơn huệ vậy. Bản nghĩa của Chu Hy. - Người trên có đức tin để làm ơn cho kẻ dưới, kẻ dưới cũng có đức tin để làm ơn cho người trên, không hỏi cũng biết cả tốt.", 663, null));
        list.add(new LineJudgment(42, 6, "Thượng Cửu", "象⽈:有孚惠⼼,勿問之矣.惠我德,⼤得志也. Dịch âm. - Tượng viết: Hữu phu huệ tâm, vật vấn chi kỹ: huệ ngã đức, đại đắc chí dã. Dịch nghĩa. - Lời Tượng nói rằng: Có tin, ơn lòng, chớ hỏi đấy vậy, ơn đức ta, cả được chí vậy. GIẢI NGHĨA Truyện của Trình Di. - Kẻ làm vua có lòng chí thành, làm điều ơn ích cho thiên hạ, thì sự cả tốt của hắn không cần phải nói, cho nên nói rằng: “Chớ hỏi đây vậy”. Thiên hạ chí thạnh nhớ đức ta để làm nên, đó là đạo của mình cả thực hành, thế chí của kẻ làm vua được toại vậy.LỜI KINH 上九: 莫益之, 或擊之, ⽴新勿恆,凶", "Mạc ích chi, hoặc kích chi, lập tâm vật hằng, hung!", "Hào Chín Trên: Chẳng ích nó, hoặc đánh nó, lập tâm chớ thường hung!", 665, null));

        // Que 43 (QUẢI)
        list.add(new LineJudgment(43, 1, "Sơ Cửu", "居 (cư) trong câu 奇货可居(kỳ hóa khả cư - của lạ đáng chứa) ở Liệt truyện vậy. Hạng Bình Âm nói rằng: Chữ 居 (cư) chua nghĩa là chứa, nhưng chữ 化居 (hóa cư) trong Kinh Thư, chữ 居業 (cư nghiệp) trong Kinh Dịch, đều thế cả. Người đời Hán hãy còn nói tiếng cư tích (ở chứa). Hồ Vân Phong nói rằng: Câu “cư đức tắc kỵ”. Trình truyện giải tắc là ước, kỵ là ngừa, cho là ước dựng ngừa ngăn, thì trái với ý vỡ lở. Vương Bật đổi là 明則 (minh tắc) cũng sai. Các nhà cho là “ngừng đậu đức mình thì kiêng” thì là trái lại ý trên, mà ở Đại tượng không có lệ nói trái lại, sách Bản nghĩachừa lại chỗ đó là phải. LỜI KINH 初九:壯于前趾,往不勝,為咎.", "Tráng vu tiền chỉ, vãng bất thắng, vi cữu.", "Hào Chín Đầu: Mạnh chưng ngón chân trước, đi thẳng được, là lỗi.", 674, null));
        list.add(new LineJudgment(43, 2, "Cửu Nhị", "象⽈:不勝⽽往,咎也. Dịch âm. - Tượng viết: Bất thắng nhi vãng, cữu da. Dịch nghĩa. - Lời Tượng nói rằng: Chẳng được mà đi, là lỗi vậy.GIẢI NGHĨA Truyện của Trình Di. - Người ta làm việc, ắt phải cân nhắc việc đó có thể làm rồi mới quyết, thì không có lỗi, Lý không thể thắng mà hãy cứ đi, đủ biết là lỗi. Hễ làm việc mà có lỗi, đều do quyết quá. LỜI KINH 九⼆:惕號,莫表弯, 勿恤.", "Dịch hào, mộ dạ hữu nhung, vật tuất", "Hào Chín Hai: Sợ kêu, đêm hôm có quân, chớ ngại.", 675, null));
        list.add(new LineJudgment(43, 3, "Cửu Tam", "象⽈:有戎勿恤,得中道冬. Dịch âm. - Tượng viết: Hữu nhung, vật tuất, đắc trung đạo dã. Dịch nghĩa. - Lời Tượng nói rằng: Có quân, chớ ngại, được đạo vậy.GIẢI NGHĨA Truyện của Trình Di. - Đêm hôm nay vó việc binh nhung, là đáng sợ lắm. Nhưng mà có thể không ngại, là vì nó khéo tự xử. Đã được đạo giữa, lại biết sợ hãi và có ngăn ngừa, thì còn việc gì đáng ngại? Hào Chín ở ngôi Hai, tuy được giữa mà không chính, nó được rất hay, là sao? Đáp rằng: Dương quyết với Âm, quân tử quyết với tiểu nhân mà được giữa, há lại có sự bất chính? Biết thời, biết thế, đó là phượng pháp lớn trong việc học Dịch. LỜI KINH 九三:壯于鳩, 有凶,君⼦夬夬,獨⾏遇⾬,若濡,有溫, 無砵.", "Tráng vu cưu, hữu hung, quân tử quải quải, độc hành ngộ vũ, nhược nhu, hữu uấn, vô cữu.", "Hào Chín Ba: Mạnh chưng gồ má, có sự hung, đấng quân tử quyết quyết, đi một mình, gặp mưa, đường ướt, có giận, không lỗi.", 676, null));
        list.add(new LineJudgment(43, 4, "Cửu Tứ", "象⽈:君⼦夬夬,終無咎也. Dịch âm. - Tượng viết: Quân tử quải quải, chung vô cữu dã. Dịch nghĩa. - Lời Tượng nói rằng: Đấng quân tử quyết quyết, chót không lỗi vậy. GIẢI NGHĨA Truyện của Trình Di. - Vướng mắc về sự yêu riêng, chỉ vì không quyết, quân tử ở liền với nghĩa, quả quyết về đáng quyết, cho nên về sau không đếncó lỗi. LỜI KINH ⼠四:臀無廣, 其⾏次且,牵⽺,悔亡,聞⾔不信.", "Điêu vô phu, kỳ hành từ thư, khiên dương, hối vong, văn ngôn bất tín.", "Hào Chin Tư: Đít không da, thửa đi chật vật, dắt dê, ăn năn mất, nghe nói chẳng tin.", 678, null));
        list.add(new LineJudgment(43, 5, "Cửu Ngũ", "象⽈:其⾏次且,位不當也;聞⾔不信,聰不明也. Dịch âm. - Tượng viết: Kỳ hành từ thư, vị bất đáng dã, văn ngôn bất tín, thông bất minh dã. Dịch nghĩa. - Lời Tượng nói rằng: Thửa đi chật vật, ngôi chẳng đáng vậy, nghe nói chẳng tin, sự nghe chẳng sáng vậy. GIẢI NGHĨA Truyện của Trình Di. - Hào Chín ở ngôi Âm, là ngôi chẳng đáng. Lấy chất Dương ở ngôi mềm, mất sự cương quyết, không thể gượng tiến, cho nên sự của nó chật vật. Kẻ cứng mới có thể sáng, ở ngôi mềm thì rời mất cái chính tính rồi, há lại sáng được? Cho nên nghe nói mà không biết tin, là vì sự nghe của nó không được sáng vậy. LỜI KINH 九五:筧奚夬夬,中⾏無咎.", "Nghiến lục quải quải, trung hàng vô cữu.", "Hào Chín Năm: Rau sam quyết quyết, đường giữa không lỗi.", 679, null));
        list.add(new LineJudgment(43, 6, "Thượng Lục", "上六:無號,終有凶.", "Vô hào, chung hữu hung.", "Hào Sáu Trên: Không kêu, sau chót có hung.", 681, null));

        // Que 44 (CẤU)
        list.add(new LineJudgment(44, 1, "Sơ Lục", "初六:于⾦柅,貞吉,有攸往,⾒凶,⾗孚蹢獨.", "Hệ vu kim nỷ, trính cát, hữu du vãng, kiến hung, luy thỉ phu chích chúc.", "Hào Sáu Đầu: Buộc chưng neo sắt, chính tốt, có thửa đi, thấy hung, con lợn còm tin nhảy nhót.", 688, null));
        list.add(new LineJudgment(44, 2, "Cửu Nhị", "象⽈: 于命柅, 柔遇牵也 Dịch âm. - Tượng viết: Hệ vu kim nỷ, nhu đạo khiên dã. Dịch nghĩa. - Lời Tượng nói rằng: Buộc chưng neo sắt, đạo mềm kéo vậy. GIẢI NGHĨA Truyện của Trình Di. - Kéo là dắt cho tiến lên. Khí Âm mới sinh mà tiến dần, tức là đạo mềm đương được dắt kéo. Buộc vào neo sắt, là để ngăn cản sự tiến của nó, không cho nó tiến, thì nó không thể làm tiêu chính đạo, mới là chính tốt.Bản nghĩa cua Chu Hy. - Kéo là tiến lên. Vì nó tiến lên, cho nên ngăn lại. LỜI KINH 九⼆:包有枣,無咎,不利賓.", "Bao hữu ngư, vô cữu, bất lợi tân.", "Hào Chín Hai: Bọc có cá, không lỗi chẳng lợi khách.", 690, null));
        list.add(new LineJudgment(44, 3, "Cửu Tam", "象⽈:包有⿂,義不及賓也. Dịch âm. - Tượng viết: Bao hữư ngư, nghĩa bất cập tân dã. Dịch nghĩa. - Lời Tượng nói rằng: Bọc có cá, nghĩa chẳng kịp khách vậy. GIẢI NGHĨA Truyện của Trình Di. - Hào Hai gặp hào Đầu, không thể để nó hai lòng với người khác, nên như bọc gói có cá. Cá trong bọc gói, nghĩa không đến phần khách khứa. LỜI KINH 九三:臀無膚,其⾏次且,厲,無⼤咎.", "Điến vô phu, kỳ hành từ thư, lệ! Vô đại cữu.", "Hào Chín Ba: Đít không da, thửa đi chật vật, nguy! Không lỗi lớn.", 691, null));
        list.add(new LineJudgment(44, 4, "Cửu Tứ", "象⽈:其⾏次且,⾏未牵也. Dịch âm. - Tượng viết: Kỳ hành từ thư, hành vị khiên dã. Dịch nghĩa. - Lời Tượng nói rằng: Thửa đi chật vật, đi chưa kéo vậy. GIẢI NGHĨA Truyện của Trình Di. - Lúc đầu chí nó cầu gặp hào Đầu, cho nên sự đi chầm chậm. “Chưa kéo” nghĩa là không giục sự đi của mình. Đă biết là nguy mà đổi lại, cho nên không đến lỗi lớn. LỜI KINH 九四:包無⿂,起蛛凶", "Bao vô ngư, khởi hung. Dịch âm. -", "Hào Chín Tư: Bọc không cá, dấy hung.", 692, null));
        list.add(new LineJudgment(44, 5, "Cửu Ngũ", "象⽈:無⿂之凶,遠民也. Dịch âm. - Tượng viết: Vô ngư chi hung, viễn dân dã. Dịch nghĩa. - Lời Tượng nói rằng: Cái hung của sự - không cá, vì xa dân vậy. GIẢI NGHĨA Truyện của Trình Di. - Kẻ dưới lìa bỏ, là do ở mình làm ra, xa dân là mình xa họ, tức là kẻ làm người trên có cái khiến cho họ lìa. Bản nghĩa của Chu Hy. - Dân họ xa mình, cũng như là mình xa họ. LỜI KINH 九五:以杞包⽠,含章,有隕⾃天.", "Dĩ kỷ bảo qua, hàm chương, hữu vẫn tự thiên,", "Hào Chín Năm: lấy cây kỷ bọc quả dưa, ngậm văn vẻ, có sa tự trời.", 693, null));
        list.add(new LineJudgment(44, 6, "Thượng Cửu", "象⽈:九五含章,中正也,有隕⾃天,志不舍命也.Dịch âm. - Tượng viết: Cửu Ngũ hàm chương, trung chính dã, hữu vẫn tự thiên, chí bất xả mệnh dã. Dịch nghĩa. - Lời Tượng nói rằng: Hào Chín Năm ngậm văn vẻ, giữa chính vậy, có sa tự trời, chí chẳng bỏ mệnh vậy. GIẢI NGHĨA Truyện của Trình Di. - “Mệnh” là lẽ trời, “bỏ” tức là trái. Chí thành trung chính, uấn mình để tìm người hiền, chí muốn hợp với lẽ trời, vì vậy mới “có sa tự trời”, nghĩa là ắt được cái người mình tìm. LỜI KINH ⼟九:垢其⾓,吝,無咎.", "Cầu kỳ giốc, lận, vô cữu.", "Hào Chín Trên: Gặp thửa sừng, đáng tiếc, không lỗi.", 695, null));

        // Que 45 (TỤY)
        list.add(new LineJudgment(45, 1, "Sơ Cửu", "初九:有孚,不終,乃亂,乃萃若號,⼀握為笑,勿恤,往無晷.", "Hữu phu, bất chung, nãi loạn, nãi tụy, nhược hào, nhấtác vi tiếu, vật tuất, vãng vô cữu.", "Hào Chín Đầu: Có tin, không chót, bèn loạn, bèn họp, bằng kêu, một nắm làm cười, chớ lo, đi không lỗi.", 703, null));
        list.add(new LineJudgment(45, 2, "Lục Nhị", "象⽈:乃亂,乃萃,其志亂也. Dịch âm. - Tượng viết: Nãi loạn, nãi tụy, kỳ chí loạn dã. Dịch nghĩa. - Lời Tượng nói rằng: Bèn loạn, bèn họp, thửa chí loạn vậy. GIẢI NGHĨA Truyện của Trình Di. - Tâm chí nó bị kẻ đồng loại làm cho mê loạn, chonên nó bèn họp với các hào Âm. Không thể cầm chắc sự thao thủ của mình, thì kẻ tiểu nhân làm cho mê loạn, mà mất chính đạo vậy. LỜI KINH 六⼆:引吉,無咎,孚乃利,⽤褕.", "Dẫn cát, vô cữu, phu nãi lợi, dụng Thược.", "Hào Sáu Hai: Dẫn tốt, không lỗi, tin bèn lời, dùng tế Thược.", 705, null));
        list.add(new LineJudgment(45, 3, "Lục Tam", "象⽈:引⼠無咎,中未變也. Dịch âm. - Tượng viết: Dẫn cát, vô cữu, trung vị biến dã. Dịch nghĩa. - Lời Tượng nói rằng: Dẫn tốt, không lỗi, giữa chưa đổi vậy. GIẢI NGHĨA Truyện của Trình Di. - Trong thì họp, lấy sự được họp làm tốt, cho nên hào Chín Tư là được trên dưới sum họp; hào Hai với hào Năm tuy là chính ứng,nhưng ở khác chỗ và có ngăn cách, ấy là dương thì họp mà chưa được họp, cho nên có thể dẫn nhau mà họp thì tốt mà không lỗi, vì nó có đức giữa chính mà chưa vội thay đổi, nếu thay đổi thì nó không cần nhau nữa. LỜI KINH 六三:萃如,嗟如,無攸利,往無咎,⼩吝.", "Tụy như, tư như, vô du lợi, vãng vô cữu, tiểu lận.", "Hào Sáu Ba: Dường họp vậy, dường than vậy không thửa lợi, đi không lỗi, hơi tiếc.", 707, null));
        list.add(new LineJudgment(45, 4, "Cửu Tứ", "象⽈:往無吝,上巽也. Dịch âm. - Tượng viết: Vãng vô cữu, thượng tốn dã. Dịch nghĩa. - Lời Tượng nói rằng: Đi không lỗi, trên nhún vậy. GIẢI NGHĨA Truyện của Trình Di. - Hào Trên ở chỗ cùng tột của sự mềm và đẹp lòng, hào Ba đi mà không lỗi, là vì hào Trên nhún thuận mà nhận nó vậy. LỜI KINH 九四:⼤吉無咎.", "Đại cát, vô cữu.", "Hào Chín Tư: Cả tốt, không lỗi.", 708, null));
        list.add(new LineJudgment(45, 5, "Cửu Ngũ", "象⽈:⼤吉無咎,位不當也. Dịch âm. - Tượng viết: Đại cát, vô cữu, vị bất đáng dã. Dịch nghĩa. - Lời Tượng nói rằng: Cả tốt không lỗi, ngôi chẳng đáng vậy. GIẢI NGHĨA Truyện của Trình Di. - Vì là ngôi nó không đáng, ngờ điều nó làm chưa chắc phải cả, cho nên răn rằng: “Ắt được cả tốt, nói sau mới là không lỗi” LỜI KINH 九五:苹有位,無咎匪孚,元永貞,悔亡.", "Tụy hữu vị, vô cữu, phỉ phu, nguyên vĩnh trinh hối vong.", "Hào Chín Năm: Họp có ngói, không lỗi, chẳng tin, cả, dài, chính, ăn năn mất.", 709, null));
        list.add(new LineJudgment(45, 6, "Thượng Lục", "象⽈:萃有位,志未光也. Dịch âm.- Tượng viết: Tụy hữu vị, chí vị quan dã. Dịch nghĩa. - Tượng nói rằng: họp có ngôi, chí chưa tỏ vậy.GIẢI NGHĨA Truyện của Trình Di. - Lời tượng nhắc lại câu trên của lời hào. Chí kẻ làm vua ắt muốn làm tín tỏ với thiên hạ, có cảm ắt thong, những loại có sống ắt đều mến về. Nếu còn có kẻ chưa tin, ấy là chí mình chưa được sáng lớn vậy. Bản nghĩa của Chu Hy. - Chưa tỏ chỉ về kẻ chẳng tin. LỜI KINH 上九:賫咨,涕洟 無咎.", "Tê tư, thế di, vô cữu.", "Háo Sáu Trên: Than thở, nước mắt, nước mũi, không lỗi.", 711, null));

        // Que 46 (THĂNG)
        list.add(new LineJudgment(46, 1, "Sơ Lục", "順 (thuận) chép làm chữ 慎(thận), ý càng rõ ràng. Đó là cổ văn hai chữ vẫn thong dụng. Thuyết đó đã thấy ở quẻ Mông thiên trên. LỜI KINH 初六:允升,⼤吉.", "Doãn thăng, đại cát.", "Hào Sáu Đầu: Tin lên, cả tốt.", 716, null));
        list.add(new LineJudgment(46, 2, "Cửu Nhị", "象⽈: 允升⼤吉上合志也. Dịch âm.- Tượng viết: Doãn thăng đại cát, thượng hợp chí dã. Dịch nghĩa. - Lời Tượng nói rằng: Tin lên cả tốt, trên hợp chí vậy. GIẢI NGHĨA Truyện của Trình Di. - Tức là cùng kẻ ở trên họp chí cùng lên Trên chỉ vào hào Chín Hai, theo hào Hai mà lên, tức là cùng chí với hào Hai. Vì biết tin theo người hiền mà có đức cứng giữa, cho nên cả tốt. LỜI KINH 九⼆:孚乃利,⽤鑰,無咎.", "Phu nãi lợi, dụng Thược, vô cữu.", "Hào Chín Hai: Tin bèn lợi, dùng tế Thược, không lỗi.", 718, null));
        list.add(new LineJudgment(46, 3, "Cửu Tam", "象⽈: 往無,咎上巽也. Dịch âm.- Tượng viết: Cửu Nhị chi phu, hữu hỷ dã. Dịch nghĩa. - Lời Tượng nói rằng: Sự tin của hào Chín Hai, có mừng vậy.GIẢI NGHĨA Bản nghĩa của Chu Hy. - Hào Hai biết lấy sự tín mà thờ người trên, thì chẳng những về đạo làm tôi không lỗi mà thôi, lại còn có thể thi hành được đạo cứng giữa, ơn tới thiên hạ, thế là có mừng. LỜI KINH 九三:升虛⾢.", "Thăng hư ấp.", "Hào Chín Ba: Lên làng trống không.", 719, null));
        list.add(new LineJudgment(46, 4, "Lục Tứ", "象⽈: 升虛⾢,無所疑也. Dịch âm.- Tượng viết: Thăng hư ấp, vô sở nghi dã. Dịch nghĩa. - Lời Tượng nói rằng: lên làng trống không, không thửa ngờ vậy. GIẢI NGHĨATruyện của Trình Di. - Vào làng không người, sự tiến không còn nghi ngờ trở ngại gì nữa. LỜI KINH 六四:王⽤亨于岐⼭,吉,無咎.", "Vượng dụng hưởng[2] vu Kỳ Sơn, cát, vô cữu.", "Hào Sáu Tư: Vua dùng hưởng ở núi Kỳ, tốt, không lỗi.", 720, null));
        list.add(new LineJudgment(46, 5, "Lục Ngũ", "享 (hưởng). “Vua hưởng ở núi Kỳ” với “vua dùng hưởng ở núi tây”, chỉ là nói việc tế núi sông. LỜI KINH 象⽈: 王⽤亨于岐, 順事也. Dịch âm.- Tượng viết: Vương dụng hưởng vu Kỳ Sơn, thuận sự dã.Dịch nghĩa. - Lời tượng nói rằng: Vua dùng hưởng chưng núi Kỳ, việc thuận này. GIẢI NGHĨA Truyện của Trình Di. - Hào tư ở ngôi gần vua, đương thì lên, được tốt mà không lỗi, là vì ở đức thuận, lấy chất mềm ở thể Khôn, thuận đến tột cùng vậy. Vua Văn được hanh thông ở núi Kỳ, cũng vì thuận thì mà thôi. Trên thuận với người trên, dưới thuận với người dưới, mình thì thuận với nghĩa của mình, cho nên gọi là việc thuận. Bản nghĩa của Chu Hy. - Cứ thuận mà lên, là Tượng lên tế ở núi. LỜI KINH 六五:貞吉,升階.", "Trinh cát, thăng giai.", "Hào Sáu Năm: Chính bền, tốt, lên thềm[3].", 721, null));
        list.add(new LineJudgment(46, 6, "Thượng Lục", "象⽈: 貞吉,升階, ⼤得志也. Dịch âm.- Tượng viết: Trinh cát, thăng giai, đại đắc chí dã. Dịch nghĩa. - Lời tượng nói rằng: Chính bền, tốt lên thềm, cả được chí vậy. GIẢI NGHĨA Truyện của Trình Di. - Tựa dùng kẻ hiền tài mà có thể chính, bền, như thé mà lên, có thể đưa thên hạ đến cuộc đại trị chí mình cả được thỏa vậy. Cuộc lên của đạo làm vua, chỉ lo không có người hiền tài giúp đỡ, thì cũng giống như tự thềm mà lên vậy. LỜI KINH 上六:冥升,利于不息之升.", "Minh thăng, lợi vu bất tức chi trinh.", "Hào Sáu Trên: Tối lên, lợi về sự chính bền chẳng nghĩ.", 722, null));

        // Que 47 (KHỐN)
        list.add(new LineJudgment(47, 1, "Sơ Lục", "初六:臀困于株⽊,⼊于幽⾕,三歲不覿.", "Điến khốn vu châu mộc, nhập vu u cốc, tam tuế bất thục.", "Hào Sáu Đầu: Đít khốn chưng trồi cây, vào chưng hang tối, ba năm chẳng thấy.", 728, null));
        list.add(new LineJudgment(47, 2, "Cửu Nhị", "象⽈:⼊于幽⾕,幽不明也Dịch âm.- Tượng viết: Nhập vu u cốc, u bất minh dã. Dịch nghĩa. - Lời Tượng nói rằng: Vào chưng hang tối, tối chẳng sáng vậy. GIẢI NGHĨA Truyện của Trình Di. - Tối chẳng sáng là càng vào chỗ tối tăm, tự hãm vào nơi sâu khốn vậy. Nếu sáng thì không đến nỗi hãm. LỜI KINH 九⼆:困于酒⾷,朱敝⽅來,利⽤亨祀,征凶,無咎.", "Khốn vu tửu tửu thực, chu phất phương lai, lợi dụng hưởng tự, chính hung, vô cữu.", "Hào Chín Hai: Khốn chưng rượu cơm, cái phất đỏ đương lại, lợi dùng cúng tế, đi hung không lỗi.", 729, null));
        list.add(new LineJudgment(47, 3, "Lục Tam", "九⼆:困于酒⾷,中有慶也. Dịch âm.- Tượng viết: Khốn vu tửu thực, trung hữu khánh dã. Dịch nghĩa. - Lời Tượng nói rằng: Khốn chưng rượu cơm, giữa có phúc vậy. GIẢI NGHĨA Truyện của Trình Di. - Tuy bị khốn về cái mình muốn, chưa thể ra ân chongười, nhưng giữ được đức cứng giữa, ắt có thể đem lại sự hanh thông mà có phúc khánh. Dù cho thì chưa hanh thông, mà mình giữ được đức giữa, cũng là đạo đấng quân tử, thế là có phúc. LỜI KINH 六三:困于⽯,據于蒺藜,⼊于其宫,不⾒其妻,凶.", "Khốn vu thạch, cứ vu tật lệ, nhập vu kỳ cung, bất kiến thê, hung.", "Hào Sáu Ba: Khốn chưng đá, vin chưng cây cà gai, vào chưng thửa buồng, chẳng thấy thửa vợ, hung.", 731, null));
        list.add(new LineJudgment(47, 4, "Cửu Tứ", "象⽈: 據于蒺藜, 承剛也,⼊于其宫,不⾒其妻,不祥也. Dịch âm.- Tượng viết: Cứ vu tật lê, thừa cương dã, nhập vu kỳ cung, bất kiến kỳ thê, bất tường dã. Dịch nghĩa. - Lời Tượng nói rằng: Vịn chưng cà gai, cưỡi cứng vậy, vào chưa thửa buồng, chẳng thấy thửa vợ, chẳng lành vậy. GIẢI NGHĨA Truyện của Trình Di. - Vịn chưng cây cà gai, ý nói cưỡi hào Chín Hai là hào cứng, sự không yên như thể tựa vào gai vậy. Chẳng lành là điềm chẳng hay. Mất chỗ yên ổn, tức là hiệu quả chẳng hay, cho nên nói rằng: “chẳng thấy thửa vợ, chẳng lành vậy”. LỜI KINH 九四:來徐徐,困于⾦⾞,吝,有終", "Lai từ từ, khốn vu kim xa, lận hữu chung.", "Hào Chín Tư: Lại thong thả, khốn chưng xe sắt, đáng tiếc! có chót.", 732, null));
        list.add(new LineJudgment(47, 5, "Cửu Ngũ", "象⽈: 來徐徐,志在下也;雖不當位,有與也. Dịch âm.- Tượng viết: Lai từ từ, chí tại hạ dã: tuy bất đáng vị, hữu dữ dã. Dịch nghĩa. - Lời Tượng nói rằng: Lại thong thả, chí ở dưới vậy, tuy chẳng đáng ngôi, có kẻ cùng với vậy. GIẢI NGHĨA Truyện của Trình Di. - Hào Tư với hào Đầu mà cách hào Hai, chí nó cốt ở tìm xuống, cho nên nó mới thong thả mà lại, tuy nó ở không đáng ngôi, cũng là chưa hay, nhưng có chính ứng của nó chung cùng với nó, cho nên có chốt. LỜI KINH九五:劓刖,困于⾚敝,乃徐有説,利⽤祭祀.", "Ty ngoạt, khốn vu xích phất, nãi từ hữu duyệt, lợi dụng tế dự.", "Xẻo mũi, chặt chân, khốn chưng cái phất[5] đỏ, bèn thong thả có đẹp lòng, lợi dụng tế tự.", 734, null));
        list.add(new LineJudgment(47, 6, "Thượng Lục", "上九:困于葛藟,于跪脆,⽈: 動悔,有悔,征吉.", "Khốn vu cát lũy, vu nghiết ngột, viết: động hối, hữu hối, chính cát.", "Hào Sáu Trên: Khốn chưng cây sắn dây, nhưng cheo leo, rằng: động ăn năn, có ăn năn, đi tốt.", 736, null));

        // Que 48 (TỈNH)
        list.add(new LineJudgment(48, 1, "Sơ Lục", "初六: 井泥不⾷, 舊井⽆禽.", "Tỉnh nê bất thực, cựu tỉnh vô cầm Tỉnh mê bất thực, cựu tỉnh vô cầm.", "Hào Sáu Đầu: Giếng bùn chẳng ăn, giếng cũ không chim.", 744, null));
        list.add(new LineJudgment(48, 2, "Cửu Nhị", "象 ⽈: 井 不 ⾷, 下 也, 舊 井 無 禽 時 舍 也. Dịch âm. - Tượng viết: Tỉnh mê bất thực, hạ dã; cựu tỉnh vô cầm thì xả dã. Dịch nghĩa. – Lời Tượng nói rằng: Giếng bùn chẳng ăn, ở dưới vậy; giếngcũ không chim, thì bỏ vậy. GIẢI NGHĨA Truyện của Trinh Di. - Lấy chất Âm mà ở dưới giếng, là Tượng bùn vậy. Không có nước mà là bùn, người ta không ăn. Người khổng ăn thì nước không lên, không có cái gì kịp tới chim chóc, chim chóc cũng chẳng buồn đến nữa, chỗ đó đủ thấy nó không giúp cho các loài, bị đời bỏ đó không dùng. Bản nghĩa của Chu Hy. - Ý nói bị đời ruồng bỏ. LỜI KINH 九 ⼆: 井 ⾕, 射鲋, 甕敝 漏.", "Tỉnh cốc, xạ phụ, úng tệ lậu.", "Hào Chín Hai: Giếng hang, bắn loài ếch nhái[7], vò nát dò.", 745, null));
        list.add(new LineJudgment(48, 3, "Cửu Tam", "九 ⼆: 井 ⾕ 射 鲋, 無 與 也. Dịch âm. - Tượng viết: Tỉnh cốc, xạ phụ, vô dữ dã. Dịch nghĩa. - Lời Tượng nói rằng: Giếng hang, bắn ếch nhái, không cùng vậy. GIẢI NGHĨA Truyện của Trinh Di. - Cái giếng lấy sự chảy lên làm công, hào Hai là tài Dương cứng, vốn vẫn có thể nên dùng, vì nó ở dưới, mà phía trên không kẻ ứng viện, cho nên phải liền xuống dưới mà bắn vào ếch nhái. Nếu như phía trên có kẻ cùng với, thì sẽ kéo cho nó lên, mà làm nên công dụng của cái giếng vậy. LỜI KINH 九 三: 井 渫 不 ⾷, 為 我 ⼼ 惻, 可 ⽤ 汲, 王 明,并 受 其 福.", "Tỉnh điệp bất thực, vi ngã tâm trắc, khả dụng cấp, vương minh, tịnh thụ kỳ phúc", "Hào chín Ba: Giếng trong chẳng ăn, làm sự bùi ngùi cho lòng ta, khá dùng múc nước; vua sáng, cùng chịu thửa phúc.", 746, null));
        list.add(new LineJudgment(48, 4, "Lục Tứ", "象 ⽈: 井 渫 不 ⾷, ⾏ 測 也, 求 王 明, 受 福 也. Dịch âm. - Tượng viết: Tỉnh điệp bất thực, hành trắc dã, cầu minh vương, thụ phúc dã. Dịch nghĩa. - Lời Tượng nói rằng: Giếng trong chẳng ăn, kẻ đi bùi ngùi vậy: tìm vua sáng, cùng chịu phúc vậy. GIẢI NGHĨATruyện của Trình Di. - Giếng trong sạch mà không được người ta ăn đến, tức là người có tài trí mà không được dùng, lấy sự không được hành đạo làm điều lo lắng ngậm ngùi vậy. Đã lấy sự không được hành đạo làm điều lo lắng bùi ngùi, thì sao cho khỏi có sự cầu cạnh? Cho nên nó tìm vua sáng mà chịu phúc, là tại trí nó thiết tha về sự hành đạo vậy. Bản nghĩa của Chu Hy. - “Hành trắc” nghĩa là kẻ đi đường lấy làm bùi ngủi. LỜI KINH 六四: 井鹙, ⽆咎.", "Tỉnh thịu, vô cữu.", "Hào Sáu Tư: Giếng xây bờ, không lỗi.", 748, null));
        list.add(new LineJudgment(48, 5, "Cửu Ngũ", "象⽈: 井鹙⽆咎, 脩井也 Dịch âm. - Tượng viết: Tỉnh thỉu vô cữu, tu tỉnh dã. Dịch nghĩa. Lời Tượng nói rằng: Giếng xây dựng bờ không lỗi, sửa giếng vậy. GIẢI NGHĨA Truyện của Trình Di. - Xây bờ tức là sửa trị cho giếng, tuy là không thể làm lớn cái công giúp người, nhưng biết sửa trị, thì không phải bỏ, cho nên không lỗi. Chỉ được khỏi lỗi mà thôi. Nếu nó là Dương cương, thì không đến nỗi như thế. LỜI KINH 九五: 井冽, 寒泉⾷", "Tỉnh liệt, hàn toàn thực.", "Hào Chín Năm: Giếng mát, suối lạnh, ăn.", 749, null));
        list.add(new LineJudgment(48, 6, "Thượng Lục", "象⽈: 寒泉之⾷, 中正也. Dịch âm. - Tượng viết: Hàn tuyền chi thực, trung chính dã. Dịch nghĩa. - Lời Tượng nói rằng: Suối lạnh chưng ăn, giữa chính vậy. GIẢI NGHĨA Truyện của Trình Di. - Suối lạnh mà có thể ăn, là điều chí thiện trong đạo giếng. Hào Chín Năm có đức giữa chính, tức là cái nghĩa chí thiện vậy. LỜI KINH 上六: 井收, 勿幕, 有孚, 元吉.", "Tỉnh thu, vật mục, hữu phu, nguyên cát.", "Hào Sáu Trên: Giếng thu, chớ chùm, có tin, cả tốt.", 750, null));

        return List.copyOf(list);
    }
}
