package io.destinyos.calendar;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.LocalDateTime;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Solar-term resolution at an exact instant, and the honest size of its error.
 *
 * <p>Bát Tự needs the term at the birth instant, not at the start of the day
 * containing it — the two differ for every birth on a term day, which is
 * roughly one birth in fifteen. That makes the accuracy of the underlying solar
 * series a user-visible property rather than an internal detail, so it is
 * measured here rather than assumed.
 *
 * <p><strong>Published reference values used below</strong> (Beijing time,
 * UTC+8, from Purple Mountain Observatory-derived tables republished at
 * jieqi.bmcx.com and, for 2024, Vietnamese press reporting the 15:27 UTC+7
 * instant): Lập Xuân 1984 at 23:18:44, Lập Xuân 2024 at 16:27. Neither was
 * generated by this project's own code (CLAUDE.md §32).
 */
class SolarTermInstantTest {

    /**
     * The deviation this project accepts, and the number
     * {@code BaziEngine.SOLAR_TERM_GUARD_MINUTES} is set from. Meeus's
     * low-precision solar series omits nutation and aberration, which together
     * account for most of the gap; research item R19 records the option of
     * correcting for them.
     */
    private static final double DOCUMENTED_TOLERANCE_MINUTES = 40.0;

    @Test
    @DisplayName("The local-midnight and exact-instant term lookups agree at midnight")
    void midnightFormsAgree() {
        // termIndexAt existed first and is what the lunar calendar's golden
        // tests exercise. If the new instant-level form ever disagrees with it
        // at midnight, one of the two has drifted and every Bát Tự month pillar
        // silently inherits the drift.
        for (int month = 1; month <= 12; month++) {
            long dayNumber = JulianDay.fromDate(15, month, 1997);
            double julianDate = JulianDay.fromLocalDateTime(
                    LocalDateTime.of(1997, month, 15, 0, 0), 7.0);

            assertThat(SolarTerm.termIndexAtJulianDate(julianDate))
                    .as("term index for 1997-%02d-15", month)
                    .isEqualTo(SolarTerm.termIndexAt(dayNumber, 7.0));
        }
    }

    @Test
    @DisplayName("Lập Xuân 1984 falls between one hour before and one hour after 23:18:44 Beijing")
    void lapXuan1984BracketsThePublishedInstant() {
        assertThat(termAt(LocalDateTime.of(1984, 2, 4, 22, 18, 44), 8.0))
                .as("one hour before the published Lập Xuân instant")
                .isEqualTo(SolarTerm.DAI_HAN);
        assertThat(termAt(LocalDateTime.of(1984, 2, 5, 0, 18, 44), 8.0))
                .as("one hour after the published Lập Xuân instant")
                .isEqualTo(SolarTerm.LAP_XUAN);
    }

    @Test
    @DisplayName("Lập Xuân 2024 falls between one hour before and one hour after 16:27 Beijing")
    void lapXuan2024BracketsThePublishedInstant() {
        assertThat(termAt(LocalDateTime.of(2024, 2, 4, 15, 27), 8.0))
                .isEqualTo(SolarTerm.DAI_HAN);
        assertThat(termAt(LocalDateTime.of(2024, 2, 4, 17, 27), 8.0))
                .isEqualTo(SolarTerm.LAP_XUAN);
    }

    @Test
    @DisplayName("Deviation from the published instants stays inside the documented tolerance")
    void deviationFromPublishedInstantsIsBounded() {
        // At the published boundary instant, the distance this model reports to
        // its own nearest boundary IS the model's error. Asserting it directly
        // turns the tolerance from a claim in a comment into a checked fact -
        // and would fail loudly if a future change to SolarPosition made the
        // guard window in BaziEngine too small.
        double deviation1984 = SolarTerm.minutesToNearestTermBoundary(
                JulianDay.fromLocalDateTime(LocalDateTime.of(1984, 2, 4, 23, 18, 44), 8.0));
        double deviation2024 = SolarTerm.minutesToNearestTermBoundary(
                JulianDay.fromLocalDateTime(LocalDateTime.of(2024, 2, 4, 16, 27), 8.0));

        assertThat(deviation1984)
                .as("minutes from published Lập Xuân 1984 to the computed boundary")
                .isLessThan(DOCUMENTED_TOLERANCE_MINUTES);
        assertThat(deviation2024)
                .as("minutes from published Lập Xuân 2024 to the computed boundary")
                .isLessThan(DOCUMENTED_TOLERANCE_MINUTES);

        // And it is genuinely non-zero: the tolerance is not covering for an
        // exactness the model does not have.
        assertThat(deviation1984).isGreaterThan(1.0);
        assertThat(deviation2024).isGreaterThan(1.0);
    }

    @Test
    @DisplayName("minutesToNearestTermBoundary is largest mid-term and near zero at a boundary")
    void boundaryDistanceBehavesLikeADistance() {
        // Half a term is 15 degrees / 2 of solar longitude, about 7.6 days, so
        // the mid-term maximum is around 5480 minutes. The point of the check is
        // the shape, not the constant: monotone-ish, non-negative, zero-ish at
        // the crossing.
        double atBoundary = SolarTerm.minutesToNearestTermBoundary(
                JulianDay.fromLocalDateTime(LocalDateTime.of(2024, 2, 4, 16, 11), 8.0));
        double midTerm = SolarTerm.minutesToNearestTermBoundary(
                JulianDay.fromLocalDateTime(LocalDateTime.of(2024, 2, 12, 12, 0), 8.0));

        assertThat(atBoundary).isBetween(0.0, 5.0);
        assertThat(midTerm).isGreaterThan(1000.0);
    }

    private static SolarTerm termAt(LocalDateTime local, double utcOffsetHours) {
        return SolarTerm.atJulianDate(JulianDay.fromLocalDateTime(local, utcOffsetHours));
    }
}
