package io.destinyos.engines.numerology;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.LocalDate;
import java.util.List;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

/**
 * Golden tests for the Pythagorean calculation (research item R8).
 *
 * <p>Each vector here was found independently during R8's research, not
 * generated by this code — the discipline docs/RESEARCH_BLOCKERS.md requires
 * ("test vectors from the source, never generated by our implementation").
 */
class PythagoreanCalculatorTest {

    @Nested
    @DisplayName("Life Path — sourced worked examples")
    class LifePath {

        @Test
        @DisplayName("15 March 1990 reduces to 1 (source: numerologist.com worked example)")
        void marchFifteenNineteenNinety() {
            int result = PythagoreanCalculator.lifePath(LocalDate.of(1990, 3, 15));
            assertThat(result).isEqualTo(1);
        }

        @Test
        @DisplayName("Day 29 alone reduces to master number 11 (sourced example: 2+9=11)")
        void dayTwentyNinePreservesMasterNumber() {
            // Directly sourced: "If born on the 29th, add 2+9 = 11, and keep
            // it as 11 because it is a master number."
            assertThat(NumerologyReduction.reduce(29)).isEqualTo(11);
        }

        @Test
        @DisplayName("A birth date whose day is 29 preserves the day-component master number")
        void fullDateWithDayTwentyNine() {
            // Per-component reduction (R8's adopted policy): the day
            // component must independently show 11, not be diluted by
            // summing with month/year before any reduction happens.
            LocalDate birthDate = LocalDate.of(1985, 6, 29);

            // Reconstruct the per-component reasoning to assert the DAY
            // component specifically preserves the master number, which is
            // the property the adopted policy exists to protect.
            int dayComponent = NumerologyReduction.reduce(birthDate.getDayOfMonth());
            assertThat(dayComponent).isEqualTo(11);
        }

        @Test
        @DisplayName("Month reduces to a single digit (November, month 11, is itself a master number)")
        void novemberIsAMasterMonth() {
            assertThat(NumerologyReduction.reduce(11)).isEqualTo(11);
        }
    }

    @Nested
    @DisplayName("Expression — sourced worked example (John Doe)")
    class Expression {

        @Test
        @DisplayName("JOHNDOE sums to 35, reduces to 8 (source: Centre of Excellence worked example)")
        void johnDoeExpressionNumber() {
            // J=1 O=6 H=8 N=5 D=4 O=6 E=5 -> 35 -> 3+5=8, exactly as sourced.
            int result = PythagoreanCalculator.sumAllLetters("JOHNDOE");
            assertThat(result).isEqualTo(8);
        }

        @Test
        @DisplayName("Jane Marie Doe reduces to 1 (source: Centre of Excellence worked example)")
        void janeMarieDoeExpressionNumber() {
            int result = PythagoreanCalculator.sumAllLetters("JANEMARIEDOE");
            assertThat(result).isEqualTo(1);
        }
    }

    @Nested
    @DisplayName("Letter table — matches the sourced Pythagorean table exactly")
    class LetterTable {

        @Test
        @DisplayName("Every letter in the John Doe example matches its sourced value")
        void johnDoeLetterValuesMatchSource() {
            // J=1, O=6, H=8, N=5, D=4, E=5 as given by the source.
            assertThat(PythagoreanLetterTable.valueOf('J')).isEqualTo(1);
            assertThat(PythagoreanLetterTable.valueOf('O')).isEqualTo(6);
            assertThat(PythagoreanLetterTable.valueOf('H')).isEqualTo(8);
            assertThat(PythagoreanLetterTable.valueOf('N')).isEqualTo(5);
            assertThat(PythagoreanLetterTable.valueOf('D')).isEqualTo(4);
            assertThat(PythagoreanLetterTable.valueOf('E')).isEqualTo(5);
        }

        @Test
        @DisplayName("Lower-case letters resolve to the same value as upper-case")
        void caseInsensitive() {
            assertThat(PythagoreanLetterTable.valueOf('a')).isEqualTo(PythagoreanLetterTable.valueOf('A'));
        }

        @Test
        @DisplayName("A non-letter character is rejected rather than silently ignored")
        void nonLetterIsRejected() {
            org.assertj.core.api.Assertions.assertThatThrownBy(() -> PythagoreanLetterTable.valueOf('5'))
                    .isInstanceOf(IllegalArgumentException.class);
        }
    }

    @Nested
    @DisplayName("Soul Urge / Personality (Y-as-consonant simplification, R8 addendum)")
    class VowelConsonantSplit {

        @Test
        @DisplayName("JOHNDOE vowels (O,O,E) and consonants (J,H,N,D) partition all seven letters")
        void johnDoeVowelConsonantSplit() {
            int vowels = PythagoreanCalculator.sumVowels("JOHNDOE");
            int consonants = PythagoreanCalculator.sumConsonants("JOHNDOE");

            // O(6)+O(6)+E(5)=17 -> 1+7=8
            assertThat(vowels).isEqualTo(8);
            // J(1)+H(8)+N(5)+D(4)=18 -> 1+8=9
            assertThat(consonants).isEqualTo(9);
        }

        @Test
        @DisplayName("Y is always treated as a consonant (labelled simplification, not a sourced rule)")
        void yIsAlwaysAConsonant() {
            // "YYYY" has no vowel under the adopted simplification, so
            // sumVowels must be 0 and sumConsonants must carry all four Y's.
            assertThat(PythagoreanCalculator.sumVowels("YYYY")).isEqualTo(0);

            // Y=7, four of them = 28 -> 2+8=10 -> 1+0=1
            assertThat(PythagoreanCalculator.sumConsonants("YYYY")).isEqualTo(1);
        }

        @Test
        @DisplayName("Every letter is classified as exactly one of vowel or consonant")
        void everyLetterIsClassifiedExactlyOnce() {
            String name = "NGUYENVANAN";
            // This is an internal consistency check (both subsets use the
            // already-sourced letter table), not an independently sourced
            // claim about the split itself for this specific name.
            long vowelCount = name.chars().filter(c -> "AEIOU".indexOf(c) >= 0).count();
            long consonantCount = name.length() - vowelCount;

            assertThat(vowelCount + consonantCount).isEqualTo(name.length());
        }
    }

    @Nested
    @DisplayName("Full profile computation")
    class ProfileComputation {

        @Test
        @DisplayName("compute() normalizes the name and fills every field")
        void computeFillsEveryField() {
            NumerologyProfile profile = PythagoreanCalculator.compute(
                    "Nguyễn Văn An", LocalDate.of(1990, 3, 15));

            assertThat(profile.normalizedName().displayForm()).isEqualTo("Nguyen Van An");
            assertThat(profile.lifePath().value()).isEqualTo(1);
            assertThat(profile.expression()).isNotNull();
            assertThat(profile.soulUrge()).isNotNull();
            assertThat(profile.personality()).isNotNull();
            assertThat(profile.birthday().value()).isEqualTo(6); // day 15 -> 1+5=6
        }

        @Test
        @DisplayName("Every result is a valid single digit (1-9) or a master number")
        void everyResultIsValid() {
            NumerologyProfile profile = PythagoreanCalculator.compute(
                    "Trần Thị Bích Ngọc", LocalDate.of(1985, 6, 29));

            for (NumerologyResult result : List.of(profile.lifePath(), profile.expression(),
                    profile.soulUrge(), profile.personality(), profile.birthday())) {
                boolean validSingleDigit = result.value() >= 1 && result.value() <= 9;
                boolean validMaster = NumerologyReduction.isMasterNumber(result.value());
                assertThat(validSingleDigit || validMaster)
                        .as("%s = %d must be 1-9 or a master number", result.type(), result.value())
                        .isTrue();
                assertThat(result.isMasterNumber()).isEqualTo(validMaster);
            }
        }
    }
}
